### ISSUE TITLE
cms_page_publisher_public_id_key / Key publisher_public_id already exists

### ISSUE THREAD

**Issue by bartTC** [divio/django-cms#5872] opened 2017-02-06 14:30 UTC
This is not a bug report, more an insight. I believe this was already tacked in the related issues below. However none of them told specifically what is going on. I wrote this down for our internal bug tracker and I thought it would be useful to share with you.

You can close this right away or delete if you think it doesn't fit here. Maybe its all wrong too, then I'm open for discussion of course.

Related https://github.com/divio/django-cms/issues/806 https://github.com/divio/django-cms/issues/4940

---

Django-CMS 3.3, Django 1.9, Python 2.7

Sometimes pages fail to published, with an exception:

```
    IntegrityError /admin/cms/page/{var}/{var}/publish/
    Duplicate key value violates unique constraint
    "cms_page_publisher_public_id_key" DETAIL:
    Key (publisher_public_id)=(3137) already exists.
```

CMS Pages are twice in the cms_page table. One is the draft, one is the public page. Upon publishing, the draft is duplicated, and a relation between those two pages is set:

- publisher_public_id: This column is the ID of "the other" page. The name 
  is misleading, its more "related_page".

  This field contains the PK of the published Page if this page is a draft,
  or it contains the PK of the draft Page, if this page is the public one.

 - publisher_is_draft: This boolean indicates whether this Page is the
   draft or the public variant.

The error is: 

The page was published, it was duplicated and public Page has a PK set back to the draft page. However the draft page does not know about the public one. This PK is not set.

When you publish the draft again, it will duplicate the page again, and tries to save it, but fails, as there is already another orphan public page with the same publisher_public_id targeting the draft.

Code wise this makes sense, it can happen here: http://d.pr/i/xicV.png

1. It's a three step process. First the public page is created and saved.
2. Then the menu pool (navigation, breadcrumbs) is purged.
3. Then the original draft page is updated with the PK of the new publish page.

Either 2 or 3 fails here. The Public page is created, however its an orphan, as the draft variant does not know about it.

The fix below tries to find those orphan, public pages and fixes the missing primary keys in the draft pages.

```
from cms.models import Page

for p in Page.objects.filter(publisher_is_draft=False, publisher_public_id__isnull=False):
    draft = Page.objects.get(id=p.publisher_public_id)
    if draft.publisher_public_id == None:
        print "Error in:", draft.id, draft.get_title('en')
        draft.publisher_public_id = p.id
        draft.save()
```

We were able to reproduce this issue in an import script. Import hundreds of CMS pages, and then cancel it using ctrl+c will sporadically lead to this issue. We wrapped the page creation process in a transaction which fixed the issue for us. 

Django-CMS 3.4 did the same (as I understand) so my assumption is, that this is no longer an issue with 3.4+.

**Comment by czpython** [comment] 2017-02-10 18:25
Hello @bartTC,
Thanks for the info.
I'm closing this as a duplicate of https://github.com/divio/django-cms/issues/4940
Will continue the conversation there.

**Closed by czpython** 2017-02-10 18:25 UTC
