### ISSUE TITLE
Column does not exist in tests with multiple databases

### ISSUE THREAD

**Issue by igorkud90** [divio/django-cms#4798] opened 2015-12-01 10:50 UTC
I use multiple databases in my project: master and log_db. When i updated to django-cms==3.1.4 and started the tests, i've got error in 0005_auto_20140924_1039.py migration, when creating test log database:
```
Creating test database for alias 'default'...
Creating test database for alias 'log_db'...
Traceback (most recent call last):
  File "/home/user/Downloads/pycharm-5.0/helpers/pycharm/django_test_manage.py", line 129, in <module>
    utility.execute()
  File "/home/user/Downloads/pycharm-5.0/helpers/pycharm/django_test_manage.py", line 104, in execute
    PycharmTestCommand().run_from_argv(self.argv)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/user/Downloads/pycharm-5.0/helpers/pycharm/django_test_manage.py", line 91, in handle
    failures = TestRunner(test_labels, verbosity=verbosity, interactive=interactive, failfast=failfast, keepdb='--keepdb' in sys.argv)
  File "/home/user/Downloads/pycharm-5.0/helpers/pycharm/django_test_runner.py", line 256, in run_tests
    extra_tests=extra_tests, **options)
  File "/home/user/Downloads/pycharm-5.0/helpers/pycharm/django_test_runner.py", line 156, in run_tests
    return super(DjangoTeamcityTestRunner, self).run_tests(test_labels, extra_tests, **kwargs)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/test/runner.py", line 147, in run_tests
    old_config = self.setup_databases()
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/test/runner.py", line 109, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/test/runner.py", line 299, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/backends/creation.py", line 377, in create_test_db
    test_flush=True,
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/cms/migrations/0005_auto_20140924_1039.py", line 135, in move_to_mp
    for page in pages:
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/models/query.py", line 141, in __iter__
    self._fetch_all()
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/user/project-env/project/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column cms_page.level does not exist
LINE 1: ...cation_urls", "cms_page"."application_namespace", "cms_page"...
                                                             ^
```
router:
``` python
class UserLoggerRouter(object):

    def db_for_read(self, model, **hints):
        if model._meta.app_label == 'user_logger':
            return 'log_db'
        return None

    def db_for_write(self, model, **hints):
        if model._meta.app_label == 'user_logger':
            return 'log_db'
        return None

    def allow_relation(self, obj1, obj2, **hints):
        if obj1._meta.app_label == 'user_logger' or \
           obj2._meta.app_label == 'user_logger':
           return True
        return None

    def allow_migrate(self, db, model):
        if db == 'log_db':
            return model._meta.app_label == 'user_logger'
        elif model._meta.app_label == 'user_logger':
            return False
        return None
```

**Comment by viatoriche** [comment] 2015-12-02 14:09
I have this problem too

**Comment by mkoistinen** [comment] 2015-12-03 13:47
Thanks for the report @igorkud90 (and @viatoriche). Would you be able to dig into this a little deeper to be more specific about how the CMS is doing something wrong?

**Comment by mvid** [comment] 2016-03-19 22:16
I have this problem too.

**Comment by mvid** [comment] 2016-03-19 22:24
I had this issue as well. @igorkud90, you are likely using the old style of the allow_migrate method. You should use the new style defined here:
https://docs.djangoproject.com/en/1.9/topics/db/multi-db/

**Comment by diegoponciano** [comment] 2016-06-06 18:46
@mvid How did you fix it?   
I have the same issue using multiple databases, only difference being I'm not using routers.

**Comment by mvid** [comment] 2016-06-06 21:53
@diegoponciano My solution was to update the routers to use the new syntax for `allow_migrate`. If you aren't using routers, I don't know what to do if you aren't using routers. How is it even possible to use multiple databases without routers?

**Comment by FinalAngel** [comment] 2016-06-07 06:52
@divio/django-cms-core @mkoistinen anything we still can do here?

**Comment by naush** [comment] 2016-06-26 23:18
See: https://github.com/divio/django-cms/issues/4798

Could be the same problem. Not sure if the bug affects router as well.

**Comment by czpython** [comment] 2016-08-27 02:53
Closing as confirmed duplicate of https://github.com/divio/django-cms/issues/5093

**Closed by czpython** 2016-08-27 02:53 UTC
Labels: needs more info
