### ISSUE TITLE
After upgrading 3.1.1, makemigrations creates a cms migration

### ISSUE THREAD

**Issue by pa-jama** [divio/django-cms#4222] opened 2015-07-01 02:42 UTC
As in title,
after 
    
    ./manage.py makemigrations

    Migrations for 'cms':
      0013_auto_20150701_1440.py:
      - Change managers on pageuser

...

    class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20150607_2207'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pageuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]

**Comment by yakky** [comment] 2015-07-01 03:35
I can't reproduce this. Could you provide more context? Do you use custom user modules?

**Comment by pa-jama** [comment] 2015-07-01 04:02
Yes, but even removing that app from installed_apps I still get it.
I just reproduced this by:

[new virtualenv]

    pip install "django-cms==3.1.1"
    django-admin startproject

add to settings.py:

    SITE_ID=1

    INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cms',
    'treebeard',)
    LANGUAGE_CODE = 'en'
    LANGUAGES = [
    ('en', 'English'),]

    ./manage.py makemigrations

**Comment by pa-jama** [comment] 2015-07-02 03:40
ALso,

Cloning this repo, new virtual env, 
    pip install -r test_requirements/django-1.8.txt, 
    python develop.py makemigrations 

Also creates it? It also creates random migrations for djangocms_link too, which I didn't encounter because I'm not using it.


    Migrations for 'djangocms_link':
      0004_auto_20150702_1535.py:
        - Alter field anchor on link
        - Alter field mailto on link
        - Alter field url on link
    Migrations for 'cms':
      0013_auto_20150702_1535.py:
         - Change managers on pageuser

**Comment by yakky** [comment] 2015-07-03 07:30
Apparently it's Django 1.87 triggering a new migration ...

**Comment by yakky** [comment] 2015-07-03 07:32
Thanks @pa-jama

**Comment by yakky** [comment] 2015-07-04 12:45
Fixed by #4232

**Closed by yakky** 2015-07-04 12:45 UTC
Labels: has patch, status: accepted
