### ISSUE TITLE
create/delete context menu in /cms/page/ is not working

### ISSUE THREAD

**Issue by otg-sandrey** [divio/django-cms#4378] opened 2015-08-25 14:37 UTC
In admin interface open /cms/page/.

Right click at a link to any of the pages. A context menu will open and it contains two items:
- CREATE
- DELETE

"CREATE" seems does nothing.
"DELETE" removes the page from the list, but it is back if I click F5

Also the menu is not available for all pages but last one in the list. The problem is that the menu is open behind (in Z-order) next page line frame.

**Comment by yakky** [comment] 2015-08-25 15:12
Which CMS version are you using?

**Comment by otg-sandrey** [comment] 2015-08-25 15:25
django-cms==3.0.13

**Comment by yakky** [comment] 2015-08-27 05:53
@otg-sandrey this is actually a remnant of the past. The new UI revisions will fix the entire page tree, still not finalised yet

**Comment by FinalAngel** [comment] 2015-09-18 06:49
@otg-sandrey I tried to reproduce with the latest version and I'm getting:

![image](https://cloud.githubusercontent.com/assets/270307/9953548/106e8f3e-5de2-11e5-9474-bb5cb54a6d0c.png)

Could you provide a screenshot?

**Comment by FinalAngel** [comment] 2015-10-30 12:54
duplicate of https://github.com/divio/django-cms/issues/4144

**Closed by FinalAngel** 2015-10-30 12:54 UTC
Labels: component: frontend, component: ux, kind: bug, needs patch
