### ISSUE TITLE
Missed migration django-cms: 3.0.12

### ISSUE THREAD

**Issue by skrzypek** [divio/django-cms#3977] opened 2015-04-02 13:58 UTC
`./manage.py makemigrations`

Create migrate for `cms`
```
Migrations for 'cms':
  0004_auto_20150402_1352.py:
    - Alter field plugin_type on cmsplugin
    - Alter field has_url_overwrite on title
```

code:

```
dependencies = [                                                            
    ('cms', '0003_auto_20140926_2347'),                                     
]                                                                           
                                                                            
operations = [                                                              
    migrations.AlterField(                                                  
        model_name='cmsplugin',                                             
        name='plugin_type',                                                 
        field=models.CharField(verbose_name='plugin name', db_index=True, editable=False, max_length=50),
        preserve_default=True,                                              
    ),                                                                      
    migrations.AlterField(                                                  
        model_name='title',                                                 
        name='has_url_overwrite',                                           
        field=models.BooleanField(editable=False, verbose_name='has URL overwrite', db_index=True, default=False),
        preserve_default=True,                                              
    ),                                                                      
]                                                                           
```

Django-cms: 3.0.12
Dajngo: 1.7.7

It's looks like someone forgot add a migration.

**Comment by yakky** [comment] 2015-04-03 06:56
Duplicate of #3572
Will be fixed in 3.0.13 due soon

**Closed by yakky** 2015-04-03 06:56 UTC
