### ISSUE TITLE
Issues with 2 LANGUAGES but only 1 CMS_LANGUAGE

### ISSUE THREAD

**Issue by casio** [divio/django-cms#3425] opened 2014-08-29 10:08 UTC
I'm running into several issues with my attempt to provide a localizable admin for a site with only one locale.

Using Django 1.6.5, CMS 3.0.5 with these i18n settings:

```
USE_I18N = True
USE_L10N = True
LANGUAGE_CODE = 'en'
LANGUAGES = (
    ('en', gettext('en')),
    ('de', gettext('de')),
)
CMS_LANGUAGES = {
    1: [
        {
            'code': 'de',
            'name': gettext('German'),
            'public': True,
        }
    ]
}
```

When browsing the admin in 'en', the add page gives me 'Please correct errors below' with no actual validation errors shown when I try to save.

Manually modifying the admin URLs to eg. `...&language=de` helps for that single request but of course doesnt help the problem - the frontend editing will show further issues related to the wrong language being selected for editing.

I'm actually trying to keep the admin in 'en' locale for a single-locale site in another locale.
Maybe I'm using the wrong approach here?

**Comment by mkoistinen** [comment] 2015-02-20 21:31
@casio, can you try this in 3.0.10 and let us know if this is still an issue? I know some changes have been committed in this general area, it'd be good to know if this is still something that we should address.

**Comment by mkoistinen** [comment] 2015-05-11 21:02
@casio, can you try this in 3.0.13? Let us know!

**Comment by czpython** [comment] 2017-03-02 14:50
Closing as we're unable to reproduce this.
Please open a new ticket if this issue is present on latest cms (3.4.2).

**Closed by czpython** 2017-03-02 14:50 UTC
Labels: needs more info, needs patch, needs tests
