### ISSUE TITLE
IntegrityError with 10 placeholders on one page.

### ISSUE THREAD

**Issue by JurajKavka** [divio/django-cms#5039] opened 2016-02-28 16:03 UTC
Hello,

i have more than 10 placeholders on one webpage. When i't trying to add plugin to the 10th placeholder it works, but publish changes fails with ERROR 500.  When i try to add 11th placeholder - same error.

`IntegrityError at /sk/admin/cms/page/1/sk/publish/
duplicate key value violates unique constraint "cms_cmsplugin_path_7692c19a7d5df9d5_uniq"
DETAIL:  Key (path)=(000A) already exists.`

Please, copy and paste this output to the wider editor, to see state in table `cms_cmsplugin`.

`+----+----------+----------+-------------+-------------------------------+-------------------------------+-----------+----------------+-------+----------+------+
| id | position | language | plugin_type |         creation_date         |         changed_date          | parent_id | placeholder_id | depth | numchild | path |
+----+----------+----------+-------------+-------------------------------+-------------------------------+-----------+----------------+-------+----------+------+
|  1 |        0 | sk       | TextPlugin  | 2016-02-28 16:42:14.789136+01 | 2016-02-28 16:42:16.990363+01 |           |              2 |     1 |        0 | 0001 |
|  3 |        0 | sk       | TextPlugin  | 2016-02-28 16:42:26.189419+01 | 2016-02-28 16:42:28.55339+01  |           |              3 |     1 |        0 | 0003 |
|  4 |        0 | sk       | TextPlugin  | 2016-02-28 16:42:33.718335+01 | 2016-02-28 16:42:35.695503+01 |           |              4 |     1 |        0 | 0004 |
|  5 |        0 | sk       | TextPlugin  | 2016-02-28 16:42:40.496814+01 | 2016-02-28 16:42:42.457569+01 |           |              5 |     1 |        0 | 0005 |
|  6 |        0 | sk       | TextPlugin  | 2016-02-28 16:42:14.789136+01 | 2016-02-28 16:42:45.430397+01 |           |             16 |     1 |        0 | 0006 |
|  7 |        0 | sk       | TextPlugin  | 2016-02-28 16:42:26.189419+01 | 2016-02-28 16:42:45.450672+01 |           |             17 |     1 |        0 | 0007 |
|  8 |        0 | sk       | TextPlugin  | 2016-02-28 16:42:33.718335+01 | 2016-02-28 16:42:45.47063+01  |           |             18 |     1 |        0 | 0008 |
|  9 |        0 | sk       | TextPlugin  | 2016-02-28 16:42:40.496814+01 | 2016-02-28 16:42:45.491471+01 |           |             19 |     1 |        0 | 0009 |
| 10 |        0 | sk       | TextPlugin  | 2016-02-28 16:42:51.713619+01 | 2016-02-28 16:42:55.516187+01 |           |              6 |     1 |        0 | 000A |
+----+----------+----------+-------------+-------------------------------+-------------------------------+-----------+----------------+-------+----------+------+`

I reinstalled whole web with new database but problem persists. 

Tnank you.

**Comment by evildmp** [comment] 2016-02-29 02:05
I can't replicate this.

I am using SQLite 3. I have ten placeholders, each with a text plugin in it.

Are you able to create a failing test case, or failing that some more information on how to reproduce the error?

**Comment by JurajKavka** [comment] 2016-02-29 09:08
at first i need to mention that im using `django-cms==3.1.3` with `django==1.7.10`.

My page was working with some placeholders, but in new version i have added few more placeholders.

anyway, i have resolved this isue. i have production server with caching in redis and my django-cms page uses default caching for plugins, pages, placeholders, so these steps helped me:

- close browser with page loaded
- stop uwsgi daemon 
- ./manage.py cmd fix-tree 
- go to `redis-cli`, `select DB`, `flushdb`
- start uwsgi daemon

So I think that problem was in combination of corrupted tree and cache. I cannot say, how to corrupt the tree, but in my case `fix-tree` was not enough.

**Comment by evildmp** [comment] 2016-02-29 22:10
I think we'll have to close this as a non-issue, since we can't replicate it, but please feel free to re-open.

**Closed by evildmp** 2016-02-29 22:10 UTC
Labels: kind: bug, needs more info, status: non-issue

**Comment by JurajKavka** [comment] 2016-02-29 22:12
Ok thank you for your time.
