### ISSUE TITLE
Placeholder template tag does not work with conditional "extends" in template

### ISSUE THREAD

**Issue by LeaFin** [divio/django-cms#5910] opened 2017-03-24 07:34 UTC
### Summary
I changed a page template from:
```
{% extends "base.html" %}
{% load i18n staticfiles cms_tags %}

{% block body_class %}tpl-fullwidth{% endblock %}

{% block content %}
    {% placeholder "content" %}
{% endblock content %}
```

to

```
{% extends request.is_ajax|yesno:"base_ajax.html,base.html" %}
{% load i18n staticfiles cms_tags %}

{% block body_class %}tpl-fullwidth{% endblock %}

{% block content %}
    {% placeholder "content" %}
{% endblock content %}
```

### Expected behaviour
If the request isn't ajax, I expect the behaviour of the two versions to be excately the same.

### Actual behaviour
A not ajax request with the new version of the template extends the base.html template correctly.
But the placeholder isn't rendered. In the edit structure mode, the palceholder "content" does not show neither.

### Environment

* Python version: 2.7.11
* Django version: 1.8.16
* django CMS version: 3.4.2

**Comment by czpython** [comment] 2017-04-08 21:01
Hello @LeaFin,
This was a design decision.

When a page is rendered, the first time we encounter a {% placeholder %}, the plugin renderer will scan the page template in search for `{% placeholder %}` tags, then we use these tags to create any placeholder found on the template that does not exist on the page, and then attach it to the page via a many to many field.

Then if the placeholder exists on the page, it gets rendered.

The problem is that the scanning for placeholders on a template is done outside of the page rendering itself, meaning that there's no context present when this happens.

This is to avoid rendering the page every time you change the page template or create a new page.

Because of this, any dynamic `{% extends %}` call would fail to produce the desired placeholders because context is **not** present.

To avoid this, we explicitly disabled the scanning for placeholders if the template contains an `{% extends %}` tag.

I think the most we can do here is document this limitation.

/cc @divio/django-cms-core

**Comment by czpython** [comment] 2017-05-08 23:23
Closing as duplicate of https://github.com/divio/django-cms/issues/1847

**Closed by czpython** 2017-05-08 23:23 UTC
Labels: component: documentation, status: accepted
