### ISSUE TITLE
Fix bugs that make fix-tree and delete_orphaned_plugins necessary

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3736] opened 2015-01-07 21:57 UTC
Simply put, the code should not corrupt the tree or leave orphaned plugins laying around. Orphaned plugins are a frequent headache. The current situation requires developers to log in and run a command to repair the database once the site starts giving 500 errors to users. This is not a good way to run a production website.

Part of the issue is that it's possible for django-cms and plugins to overwrite treebeard data by saving stale data after treebeard makes updates. I found an example of this type of corruption in https://github.com/divio/djangocms-text-ckeditor/issues/212 where tree data was overwritten due to incorrect order of operations. 

We need tighter controls on when treebeard operations take place. Haven't fully investigated the feasibility but would be good if we could prevent CMS Plugins from ever setting these mptt values directly, perhaps using [update_fields](https://docs.djangoproject.com/en/1.7/ref/models/instances/#specifying-which-fields-to-save). Only treebeard should ever touch these values.

Haven't dug through all the code paths that might contribute to the orphaned plugins situation but we may need to rethink the 'save CMSPlugin when all the user really needed was a form to be rendered'. CMSPlugin's should only be saved to the db when a CMSPlugin subclass is saved to the db, wrapped in a transaction.

This is somewhat related to #3157 & #3158 but I think we should focus on squashing the bugs that lead to these issues in the first place. Those tickets are just asking for errors to be silenced in production, but there may be too many code paths that expect valid, intact data for that approach to work.

**Comment by yakky** [comment] 2015-01-08 11:46
@jsma the root of the stale plugins issue should be solved by #3516

**Comment by jsma** [comment] 2015-01-08 16:36
Ah, I had seen that PR before but totally blanked on it yesterday, tunnel vision. I'll need some people smarter than me to weigh in on the issue where Page/CMSPlugin's can inadvertently overwrite freeboard fields with stale data.

**Comment by yakky** [comment] 2015-01-08 16:43
Ok, let us release 3.0.8 in the next few days, sync develop with 3.0.x branch and merge all the outstanding PRs, so we have a more stable base to investigate issues like this

**Comment by jsma** [comment] 2015-01-08 18:44
Damn you auto-correct! *treebeard* not 'freeboard'...

Anyway, sounds good. I'll try to review #3516 in the meantime.

**Comment by mkoistinen** [comment] 2015-01-12 10:17
+1

**Comment by jsma** [comment] 2015-12-17 21:41
I just experienced this issue again on 3.2 with an orphaned `cmsplugin_filer_file.models.FilerFile` instance. Quickly reviewed #3516 but unclear to me what, if anything, needs to be updated in cmsplugin-filer or if there are still bugs lurking in django-cms.

**Comment by yakky** [comment] 2015-12-18 08:19
@jsma #3516 is not merged, we need to wait for the effort to cleanup the frontend testing stuff before trying to get it in

**Comment by czpython** [comment] 2016-05-26 13:31
I agree that all issues should be taken care of instead of silently failing.
That said, the apphooks and menus exceptions are usually caused by changes in the code base (removing an apphook class without properly uninstalling it).

https://github.com/divio/django-cms/pull/3516 has been merged on CMS 3.3.
That should fix all problems with orphan plugins while keeping backwards compatibility
with any existing orphan plugins (in case on upgrade didn't run remove_orphan_plugins).

Regarding tree corruptions, we've made a lot of effort on 3.3 to bring these to light and fix as many as possible. The ones that remain will have to be addressed individually as reproducing these corruptions is not very easy due to the amount of combinations.

Last, using update_fields is a great idea, we started doing this on 3.2 to avoid the constant full row updates and this has brought much more stability and speed.

Closing this to track any new plugin issue individually.

**Closed by czpython** 2016-05-26 13:31 UTC
Labels: blocker, kind: bug, status: accepted
