### ISSUE TITLE
Plugin edit buttons not working when render_plugin is not called in the template

### ISSUE THREAD

**Issue by petrklus** [divio/django-cms#5085] opened 2016-03-15 18:08 UTC
I have created very simple plugin to allow per-block translation of a page. It works by creating Translated Block Holder, which can then contain multiple TranslatedBlock children. Each child can have

I am having problems when using the structure editor. I can add and edit Holder objects without any problems, however, their children do not seem to be editable. Nothing happens when I click the "pencil" icon, and double-click shows the menu of the parent, not the actual object.

In the screenshot below, I can click the "pencil" for the translated block holder and the first block underneath - however, I cannot even expand the second (de) block - nothing happens on click. No errors are reported in console and I've tested this both on Firefox and Chrome.

![image](https://cloud.githubusercontent.com/assets/1115667/13788647/e942fd96-eae0-11e5-9814-2882515ea8a4.png)

[cnk_djangocms_translated_block.zip](https://github.com/divio/django-cms/files/174522/cnk_djangocms_translated_block.zip)

**Comment by petrklus** [comment] 2016-03-18 14:21
Just upgraded to 3.2.3 and still seeing the issue.

**Comment by petrklus** [comment] 2016-03-18 14:31
Furthermore, the plugins that are "broken" also cannot be dragged anywhere - it looks like they are missing some init parameters.

**Comment by petrklus** [comment] 2016-03-18 14:52
I think have have found the problem, though not sure what the solution may be. In my template, I've got the following:

    {% if LANGUAGE_CODE == translatedblock.show_on_lang %}
    <div class="">
    {% for plugin in translatedblock.child_plugin_instances %}
    	{% render_plugin plugin %}
    {% endfor %}
    </div>
    {% else %}
    
    {% endif %}

Which means that the render_plugin is only called when the language matches. On the plugins where the render_plugin was omitted, the frontend admin did not work. Any tips how to make a render_plugin "dry run"?

**Comment by vxsx** [comment] 2016-03-18 14:53
It looks like this problem happens because some plugins have no markup in the DOM ), and historically we rely on the markup to store the data about the plugin, and if we cannot access this data the plugin is considered immovable (and it's also not initialized correctly).

It is a problem that is on our list, it's going to be addressed in it's current state soon.

**Comment by petrklus** [comment] 2016-03-18 14:54
@vxsx crossed wires! :) 

Any tips how to effectively run {% render_plugin plugin %} without the output being shown? My use case is to allow simple customisation of a page without the need to translate/copy all of the contents.

**Comment by vxsx** [comment] 2016-03-18 15:01
Well, ugly quickfix would be to check if cms user is logged in and render everything, but non-matching ones in invisible divs, and if not to not render.

something like this should probably work:

```
{% if LANGUAGE_CODE == translatedblock.show_on_lang %}
<div class="">
{% for plugin in translatedblock.child_plugin_instances %}
    {% render_plugin plugin %}
{% endfor %}
</div>
{% elsif if request.toolbar.show_toolbar %}
<div style="display: none">
{% for plugin in translatedblock.child_plugin_instances %}
    {% render_plugin plugin %}
{% endfor %}
</div>
{% endif %}
```

**Comment by petrklus** [comment] 2016-03-18 15:15
Thank you @vxsx  - I've done the same except for the toolbar condition, was wondering how to remove the content from end-user facing pages. Glad it was a bug and that I was not getting crazy :)

**Comment by macolo** [comment] 2016-05-31 15:44
Thanks, saved my life for the second time now.

**Comment by vxsx** [comment] 2016-07-08 15:05
Fixed by #5375

**Closed by vxsx** 2016-07-08 15:05 UTC
Labels: component: frontend, status: accepted, status: has patch

**Comment by rafalp** [comment] 2017-06-30 15:35
I'm currently experiencing this issue in Django CMS 3.4.4.

**Comment by nibytes** [comment] 2017-07-17 21:06
I too have it problem but only on home page, and in browser js console 
`TypeError: this.ui.container.data(...).push is not a function[Подробнее]  bundle.toolbar.min.js:5:18129
	initialize http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:5:18129
	o http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:4:6267
	f._initializeTree/< http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:6:8942
	each http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:1:14646
	f._initializeTree http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:6:8908
	<анонимная> http://127.0.0.1:8000/:2104:5
	c http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:2:6423
	fireWith http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:2:7245
	ready http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:2:9104
	h http://127.0.0.1:8000/static/cms/js/dist/3.4.4/bundle.toolbar.min.js:1:1607`

**Comment by creimers** [comment] 2018-08-30 07:08
I'm experiencing this behaviour in 3.5.2.

**Comment by creimers** [comment] 2018-08-30 07:35
@vxsx For me it's still the same on the `release/3.5.x` branch.

**Comment by vxsx** [comment] 2018-08-30 08:42
@creimers in that case could you please open a new ticket with steps to reproduce the problem (and / or a sample project that has it)

**Comment by zypro** [comment] 2019-07-18 07:59
Is there a new issue opened? Having same issue with v3.5.3, but only for certain child plugin.
