### ISSUE TITLE
Redirect to another CMS Page

### ISSUE THREAD

**Issue by darioalbanesi** [divio/django-cms#4333] opened 2015-07-31 13:51 UTC
Setting a redirect to another cms page is pretty simple and very good with the support of autocomplete. However there is a bug when changing the name and slug of the target page. At the moment it doesn't adapt the redirect automatically. 

django CMS 3.0.13
django 1.6.11.post1

**Comment by FinalAngel** [comment] 2015-10-14 06:43
@darioalbanesi can you test this again with the latest 3.2.0 develop version?

**Comment by FinalAngel** [comment] 2015-10-14 07:18
confirmed, still valid

**Comment by FinalAngel** [comment] 2015-10-29 15:15
duplicate of https://github.com/divio/django-cms/issues/2916

**Closed by FinalAngel** 2015-10-29 15:15 UTC
Labels: kind: enhancement, status: accepted
