### ISSUE TITLE
Django CMS with MariaDB throws errors on manage.py migrate

### ISSUE THREAD

**Issue by ursomniac** [divio/django-cms#6115] opened 2017-11-08 13:59 UTC
### Summary

When setting up Django CMS on a site using MariaDB, you can't get past the 0008_auto_20150121_0059 migration file.  Django throws the error:

ValueError: Found wrong number (0) of constraints for cms_page(publisher_is_draft, application_namespace)

If you hack the migration file (i.e., make the constraint match the table) you can get past this, but you IMMEDIATELY run into similar issues with cms-filer, cms-picture, etc.   

I've tried this on other vagrant boxes with both MySQL 5.7.18 and Postgres 9.2(?) and the install works flawlessly.  However, I've also tested with MariaDB v5.5, and it fails in exactly the same place.   AFAICT MariaDB is simply not compatible with Django CMS - but I can't for the life of me figure out why.

### Environment

* Python version:  2.7.5
* Django version:  1.8.18
* django CMS version: 3.4.5
* MariaDB version:  mysql  Ver 15.1 Distrib 10.2.10-MariaDB, for Linux (x86_64) using readline 5.1 
* OS: CentOS 7.4 (on a vagrant box bento/centos-7.4)

### Expected behaviour

Migrating the database from a cold install should work.

### Actual behaviour

`% manage.py migrate` crashes as described above.

**Comment by czpython** [comment] 2017-11-08 14:11
Thanks for reporting this.
Closing as duplicate of https://github.com/divio/django-cms/issues/5716

**Closed by czpython** 2017-11-08 14:11 UTC
