### ISSUE TITLE
CMS installer issues on Windows 7

### ISSUE THREAD

**Issue by JohnKovalsky** [divio/django-cms#3794] opened 2015-01-23 18:03 UTC
I wanted to install djangocms on Windows 7 (updates up to date, service pack1)
and I followed instruction on:
http://docs.django-cms.org/en/support-3.0.x/introduction/install_from_scratch.html

After I run command `djangocms -p . mysite` I got following error:
 `File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "C:\Python27\Lib\runpy.py", line 72, in _run_code
   exec code in run_globals
 File "D:\VIRTUAL_ENV\djangoCMS\Scripts\djangocms.exe\__main__.py", line 9, in <module>
 File "D:\VIRTUAL_ENV\djangoCMS\lib\site-packages\djangocms_installer\main.py", line 30, in execute
   django.create_project(config_data)
 File "D:\VIRTUAL_ENV\djangoCMS\lib\site-packages\djangocms_installer\django\__init__.py", line 43, in create_project
   subprocess.check_call(['django-admin.py', 'startproject'] + args)
 File "C:\Python27\Lib\subprocess.py", line 499, in check_call
   retcode = call(*popenargs, **kwargs)
 File "C:\Python27\Lib\subprocess.py", line 486, in call
   return Popen(*popenargs, **kwargs).wait()
 File "C:\Python27\Lib\subprocess.py", line 672, in __init__
   errread, errwrite)
 File "C:\Python27\Lib\subprocess.py", line 882, in _execute_child
   startupinfo)
WindowsError 1 is not a valid win32 application`

Extension assocation `.py` was set up first. 
I solved it by adding named param `shell=True` in `subprocess.check_call(['django-admin.py', 'startproject'] + args)` at site-packages\djangocms_installer\django\__init__.py", line 43

**Comment by yakky** [comment] 2015-01-23 18:36
Duplicate of nephila/djangocms-installer#160

**Closed by yakky** 2015-01-23 18:36 UTC

**Comment by yakky** [comment] 2015-01-25 10:49
@JohnKovalsky would you please check by installing https://github.com/nephila/djangocms-installer/archive/feature/hotfixes.zip?

**Comment by StevenMapes** [comment] 2015-02-05 11:42
I had the same problem and downloaded and installed the hotfix which has solved the problem on my Windows 7 box (Python 3.4)
