### ISSUE TITLE
cache invalidation while using CMS_PAGE_CACHE ?!?

### ISSUE THREAD

**Issue by jedie** [divio/django-cms#6372] opened 2018-05-15 15:50 UTC
I enabled `CMS_PAGE_CACHE` and use `django.middleware.cache.UpdateCacheMiddleware` and `django.middleware.cache.FetchFromCacheMiddleware` as described here: http://djangocms.readthedocs.io/en/latest/how_to/caching/

If i now change and publish a page, then i get the old cached version, isn't it?!?

I think this should be documented, see also #5307

What's about to remove the changes page form cache? So that the next access from anonymous will get the up-to-date content?

**Comment by czpython** [comment] 2018-05-17 01:27
Closing as duplicate of https://github.com/divio/django-cms/issues/5307
This is a documentation issue, the page cache does not interact with django's cache middleware in any way.

**Closed by czpython** 2018-05-17 01:27 UTC
