### ISSUE TITLE
Undo/history and Multi Language

### ISSUE THREAD

**Issue by doctormo** [divio/django-cms#3599] opened 2014-11-21 02:33 UTC
The multi-language support is causing issues with undo. We've had page's plugins all be deleted because of an edit on some other language variant for a page only for undo to delete the first language's content.

The consistency of the language system has me baffled.

**Comment by FinalAngel** [comment] 2015-11-02 16:04
@doctormo any further help would be appreciated, we cannot reproduce it this far. Would you be able to provide video captures?

**Comment by Frigory33** [comment] 2016-07-07 17:26
Hello,
I'm another contributor of the Inkscape website.

Here are two videos:
* https://files.cloud.orange.fr/cloudUpDown/V06.00.08/UpDownCloud/downloadFileAnonymous?fileId=__upload%2Fdjango-cms-undo-bug-long.ogv&shareToken=SjMxQKt86u1077019c7c
* https://files.cloud.orange.fr/cloudUpDown/V06.00.08/UpDownCloud/downloadFileAnonymous?fileId=__upload%2Fdjango-cms-undo-bug.ogv&shareToken=SjMxQKt86u1077019c7c

I launched randomly the first video and had fun with a local copy of the Inkscape website around Martin's procedure. I create an English page and a French translation, then I add a text plugin into it at the same time. (I also added a Spanish translation, but it is useless.) Then I click on History > Undo on the French translation, this doesn't change the French translation and makes the text plugin disappear in the English one. I didn't publish any page.

The second video is more focused on the procedure: I create a page in English and a French translation, I save a text plugin into each of them still at the same time. Again, I forgot to publish and I did History > Undo on the French translation and the result, again, is the French page unchanged, and the English text plugin not removed but empty (well, I discovered it by publishing the English page — it's a mess at the end).

Note: please copy the videos elsewhere if you need archives; I used my personal cloud to store them and I probably won't keep these files more than a year.

**Comment by Frigory33** [comment] 2016-09-03 09:43
Please admire how the settings in our shield plugin disappeared thanks to a click on ‘Revert to Live’ from a translator after he had wrongly put his translation on the English plugin:
http://i.imgur.com/V4JixQG.png

Saved state on a local instance:
http://i.imgur.com/sKKUPgY.png

It seems the data cannot be restored by an additional revert.
Thanks for marking this bug as a blocker, hope it'll be fixed soon.

**Comment by doctormo** [comment] 2016-10-06 17:53
This might be related to #5722 as the plugin uses a reverse foreignkey collection for tabs. While this is covered in copy_relations, reversion doesn't know anything about it at all.

**Comment by czpython** [comment] 2017-03-02 14:35
This was one of the shortcomings of the old revision system.
It wasn't multilingual so when undoing changes in one language, it would undo on all.

This has been addressed by the undo/redo functionality of djangocms-history.

**Closed by czpython** 2017-03-02 14:35 UTC
Labels: blocker, component: reversion, kind: bug, status: accepted

**Comment by Moini** [comment] 2017-03-02 14:44
@czpython : sorry for the off-topic question: is djangocms-history a replacement for the removed history / revision in django-cms proper? (We don't have a page history anymore in django 1.8.17, and no undo/redo, but it would be nice to have it back.)

**Comment by czpython** [comment] 2017-03-02 14:56
Hello @Moini,
djangocms-history adds back the undo/redo functionality to the cms but its not a direct replacement of revisions because you can't recover deleted pages or go back in history more than 24h.

**Comment by Moini** [comment] 2017-03-02 15:10
Thank you, @czpython ! Good to know, I hope we can include it :)
