### ISSUE TITLE
Figure out better German translation for sites vs pages

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#5535] opened 2016-07-12 09:03 UTC
Currently both `Page` and `Site` are translated as `Seite` in German.
This can be very confusing in admin as well as the toolbar, where the same word is used for different things:
![screen shot 2016-07-12 at 10 52 17](https://cloud.githubusercontent.com/assets/14330/16761051/c64b9c80-481e-11e6-9835-24d465794735.png)

The first `Seiten...` is for Pages. The second "Seiten >" is for Sites (`django.contrib.site`).

IMHO the German word should also just be `Sites` or `Websites` which are both valid German words (see http://www.duden.de/rechtschreibung/Website).

Sounds like an easy change, right? _Wrong!_

The trouble is, that this translation is actually in django itself: https://github.com/django/django/blob/1.9.7/django/contrib/sites/locale/de/LC_MESSAGES/django.po#L20-L21

This issue is about figuring out how to solve this situation. A few ideas:
- make a pull request to django to change the German translation of `sites` to `Sites`.
- add the above translation to django-cms and have it override (probably a bit flaky. AFAIK `cms` would have to be before `django.contrib.sites` in `INSTALLED_APPS` for our translation to take precedence over the one from django.)
- more ideas...?

Some other translation strings in django-cms will also need changing (https://www.transifex.com/divio/django-cms/translate/#de/core/22761150?q=sites).

**Comment by evildmp** [comment] 2016-07-26 11:00
@stefanfoulis why not *Webseite* for site?

**Comment by jezdez** [comment] 2016-07-26 11:27
@MarkusH and me discussed this in an unrelated issue on IRC today and agree that this should be fixed by translating "site" in Django to "Website" or "Webseite".

By the way the reason for using "Seite" has historically been caused by an overlap of meaning between "website" (a generic term for project the developers works on, or any other one on the internet) and "site" in Django's code (a data model from django.contrib.sites that is often referred to with foreign key relations and has a specific meaning bordering on configuration).

**Comment by jezdez** [comment] 2016-07-26 11:58
I've just went through all occurrences of "site" or "sites" in Django's German translation and changed it to "Website". This will be shipped with 1.10.

**Comment by czpython** [comment] 2018-03-15 13:27
The strings on the cms have changed to website.

**Closed by czpython** 2018-03-15 13:27 UTC
Labels: status: accepted
