### ISSUE TITLE
render_model_block frontend editing ignores a model instance if another plugin with the same id is present on the page

### ISSUE THREAD

**Issue by macolo** [divio/django-cms#6031] opened 2017-07-30 18:55 UTC
### Summary
I am using a `render_model_block` to enable frontend editing for a teaser app model. A TeaserBox plugin is inserted in a djangocms page and then specific teasers that have been created through Django Admin are attached to the TeaserBox. In the frontend, these teaser instances should then be editable through `render_model_block`.

TeaserBox CmsPlugin:
```
class TaggedTeaserPlugin(CMSPluginBase):
    module = _("Teaser System")
    model = models.TaggedTeaserBox
    name = _("Teaser Box")
    render_template = 'cat_teasers/plugins/teaser-container.html'

    admin_preview = True
    allow_children = False
    cache = False

    def render(self, context, instance, placeholder):
        teasers = models.TaggedTeaser.objects.all()

        # respect max teasers
        if instance.max_teasers:
            teasers = teasers[:instance.max_teasers]

        context['teasers'] = teasers
        context['teaserbox'] = instance
        return context

plugin_pool.register_plugin(TaggedTeaserPlugin)
```

### Expected behaviour

The model representations should open the frontend editing modal on double-clicking.

#### Actual behaviour

The model representations sometimes dont react in frontend editing mode. On double-clicking, the containing / parent plugin configuration modal (TeaserBox) opens instead.

This happens when the plugin id of another plugin on the page equals the id of the teaser instance. Once the other plugin is deleted from the page, frontend editing starts working for the teaser instance.

#### Environment

* Python version: 3
* Django version: 1.8.18
* django CMS version: 3.4.3

**Comment by czpython** [comment] 2017-07-31 13:39
Thanks for reporting.
Closing as duplicate of https://github.com/divio/django-cms/issues/5677

**Closed by czpython** 2017-07-31 13:39 UTC

**Comment by macolo** [comment] 2017-08-09 17:47
@czpython I fail to see how this is a duplicate of #5677 as I am not using custom views here at all. Maybe the underlying reasons are identical, but the use case described here is much more common. 

In any case I would suggest changing the title of #5677 to something more general that includes the problem described here.

**Comment by czpython** [comment] 2017-08-09 19:26
@macolo I've changed the title to reflect the underlying issue.
