### ISSUE TITLE
Copy Page with "Overwritel Url" leads to "MultipleObjectsReturned" error

### ISSUE THREAD

**Issue by SachaMPS** [divio/django-cms#6008] opened 2017-07-03 14:45 UTC
If a user copies a page with a Overwrite URL a "MultipleObjectsReturned" error is thrown...

Tested with: django-cms==3.4.2

Steps to reproduce: 
Open: https://control.aldryn.com/demo/get-new/
Edit the About page and give it a overwrite-url: "bugdemo"
Copy the page and paste it
Try to edit the pasted page, e.g. add something in structure mode

**Comment by czpython** [comment] 2017-07-03 15:11
Thanks for reporting.
Closing as duplicate of https://github.com/divio/django-cms/issues/5311

**Closed by czpython** 2017-07-03 15:11 UTC
