### ISSUE TITLE
Missing migration 0019?

### ISSUE THREAD

**Issue by AnderUstarroz** [divio/django-cms#6287] opened 2018-02-23 03:12 UTC
I am using **Django-cms==3.5.0** and when I run `python manage.py makemigrations`, the following migration is generated:

```
Migrations for 'cms':
  env/lib/python3.6/site-packages/cms/migrations/0019_auto_20180223_0307.py
    - Change managers on pageusergroup

```
I think you probably need to make a new release running **makemigrations** first, otherwise this  will provoke  continuous inconsistencies between different environments.

This is the content of the migration 0019_auto_20180223_0307:

```
# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 03:07
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pageusergroup',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]


```

**Comment by heppstux** [comment] 2018-02-23 08:53
Same issue here, makemigrations generates 0019...

**Comment by czpython** [comment] 2018-02-23 12:13
Closing as duplicate of https://github.com/divio/django-cms/issues/6266

**Closed by czpython** 2018-02-23 12:13 UTC
