### ISSUE TITLE
Plugin deleting not functional in support/3.1.x

### ISSUE THREAD

**Issue by furiousdave** [divio/django-cms#4376] opened 2015-08-24 23:54 UTC
In the current support/3.1.x branch, the plugin delete form appears to be broken when using the modal window. First encountered in a custom project and verified by creating a clean project with djangocms-installer using django-cms 3.1 and django 1.8. Then switched to the 3.1 support branch. 

Upon clicking "Yes, I'm sure" in the delete plugin form, the ajax spinner appears but no request is made in the network panel and no errors appear in the console.

When accessing the delete url directly, it work correctly.

**Comment by yakky** [comment] 2015-08-25 06:34
I cannot reproduce this, both on plain django-cms using ``develop.py server`` and on a clean installer project (both on Django 1.7 and 1.8 with all the rest set as default, and the installing latest support/3.1)

**Comment by furiousdave** [comment] 2015-08-25 14:20
Thanks yakky. I'll see if I can isolate the conditions here more.

**Comment by FinalAngel** [comment] 2015-09-21 06:27
@furiousdave which jQuery version are you using and is the console throwing any errors?

**Comment by furiousdave** [comment] 2015-10-06 17:37
Hi @FinalAngel. Sorry for the delayed response. I'm still able to reproduce this using 3.1.3 from a clean installer project, only the cms toolbar jquery being loaded (1.11.0). It may be specifically a Firefox issue as Chrome is working with the same project.

The exact setup is Firefox 41, Ubuntu 14.04.

Oddly, as I mentioned in the original post, no console errors or requests shown.

I may try testing the develop branch.

**Comment by FinalAngel** [comment] 2015-10-07 05:14
@furiousdave no problems, thanks taking time for debugging and providing back feedback! I'll add it to our testing list for the 3.2.0 release!

**Comment by yakky** [comment] 2015-10-09 06:57
@FinalAngel we need to check this in 3.1 too

**Comment by yakky** [comment] 2015-11-17 05:30
@FinalAngel any update on this?

**Comment by FinalAngel** [comment] 2015-11-17 08:01
It is a bit hard to reproduce @yakky, in fact I don't have such behaviour as our jQuery is isolated anyways. @furiousdave we did some minor changes on the loading for 3.2. Could you test latest djangocms-admin-style and django-cms develop branch?

**Comment by furiousdave** [comment] 2015-12-02 22:09
Tested CMS 3.2 and admin-style 1.0.6. Oddly, all is well using Firefox 42 in both Win and OS X but I still can't delete plugins via the modal when using Ubuntu 14.04. Now I'm wondering if a browser add-on could somehow be interfering with this request. Either way; at the most it's a fringe case. It's just very unusual because it's only the delete action that fails. If I ever actually diagnose this, I'll post.

**Comment by yakky** [comment] 2015-12-03 06:55
@furiousdave moving out of specific milestone, waiting for new information (possibly testing with a fresh clean firefox profile -you can create without losing your existing one- so no extension may interfere with the test?)

**Comment by bennierex** [comment] 2016-05-17 15:07
I'm still encountering this issue in FF45 with CMS 3.2.5. Tested on Chrome and no issues there whatsoever.
It's just showing the spinner and there are no errors in the console. Also, I see no POST going to the server when monitoring the network activitiy in FF dev tools. I'm assuming it's JS/jQuery related (using jQuery 1.11.3).

**Comment by furiousdave** [comment] 2016-05-17 16:19
@bennierex Oddly, I found that this was resolved when I disabled lastpass from my FF addons. Never narrowed in on why that would be an issue but might be worth checking your addons to see if one is conflicting.

**Comment by FinalAngel** [comment] 2016-05-18 06:03
@vxsx might you have an additional look at this?

**Comment by bennierex** [comment] 2016-05-18 07:54
@furiousdave Well, I just checked and this is indeed the problem. I have the 1Password add-on and disabling this "solves" the problem. Re-enabling it would cause deleting items to stop working again.
Funny thing is, I also use this add-on on Chrome (Windows) and Safari (OS X) and in both browsers it works without problems...

**Comment by vxsx** [comment] 2016-06-30 15:12
@bennierex @furiousdave would you mind checking if the problem is fixed for you on latest `release/3.3.x`? I can no longer reproduce.

**Comment by vxsx** [comment] 2016-07-08 15:06
Fixed by #5367

**Closed by vxsx** 2016-07-08 15:06 UTC
Labels: component: frontend, status: accepted, status: has patch
