### ISSUE TITLE
Content/Structure buttons not in the toolbar

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#3423] opened 2014-08-28 11:14 UTC
I've got a page on a site that was showing the content/structure toggle buttons in the toolbar the last time I looked at it. Now I'm looking at it, in edit mode, and they don't display so we can't get to edit the static placeholders. We have upgraded CMS since I developed the app hook on these pages so has something changed in CMS to effect whether or not the content/structure toggle button displays in the toolbar?

Using django 1.6.5 and cms 3.0.5

**Comment by mkoistinen** [comment] 2015-02-21 00:47
@marksweb Can you let us know if this is happening still in a reproducible way? And, can you check to see if this exists in 3.0.10? I'd like to get this fixed in 3.0.11, if it is still an issue.

In addition to the hints suggested above, it is possible that the apphook has multiple views (list view, detail view) and that you saw the buttons on one of these views, but not the other? If this is possible, perhaps the non-button-displaying view just has no placeholders? If this is the case, the buttons will not appear by design.

**Comment by marksweb** [comment] 2015-02-21 10:53
@mkoistinen I need to keep track of my open issues! I think this was my misunderstanding, because I expected the buttons to almost always appear but I think I happened to be on a template in an apphook that didn't have any placeholders so that's why they weren't appearing.

However on this note, I'm fairly sure the buttons are still 'inverted', because clicking 'content' gives you the structure view showing the placeholders, and the structure view shows the page content. I don't know if that's an issue in a template we've overridden & not pulled in fixes from cms because it doesn't happen on all of our CMS sites.

**Comment by rmuslimov** [comment] 2015-02-22 07:42
I met same issue after migration 2.4.3, standard pages with placeholder and I have never seen "Structure/Content" button.  So, we cant add new pages to site.

**Comment by yakky** [comment] 2015-02-22 18:45
@rmuslimov could you provide more information?
I can't replicate this
Have you followed the upgrade guide (http://django-cms.readthedocs.org/en/support-3.0.x/upgrade/3.0.html#upgrading-from-2-4)?

**Comment by rmuslimov** [comment] 2015-02-23 00:20
@yakky Ok, I think I found solution in  my case. I have base.html in project, and cmsbase.html which extends from base.html and works for CMS pages. 

cmsbase.html has:

```
{% block header_cms %}
  {% include "blocks/cms_bar.html" %}
{% endblock %}
```

where cms_bar.html is:

```
{% load cms_tags sekizai_tags %}
{% cms_toolbar %}
```

That was the way which I've chosen to step-side this:
>  Also, please check your templates to make sure that you haven’t put the {% cms_toolbar %} tag into a >  {% block %} tag. This is not allowed in 3.0 anymore.

So, now I put {% cms_toolbar %} to base.html and it works correct, but I don't know how to disable it for non-CMS pages. Thanks!

**Comment by yakky** [comment] 2015-03-01 07:29
@marksweb closing this as the "inverted behavior" it's a different one.
Please open a new issue if you can reproduce the "inverted behavior"

**Closed by yakky** 2015-03-01 07:29 UTC
Labels: needs more info

**Comment by dykyioleg** [comment] 2018-02-21 16:27
Hi! i have started my project with version 3.5.0 and i haven't in toolbar the buttons such i had in previous version.Such as 'structure' and 'content'. what i can do now ?
Thank you!

**Comment by vxsx** [comment] 2018-02-22 09:40
@dykyioleg those buttons are now one button that was moved to the rightmost position in the toolbar: 
![screen shot 2018-02-22 at 10 39 59](https://user-images.githubusercontent.com/366813/36530963-c641788a-17bc-11e8-9049-3560165a487b.png)

**Comment by dykyioleg** [comment] 2018-02-22 09:50
Thanks Vadik!

**Comment by artforlife** [comment] 2019-03-20 01:26
> @dykyioleg those buttons are now one button that was moved to the rightmost position in the toolbar:
> ![screen shot 2018-02-22 at 10 39 59](https://user-images.githubusercontent.com/366813/36530963-c641788a-17bc-11e8-9049-3560165a487b.png)

@vxsx , So, the Structure button has disappeared altogether? 

This is what I am seeing on my fresh local installation. Is this normal or is something missing?

![Screenshot from 2019-03-19 20-25-18](https://user-images.githubusercontent.com/8064423/54652549-40d02780-4a85-11e9-81b5-40dc02abc7db.png)

**Comment by vxsx** [comment] 2019-03-20 08:01
@artforlife the pressed one on the top right is the structure button. it acts as a toggle

**Comment by artforlife** [comment] 2019-03-20 15:00
> @artforlife the pressed one on the top right is the structure button. it acts as a toggle

That makes. I believe this version is more intuitive compared to when you had Structure-Content. I have been following the new documentation, which still seems to refer to the old paradigm. It alerted me to find out.
