### ISSUE TITLE
djangocms-installer generates wrong settings.py with Django 1.8

### ISSUE THREAD

**Issue by mrsarm** [divio/django-cms#4251] opened 2015-07-10 00:29 UTC
Te configuration is initialized with a ``TEMPLATE_CONTEXT_PROCESSORS`` removed in Django 1.8: ``django.middleware.doc.XViewMiddleware``. This cause this exception when you start the project with ``runserver`` an try to load the home page:

    Django version 1.8.3, using settings 'mrdev.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.
    Traceback (most recent call last):
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
        self.result = application(self.environ, self.start_response)
      File "/projects/mrsarm/py/cms-3.1/env/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
        return self.application(environ, start_response)
      File "/projects/mrsarm/py/cms-3.1/env/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
        self.load_middleware()
      File "/projects/mrsarm/py/cms-3.1/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 50, in load_middleware
        mw_class = import_string(middleware_path)
      File "/projects/mrsarm/py/cms-3.1/env/lib/python3.4/site-packages/django/utils/module_loading.py", line 26, in import_string
        module = import_module(module_path)
      File "/projects/mrsarm/py/cms-3.1/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
    ImportError: No module named 'django.middleware.doc'

According with [Django documentation](https://docs.djangoproject.com/en/1.8/internals/deprecation/#deprecation-removed-in-1-8), it should be use ``django.contrib.admindocs.middleware.XViewMiddleware`` instead. I tried it and solved the problem.

**Comment by mrsarm** [comment] 2015-07-10 00:46
I don't know if this is for the same reason, but after run the project, the web with the example template in Bootstrap looks fine, but after login with the admin user, the CMS toolbar doesn't show correctly, it's showed without styles, I attach an screenshot as example:

![Screenshot](https://docs.google.com/a/grayshirts.com.ar/uc?authuser=0&id=0B1v39YERCugsUDREU0htbG16b1U&export=download)

Looking for the error, I see imported the necessary CSS file correctly:

    {% render_block "css" %}

But when I see the HTML code generated, that block of code doesn't generate any HTML tag.

**Comment by mrsarm** [comment] 2015-07-10 00:52
This is my Python 3.4.0 environment (``pip freeze``):

    Django==1.8.3
    Django-Select2==4.3.1
    Pillow==2.8.0
    argparse==1.3.0
    dj-database-url==0.3.0
    django-classy-tags==0.6.2
    django-cms==3.1.2
    django-reversion==1.8.5
    django-sekizai==0.8.2
    django-treebeard==3.0
    djangocms-admin-style==0.2.7
    djangocms-column==1.5
    djangocms-file==0.1
    djangocms-flash==0.2.0
    djangocms-googlemap==0.2
    djangocms-inherit==0.1
    djangocms-installer==0.7.8
    djangocms-link==1.6.2
    djangocms-picture==0.1
    djangocms-style==1.5
    djangocms-teaser==0.1
    djangocms-text-ckeditor==2.5.2
    djangocms-video==0.1
    html5lib==0.999999
    ipython==3.2.0
    pytz==2015.4
    six==1.9.0
    tzlocal==1.2

**Comment by rfleschenberg** [comment] 2015-07-11 11:47
The missing toolbar CSS is caused by the fact that ``'sekizai.context_processors.sekizai'`` is not in ``CONTEXT_PROCESSORS``. Adding it fixes the issue for me.

**Comment by yakky** [comment] 2015-07-11 20:26
This is https://github.com/nephila/djangocms-installer issue, closing here, feel free to reopen the issue there

**Closed by yakky** 2015-07-11 20:26 UTC

**Comment by yakky** [comment] 2015-07-11 22:14
@mrsarm @rfleschenberg please check nephila/djangocms-installer#188
