### ISSUE TITLE
cms 3.5 - broken js enabled content after plugin save

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#6343] opened 2018-04-23 21:19 UTC
### Summary

after a plugin is saved, all js enabled content (owl carousel, or whatever custom js widget) on a page is broken/disfunctional.

### Expected behaviour

page works as before.

### Actual behaviour

js enabled content broken. as far as I can see, this happens because the placeholder's content is re-loaded with an XHR, but obviously, js components are not initialized any more.

### Possible workaround

a CMS.toolbar event, that we can listen to, to re-initialize the page javascript components. this may be already existing?

### Environment

* Python version: any
* Django version: any
* django CMS version: 3.5.x

**Comment by vxsx** [comment] 2018-04-24 05:04
Hi! There is an event available to fix those issues: http://docs.django-cms.org/en/latest/topics/frontend-integration.html

Duplicate of https://github.com/divio/django-cms/issues/6316

**Closed by vxsx** 2018-04-24 05:04 UTC

**Comment by benzkji** [comment] 2018-04-24 07:34
THX!

**Comment by benzkji** [comment] 2018-04-24 07:40
Are the javascript CMS. methods and events documented somewhere? I've looked through the docs, but the reference part only contains python APIs? 

I know it now, but documenting it better could avoid more duplicates (that get closed, as the problem is already solved, and then the next... ;-) just thinking loud..

**Comment by vxsx** [comment] 2018-04-24 07:46
There is a plan to document them, but at the moment other things are a priority.

We've also been modifying them pretty heavily lately, but we'll have to eventually give up that freedom at some point.

**Comment by benzkji** [comment] 2018-04-24 07:52
ok good luck ;-)! and thx again.
