### ISSUE TITLE
CMS Toolbar Not Working on Mobile

### ISSUE THREAD

**Issue by rhazelwood** [divio/django-cms#6070] opened 2017-09-14 21:28 UTC
### Summary

In the mobile and tablet views the 'More...' link in the Django CMS toolbar,

<img width="401" alt="screen shot 2017-09-14 at 5 21 12 pm" src="https://user-images.githubusercontent.com/8525283/30456338-2b73ada6-9971-11e7-9b91-1155b742400c.png">

,that opens up the tools for editing the page does not work, therefore pages cannot be edited, published, unpublished, etc on mobile

### Expected behaviour

Clicking the 'More...' link expands editing tools for page

### Actual behaviour

Clicking the 'More...' link has seemingly no effect, no tools are opened

### Environment

* Python version: 2.7.10
* Django version: 1.9.9
* django CMS version: 3.3.2

**Comment by vxsx** [comment] 2017-09-15 07:23
Hi, could you provide a reduced test case to reproduce and a bit more information on browser / OS ?
I've just tried at http://demo.django-cms.org and it seems to be working correctly.

**Comment by rhazelwood** [comment] 2017-09-26 17:03
Hiya,

I'm seeing this in Chrome 60.0.3112.113 // Macintosh OS X 10.10.5 personally, but have had a few others with different set ups test and be able to reproduce.

I have a paired down example on hand, but as it requires logging in to the CMS is it all possible to do a screenshare? Thanks

**Comment by vxsx** [comment] 2017-10-06 14:00
Could you try removing the css from your site and try to see if it's accessible like that? If it is, then the problem is there. 

Sadly screenshare won't be possible

**Comment by czpython** [comment] 2018-01-30 15:11
Closing.
Please reopen if this is still an issue on the latest cms version.

**Closed by czpython** 2018-01-30 15:11 UTC
Labels: needs more info
