### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL causes save to become stuck

### ISSUE THREAD

**Issue by peterfarrell** [divio/django-cms#3717] opened 2014-12-30 03:58 UTC
The following code causes Chrome to break when saving a plugin.  The plugin saves and the modal updates with "XXX was changed successfully. You may edit it again below."  The modal doesn't redirect and stalls with JS error `Uncaught SyntaxError: Unexpected token ILLEGAL`

https://github.com/divio/django-cms/blob/e2dfbf86b1a11173bff1dff6285d8d68e0631105/cms/templates/admin/cms/page/close_frame.html#L7-L12

````
<script>
window.CMS || window.parent.CMS || document.write(
	'<script src="/static/cms/js/libs/jquery.min.js" type="text/javascript"></script>' +
	'<script src="/static/cms/js/modules/cms.base.js" type="text/javascript"></script>'
);
</script>
```

The error looks like this in Chrome:

![image](https://cloud.githubusercontent.com/assets/2857188/5575557/c6bb2e70-8fa5-11e4-9d80-7c4a56f8b124.png)

**Comment by mkoistinen** [comment] 2015-02-13 21:17
I can't seem to reproduce this. Can anyone else? Also, I've inspected the code in the repo for funny symbols, etc., that might cause JS rendering issues, but, didn't find any.

**Comment by peterfarrell** [comment] 2015-02-13 21:50
It's certainly not because of funny symbols being committed but how certain browsers are handling the line of code I indicated.  I have over 10 confirmed computers in our company that demonstrate this behavior.  My guess it has to do with multiple script tags in a single `write`. 

If I roll back enough, I see it was introduced in this commit:

https://github.com/divio/django-cms/blob/06f89bf4180d30d94d0c55534f7e100eb0fb0292/cms/templates/admin/cms/page/close_frame.html

**Comment by peterfarrell** [comment] 2015-02-13 21:50
@mkoistinen - are you using Chrome on Linux? That is where we are seeing the major of the issues.

**Comment by peterfarrell** [comment] 2015-02-13 21:56
I knew I've seen this before. Here is the issue...

http://stackoverflow.com/a/20737569

> The problem is that the string passed to document.write includes the characters `</script>`, which ends up prematurely terminating the script element that document.write is called from.

> The characters `</script>` can't appear anywhere within a script, since the HTML parser has no way to distinguish this from an actual `</script>` tag.

Using `document.write` isn't probably the best solution in this case.

**Comment by mkoistinen** [comment] 2015-02-13 23:02
@peterfarrell Can you see if this fixes the issue?

https://github.com/mkoistinen/django-cms/tree/mkoistinen-feature/fix_3717

**Comment by peterfarrell** [comment] 2015-02-13 23:11
@mkoistinen just this the 3.0.x version just to double check?

**Comment by mkoistinen** [comment] 2015-02-13 23:15
Yes please. Clearly, if this works, it will be merged into both 3.0.10, and the develop branch.

**Comment by mkoistinen** [comment] 2015-02-14 14:43
This is now fixed for 3.0.x

**Closed by mkoistinen** 2015-02-14 14:43 UTC
Labels: component: frontend, status: accepted

**Comment by peterfarrell** [comment] 2015-02-14 14:44
I haven't had a chance to confirm. I will on Monday. Did you reproduce the
issue?

**Comment by mkoistinen** [comment] 2015-02-14 15:05
I was unable to reproduce the issue, but it is clear that this issue was introduced here: https://github.com/divio/django-cms/commit/182f17fb96b97c61fd82c16b5caa1c6e495ee10b

@jrief any comment?

**Comment by peterfarrell** [comment] 2015-02-16 21:12
@mkoistinen ... I have tried your fix and I have been unable to repro the issue any more. I believe it has fixed the issue. Thank you for merging.

Do you know when this will hit PIP?  Our company policy is to use only stable packages from PIP if possible.

**Comment by mkoistinen** [comment] 2015-02-16 22:03
django CMS 3.0.10 was released formally on Saturday, 14th of February, 2015. =) It included this fix.
