### ISSUE TITLE
Make project creation debugging more intutive

### ISSUE THREAD

**Issue by kjenney** [divio/django-cms#6333] opened 2018-04-13 09:40 UTC
### Summary

Creating a new project named cms fails with Traceback:

```
(.env) Kenneths-MacBook-Pro:mysite ken$ djangocms -f -p . cms
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the project
The installation has failed.


*****************************************************************

Check documentation at https://djangocms-installer.readthedocs.io

*****************************************************************

Traceback (most recent call last):
  File "/Users/ken/www.kenjenney.com/.env/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/Users/ken/www.kenjenney.com/.env/lib/python3.6/site-packages/djangocms_installer/main.py", line 37, in execute
    django.create_project(config_data)
  File "/Users/ken/www.kenjenney.com/.env/lib/python3.6/site-packages/djangocms_installer/django/__init__.py", line 61, in create_project
    output = subprocess.check_output(cmd_args, stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/ken/www.kenjenney.com/.env/bin/python3.6', '/Users/ken/www.kenjenney.com/.env/bin/django-admin.py', 'startproject', 'cms', '/Users/ken/www.kenjenney.com/mysite']' returned non-zero exit status 1.
```

### Expected behaviour

Creating a new project named cms fails with a simple error.

### Actual behaviour

Creating a new project named cms fails with Traceback.

### Environment

* Python version: 3.6.4
* Django version: 1.11.1
* django CMS version: 1.0.0

**Comment by czpython** [comment] 2018-04-13 11:24
Closed as duplicate of https://github.com/nephila/djangocms-installer/issues/298

**Closed by czpython** 2018-04-13 11:24 UTC
