### ISSUE TITLE
Cache hits too early - causes corruption with memcached and a WSGI server with app preloading

### ISSUE THREAD

**Issue by julianandrews** [divio/django-cms#5896] opened 2017-03-15 22:12 UTC
Django CMS hits the cache on app load, and it really shouldn't.

In particular, if using uwsgi in `preforking` mode (the default) and using memcached as the backend hitting the cache on app load leads to a socket being opened before forking. Once uwsgi forks, the workers will share the same memcached socket, which, under high traffic leads to garbled responses from memcached and cache corruption. This particular problem can be fixed by running uwsgi in `lazy-apps` mode (delaying the app load until after forking), but that comes at the cost of slower startup times and increased memory usage. I'm not very familiar with `gunicorn`, but I suspect that running it with the `--preload` option would lead to similar results.

More generally, this just isn't great from a design point of view. There's no good reason, for instance, to hit the cache when running migrations or other management commands - and Django quite intentionally avoids doing that. There must be some way to avoid hitting the cache until after app load!

**Comment by czpython** [comment] 2017-03-16 20:06
Hello, thanks for reporting.
Closing this as a duplicate of https://github.com/divio/django-cms/issues/5079.

**Closed by czpython** 2017-03-16 20:06 UTC
