### ISSUE TITLE
The node of the menu is not selected when user is logged and "is_staff" and not "is_superuser"

### ISSUE THREAD

**Issue by mzbyszewska** [divio/django-cms#6424] opened 2018-06-25 11:37 UTC
### Summary

In our application users can see some pages only as logged in users. Some of these users are just active, but some of them are staff users (with "is_staff" attribute True). If users are not staff, everything works fine but if user is staff and is logged in loses ability to see submenus. More details below.

### Expected behaviour
At frontend pages user should see expanded submenu of a clicked menu item. 
If the pages are not restricted it should not matter if the user is logged or not and if has permissions or not. 

### Actual behaviour
As expected when user is not logged in. As expected when user is not a staff user. As expected when user is superuser.

When:
1. user is logged in 
2. user "is_staff" 
3. user is not "is_superuser" 
the submenu of a clicked menu position does not expand. 

As I found, under these particular conditions, the position in the menu does not get True value for the attribute "is_selected". Further investigations lead to the conclusion that the set of pages which ids are compared with node id are draft pages. That is why method is_selected() of the  CMSNavigationNode in  cms_menu.py can't find selected menu position. 

I've decided to overwrite "is_selected()" method of CMSNavigationNode from cms.cms_menus with "is_selected()" method of NavigationNode from menus.base. Seems to work. 

### Environment

* Python version: 2.7
* Django version: 1.9 and 1.10
* django CMS version: 3.5.2

**Comment by czpython** [comment] 2018-07-07 17:53
Duplicate of https://github.com/divio/django-cms/issues/6336
Fixed by https://github.com/divio/django-cms/pull/6354

**Closed by czpython** 2018-07-07 17:53 UTC
