### ISSUE TITLE
Template tag show_admin_menu_for_pages output is sometimes escaped.

### ISSUE THREAD

**Issue by rednasem** [divio/django-cms#5705] opened 2016-09-26 15:17 UTC
The cms admin template tag `show_admin_menu_for_pages` output is raw html. However the string returned by `cms.utils.render_admin_rows` is not marked safe. So the output is escaped by the `django.utils.html.conditional_escape` called internally by `register.simple_tag`. 

Eclosing the return value of `cms.utils.render_admin_row` with `django.utils.html.mark_safe` fixed the problem.

**Comment by vxsx** [comment] 2016-09-26 15:23
Thanks for the report, this is a duplicate of https://github.com/divio/django-cms/issues/5694

**Closed by vxsx** 2016-09-26 15:23 UTC
