### ISSUE TITLE
TypeError: sequence index must be integer, not 'slice'

### ISSUE THREAD

**Issue by v582ijay** [divio/django-cms#6668] opened 2019-04-11 18:00 UTC
I am having this issue when trying to run migrate.  I changed the database to PostgreSQL Below is the traceback

 Applying cms.0019_set_pagenode...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\..\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\..\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\..\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\..\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\..\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "C:\Users\..\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\..\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\..\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\..\lib\site-packages\cms\migrations\0019_set_pagenode.py", line 68, in apply
    connection.introspection.get_table_description(connection.cursor(), 'cms_page')
  File "C:\Users\..\lib\site-packages\django\db\backends\postgresql\introspection.py", line 87, in get_table_description
    )) for line in cursor.description
  File "C:\Users\..\lib\site-packages\django\db\backends\postgresql\introspection.py", line 87, in <listcomp>
    )) for line in cursor.description
TypeError: sequence index must be integer, not 'slice'

**Comment by czpython** [comment] 2019-04-11 18:04
Closing as duplicate of https://github.com/divio/django-cms/issues/6666

**Closed by czpython** 2019-04-11 18:04 UTC
