### ISSUE TITLE
Errors in initial migrations on postgresql

### ISSUE THREAD

**Issue by MARUTHESH** [divio/django-cms#6672] opened 2019-04-19 08:48 UTC
### Summary
Django-CMS with SqliteDB has no issues. When performing migrations on postgresql it showing TypeError: sequence index must be integer, not 'slice'.

### Expected behaviour
All the initial migrations applied properly.

### Actual behaviour
`django-cms`: When i tried to perform `python manage.py migrate` in postgresql, it is returning a `TypeError` but it is not giving any error in `sqlite`.

This is my full traceback:

    File "manage.py", line 22, in <module>
        execute_from_command_line(sys.argv)
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
        utility.execute()
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
        output = self.handle(*args, **options)
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
        fake_initial=fake_initial,
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
        state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
        state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
        state = migration.apply(state, schema_editor)
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/cms/migrations/0019_set_pagenode.py", line 68, in apply
        connection.introspection.get_table_description(connection.cursor(), 'cms_page')
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 87, in get_table_description
        )) for line in cursor.description
      File "/home/vagrant/.virtualenvs/pmvp/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 87, in <listcomp>
        )) for line in cursor.description
    TypeError: sequence index must be integer, not 'slice'

Can anyone help me out?

### Environment

* Python version:3.6.7
* Django version:1.11.20
* django CMS version:3.6.0

**Comment by yakky** [comment] 2019-04-19 10:12
Thanks @MARUTHESH this is a duplicate of  #6666 . See there for a workaround

**Closed by yakky** 2019-04-19 10:12 UTC
