### ISSUE TITLE
cms.permission.post_save_user fails on installing test fixtures when using Django's test Client

### ISSUE THREAD

**Issue by miraculixx** [divio/django-cms#3532] opened 2014-10-24 11:23 UTC
The problem is manifest in unit tests where there are multiple tests that repeatedly login/logout using Django's test Client() and which use fixtures referencing auth_user. The first test that runs will install the fixtures fine. Any subsequent tests will fail creating new auth_user objects:
```
File "/home/patrick/projects/shrebo-ext/env/local/lib/python2.7/site-packages/cms/signals/permissions.py", line 31, in post_save_user page_user.save()
...
IntegrityError: (1452, 'Cannot add or update a child row: a 
foreign key constraint fails (`test_shrebo`.`cms_pageuser`, 
CONSTRAINT `created_by_id_refs_id_9da6953b` FOREIGN KEY 
(`created_by_id`) REFERENCES `auth_user` (`id`))')
```
The problem appears in `cms.signals.permissions.post_save_user` while processing the post_save signal of `User.objects.create`, but the origin of the error is due to `CurrentUserMiddleware` not resetting the user object in thread local on `client.logout()`. This causes subsequent test runs (i.e. fixture installations) to set a created_by user object that no longer exists.

I will post a gist with a quick fix as I don't currently have the time for a PR.

**Comment by marksweb** [comment] 2015-01-02 10:11
Back to work again after Christmas & I've tested the receiver with the server running as normal, when logging out it is hit but I do still hit the error under test mode.

**Comment by mkoistinen** [comment] 2015-04-04 13:01
What's the status on this. It looks like its getting stale =(. @marksweb any chance you could supply a repeatable set of steps or, better yet, a simple project with said behaviour? I'd like to get this into 3.0.13 if we can get this quickly.

**Comment by marksweb** [comment] 2015-04-07 07:53
@mkoistinen Unfortunately I've not tried to run tests on any CMS projects since this issue arose.

The next time I encounter something like this I'll try to replicate in an empty project so that it can be investigated.

**Comment by sthzg** [comment] 2015-07-13 14:59
I am running into this on a `3.0.3` installation. Putting the `@receiver` from the gist on top of my test file didn't help (maybe the logout signal does not work as expected in test cases?), but I assume that I hit the same error because putting the following hack into a cleanup function called at the end of every test "fixes" the problem.

```
def cleanup():
    # ...
    try:
        from cms.utils.permissions import set_current_user
        set_current_user(None)
    except ImportError:
        pass
    # ...
```
In the coming days I will try to update the setup to the latest stable release and test it without the workaround. If the error still exists after the update I can try to provide something that reproduces the error.

**Comment by yakky** [comment] 2015-07-13 20:45
Thanks @sthzg for your efforts

**Comment by lddubeau** [comment] 2015-07-14 12:22
The problem definitely exists when using Django 1.7 and Django CMS 3.1.0. I added the `set_current_user(None)` call after test completion by using `cms.test_utils.testcases.BaseCMSTestCase` to mix it in with the problematic test cases. (Using `cms.test_utils.testcases.CMSTestCase` or `cms.test_utils.testcases.TransactionCMSTestCase` was not an option in my case.)

I've assumed that using `cms.test_utils.testcases.BaseCMSTestCase` (by referring to it directly or by using  `CMSTestCase` or `TransactionCMSTestCase`), or at least replicating enough of its setting up/tearing down procedures was the "price of admission", so to speak, to testing code that issues requests with Django CMS installed. It was an acceptable thing to do in my case, as the failing tests were for apps that are tied to a specific project, which requires Django CMS. I can imagine cases where this would not be a desirable or even a workable solution.

I don't see listening to logouts being a general solution. I have a test suite with 305 tests here. Only one of them formally issues a logout. The rest is quite capable of testing access from different classes of users without having to formally log out. A number of them would fail if `set_current_user(None)` was not issued somehow after a test.

**Comment by miraculixx** [comment] 2015-07-17 00:42
> A number of them would fail if set_current_user(None) was not issued somehow after a test.

that's the root cause - Django CMS caches a user object that doesn't exist after tearDown (and the db reset this entails). 

the solution is either of:

1. call `set_current_user(None)` before fixtures are loaded next time (in my case, using the logout signal handler worked because my tests did a logout in tearDown).
2. Catch the exception in File "/home/patrick/projects/shrebo-ext/env/local/lib/python2.7/site-packages/cms/signals/permissions.py", line 31, in post_save_user page_user.save(), call `set_current_user(None)` and try again.

**Comment by czpython** [comment] 2016-06-13 18:13
I've opened a public discussion on the developer's list in order to come up with a solution that addresses the underlying problem (using current thread to store user).

https://groups.google.com/forum/#!topic/django-cms-developers/T9OtsDl8qcQ

**Comment by czpython** [comment] 2016-06-14 15:09
Closing in favor of https://github.com/divio/django-cms/issues/5411.

**Closed by czpython** 2016-06-14 15:09 UTC
Labels: component: permissions, status: accepted
