### ISSUE TITLE
unit testing an app using both placeholder admin and apphook is difficult

### ISSUE THREAD

**Issue by jbazik** [divio/django-cms#4081] opened 2015-04-29 22:58 UTC
I'm developing an app that uses both PlaceholderAdminMixin and an apphook.  When I run my unit tests, I run into the issue from #3460 - django-cms attempts to query the database before it is created:

 OperationalError: no such table: django_site

I have a trivial app that demonstrates the problem:

https://github.com/jbazik/django-cmstest

Versions: cms 3.0.13, django 1.7.

**Comment by jbazik** [comment] 2015-04-30 16:11
Here's a traceback:

ImportError: Failed to import test module: cmstest.testurls
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/gpfs/main/home/jsb/projects/django/django-cmstest/cmstest/testurls.py", line 6, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 262, in urls
    return self.get_urls(), self.app_name, self.name
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 246, in get_urls
    url(r'^%s/%s/' % (model._meta.app_label, model._meta.model_name), include(model_admin.urls))
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 598, in urls
    return self.get_urls()
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/cms/admin/placeholderadmin.py", line 131, in get_urls
    from cms.urls import SLUG_REGEXP
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/cms/urls.py", line 20, in <module>
    urlpatterns = get_app_patterns()
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/cms/appresolver.py", line 191, in get_app_patterns
    current_site = Site.objects.get_current()
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 54, in get_current
    current_site = self.get(pk=sid)
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/tmp/tmp.Zk9yDkS2Mb/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_site

Soooo, testing the admin when an apphook (with urls) has been declared causes cms to query for the current site before TestCase has had a chance to set up the database.  Hopefully you agree that using an apphook and a placeholder and testing are all things I should be able to do.

**Comment by yakky** [comment] 2015-05-01 08:45
Duplicate of #3675

**Comment by FinalAngel** [comment] 2015-10-29 14:02
closing as it is linked to #3657

**Closed by FinalAngel** 2015-10-29 14:02 UTC
Labels: kind: bug, status: accepted
