### ISSUE TITLE
Conflicting static_placeholder records might be created, when not using sites framework

### ISSUE THREAD

**Issue by mikek** [divio/django-cms#3921] opened 2015-03-03 21:24 UTC
`unique_together = (('code', 'site'),)` that can be found in `StaticPlaceholder` model does not work as we might intuitively expect, at least on [Postgresql](http://www.postgresql.org/docs/9.4/static/indexes-unique.html):
*When an index is declared unique, multiple table rows with equal indexed values are not allowed.
Null values are not considered equal. A multicolumn unique index will only reject cases where all indexed columns are equal in multiple rows.*

So if we have `{% static_placeholder 'foo' %}` in template, it is still possible to create another one in the database with the same `code` and empty `site_id`. And it was actually happening to me for a newly created template: rendering such a page failed with 'multiple objects returned'. Not sure how to reproduce it or if using some site id will automatically solve such issues...

**Comment by mikek** [comment] 2015-03-04 12:40
Third column is `code`, so you can notice we have duplicate 'feed one' codes.
```
for obj in StaticPlaceholder.objects.all().values_list(): print obj
(1, u'footer', u'footer', 6, 7, False, u'template', None)
(5, u'sidebar_blog', u'sidebar_blog', 78, 79, False, u'template', None)
(7, u'sidebar_faq', u'sidebar_faq', 155, 156, False, u'template', None)
(6, u'sidebar_events', u'sidebar_events', 115, 116, False, u'template', None)
(8, u'quick links', u'quick links', 869, 870, False, u'template', None)
(9, u'feed one', u'feed one', 871, 872, False, u'template', None)
(10, u'feed two', u'feed two', 873, 874, False, u'template', None)
(11, u'feed three', u'feed three', 875, 876, False, u'template', None)
(12, u'feed one', u'feed one', 877, 878, False, u'template', None)
```

**Comment by mkoistinen** [comment] 2015-03-05 19:21
The installation docs for CMS states that the Sites framework is required and that SITE_ID must be set (https://django-cms.readthedocs.org/en/support-3.0.x/how_to/integrate.html).

This seems like it'd be easy to prevent, but running without SITE_ID set is bound to expose other issues.

So, I'm not sure if this should be "won't fix" or "easy pickins".

Comments: @yakky, @ojii?

**Comment by ojii** [comment] 2015-03-05 20:54
maybe it should raise an exception with unset ``SITE_ID``? At the very least should be in ``cms check``

**Comment by mkoistinen** [comment] 2015-03-05 20:57
OK, looks like I misunderstood this issue. The issue is that its unclear what to put in the optional "site_id" parameter of the templatetag. Changed to documentation issue.

**Comment by mikek** [comment] 2015-03-05 21:09
I should have given a bit more details: SITE_ID is set in the settings. I just do not use second (optional) argument called 'site' in the static_placeholder tag.
https://github.com/divio/django-cms/blob/8a09f92/cms/templatetags/cms_tags.py#L1112
As sites framework is required fro the CMS to function properly and having this Postgres issue... Is it possible to deprecate the extra argument and always set site ID in the database?

**Comment by ojii** [comment] 2015-03-05 21:14
I wouldn't deprecate it as it is there to explicitly pull a placeholder from another site. but it should probably default to ``settings.SITE_ID``.

**Comment by czpython** [comment] 2015-03-05 21:15
just about to say that.. so I agree with @ojii. it is useful to be able to pick where the placeholder comes from.

**Comment by mkoistinen** [comment] 2015-03-05 21:37
+1

**Comment by mikek** [comment] 2015-03-05 21:52
Looks like we can not pass explicit site id, but just indicate wether we want to link placeholder to the *current* site by suppling extra argument called 'site' (this is not a variable with actual site id).

**Comment by evildmp** [comment] 2015-03-06 11:12
That is correct - you can't pass anything in ``site``; ``site`` is simply a flag that tells the static placeholder that it belongs only to the current site, not all sites.

**Comment by mkoistinen** [comment] 2015-04-04 12:56
Thanks for the documentation update, @evildmp, committed.

From what I can tell, it appears that what now needs to happen to prevent this is, when there is a new static_placeholder discovered, without the 'site' flag, we need a code-side check to make sure that there is not already an existing static placeholder with the same name and whose site_id column is set to NULL. Relying on the database to enforce this condition won't work because in *most* RDBMS backends, NULLs won't ever be considered equal.

**Comment by mkoistinen** [comment] 2015-04-13 15:53
@mike The relevant code is here: https://github.com/divio/django-cms/blob/develop/cms/templatetags/cms_tags.py#L1120-L1126

I think the scenario could be something like this:

1. create a static_placeholder on site 1 constrained to the site with {% static_placeholder "sample" site %}. This should create an entry like StaticPlaceholder.objects.create(code="sample", site_id=1, ... )
2. create a second static_placeholder on site one, but do not constrain to the site using {% static_placeholder "sample" %} this would also create a new entry with something like StaticPlaceholder.objects.create(code="sample", site_id=None, ...)

Note that this is legitimate. If you choose to do so, you could use {% static_placeholder "sample" %} on site 2 and you should get the shared one. If you use {% static_placeholder "sample" %} on site 1, you will again get the "shared" one. If you use {% static_placeholder "sample" site %} on site 1, you should get the site-constrained one. Finally, if you use {% static_placeholder "sample" site %} on site 2, you should be creating a new, site-constrained placeholder with the same name "sample" for site 2.

While I'll agree this may be somewhat unintuitive, I think it is working correctly and usefully. I'm closing this with the aforementioned documentation updates.

**Closed by mkoistinen** 2015-04-13 15:53 UTC
Labels: needs patch
