### ISSUE TITLE
jstree behavior broken: TypeError: CMS.TreeManager is not a constructor

### ISSUE THREAD

**Issue by tlrh314** [divio/django-cms#3929] opened 2015-03-05 10:39 UTC
Using Django 1.7.5 and django-cms 3.0.12 the django-admin page list jstree table appears to not work. The drag and drop functionality does not work, subpages are not listed, expand/collapse does not work.

The following two errors are thrown:
SyntaxError: missing ) after formal parameters cms.changelist.js:17
TypeError: CMS.TreeManager is not a constructor page:56

**Comment by yakky** [comment] 2015-03-05 10:55
This is an error in 3.0.11. It has been fixed in 3.0.12.
Cannot reproduce in 3.0.12

**Closed by yakky** 2015-03-05 10:55 UTC

**Comment by evildmp** [comment] 2015-03-05 13:25
@tlrh314 Timo, can you confirm you really meant django-cms 3.0.12 and not django-cms 3.0.11? Thanks.
