### ISSUE TITLE
Users lose edit permission after visiting pages where they don't have it and getting back to previous page

### ISSUE THREAD

**Issue by EnaVl** [divio/django-cms#6371] opened 2018-05-15 13:42 UTC
### Summary
User who is not superuser but is staff and has the access to making edits on some specific set of pages gets permission error after visiting the page where he doesn't have permissions and getting back. As I understand it can be related to #6335 issue. 

### Expected behaviour
When user (is_staff) logged in he can see 'Edit' button in toolbar and make some edits on the page. When he visits another page where he has no permissions to edit, he doesn't see the 'Edit' button anymore. After he gets back to previous page (where he has permissions) he expects to see 'Edit' button and continues to work.

### Actual behaviour
After user gets back to previous page (where he has permissions to edit), he still doesn't see 'Edit' button. If he adds '?edit' to url, the "You do not have permission to edit this plugin" title is displayed in popup.

### Environment

* Python version: 2.7
* Django version: 1.9.5
* django CMS version: 3.5.1

**Comment by czpython** [comment] 2018-05-15 14:00
Thanks for reporting!
Closing as duplicate of https://github.com/divio/django-cms/issues/6335

**Closed by czpython** 2018-05-15 14:00 UTC
