### ISSUE TITLE
Problem with consistency of Page.publisher_public_id

### ISSUE THREAD

**Issue by vstoykov** [divio/django-cms#5667] opened 2016-09-07 13:32 UTC
We have a problem that at some time some of the draft pages has missing value `publisher_public_id` (but there is a public version of the page which points back to the draft). 

At this situation when you try to visit the public version of the page  error 500 occurs. Traceback is:

        Traceback (most recent call last):
    File "/path/to/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "/path/to/venv/lib/python3.4/site-packages/cms/views.py", line 181, in details
        response = render_page(request, page, current_language=current_language, slug=slug)
    File "/path/to/venv/lib/python3.4/site-packages/cms/page_rendering.py", line 24, in render_page
        context['has_view_permissions'] = page.has_view_permission(request)
    File "/path/to/venv/lib/python3.4/site-packages/cms/models/pagemodel.py", line 1186, in has_view_permission
        is_restricted = bool(get_any_page_view_permissions(request, self))
    File "/path/to/venv/lib/python3.4/site-packages/cms/utils/permissions.py", line 399, in get_any_page_view_permissions
        page = page.publisher_draft
    File "/path/to/venv/lib/python3.4/site-packages/django/db/models/fields/related.py", line 480, in __get__
        self.related.get_accessor_name()
    django.db.models.fields.related.RelatedObjectDoesNotExist: Page has no publisher_draft.

When I try to execute `python manage.py cms fix-tree` I end up with the following error:

    Traceback (most recent call last):
    File "/path/to/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    psycopg2.IntegrityError: duplicate key value violates unique constraint "cms_page_path_72b7799ffb81eabf_uniq"
    DETAIL:  Key (path)=(00030001) already exists.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
    File "/path/to/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
        utility.execute()
    File "/path/to/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/path/to/venv/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
        self.execute(*args, **cmd_options)
    File "/path/to/venv/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
        output = self.handle(*args, **options)
    File "/path/to/venv/lib/python3.4/site-packages/cms/management/commands/subcommands/base.py", line 84, in handle
        command.handle(*args, **options)
    File "/path/to/venv/lib/python3.4/site-packages/cms/management/commands/subcommands/tree.py", line 32, in handle
        page.move(target=last, pos='right')
    File "/path/to/venv/lib/python3.4/site-packages/cms/models/pagemodel.py", line 1420, in move
        super(Page, self).move(target, pos)
    File "/path/to/venv/lib/python3.4/site-packages/treebeard/mp_tree.py", line 1037, in move
        return MP_MoveHandler(self, target, pos).process()
    File "/path/to/venv/lib/python3.4/site-packages/treebeard/mp_tree.py", line 481, in process
        self.run_sql_stmts()
    File "/path/to/venv/lib/python3.4/site-packages/treebeard/mp_tree.py", line 119, in run_sql_stmts
        cursor.execute(sql, vals)
    File "/path/to/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    File "/path/to/venv/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
    File "/path/to/venv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
        raise value.with_traceback(tb)
    File "/path/to/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.IntegrityError: duplicate key value violates unique constraint "cms_page_path_72b7799ffb81eabf_uniq"
    DETAIL:  Key (path)=(00030001) already exists.

I know that this denormalization of the data in the database is for speed but consistency and error fixing need to be ensured for proper work.

**Comment by czpython** [comment] 2016-09-07 13:42
Hello @vstoykov,
This is a known error. I believe it comes from using revisions to recover/undo/redo a page.
There's other cases where it was happening but these are now fixed on 3.3.x

Can you try running https://gist.github.com/czpython/5c029928a73cd0243bad313cd97bafa8 locally? It's a command that finds this type of corruption and fixes it.

Afterwards run `cms fix-tree`

**Comment by vstoykov** [comment] 2016-09-07 13:44
As a workaround I'm able to fix this with executing this code:

    for broken_page in Page.objects.filter(publisher_public=None, publisher_draft__isnull=False):
        Page.objects.filter(pk=broken_page.pk).update(publisher_public=broken_page.publisher_draft)

Probably something like that need to be placed in `fix-tree` subcommand (probably also for `Title` and all registered page and title extensions).

**Comment by czpython** [comment] 2016-09-07 13:49
@vstoykov Do you mind creating a topic for this in the developers list?

**Comment by czpython** [comment] 2016-09-07 13:52
@vstoykov Also regarding your workaround, make sure to target the titles as well for those pages, if the page has the corruption then very likely the title will too.

**Comment by vstoykov** [comment] 2016-09-07 13:53
Now as I look close to your script It does basically the same as my workaround but says which where the  broken pages and if they were draft or public and also fixes the titles.

And both functions `_process_draft` and `_process_public` are basically the same except the message printed to stdout

**Comment by czpython** [comment] 2016-09-07 13:55
Yes I thought about unifying them but for my own sanity I left them separate 😞

**Comment by vstoykov** [comment] 2016-09-07 14:10
Ok my final workaround is:

    from cms.models import Page, Title
    from cms.extensions import extension_pool
    from django.core.cache import cache


    for broken_page in Page.objects.filter(publisher_public=None, publisher_draft__isnull=False):
        Page.objects.filter(pk=broken_page.pk).update(publisher_public=broken_page.publisher_draft)


    for broken_title in Title.objects.filter(publisher_public=None, publisher_draft__isnull=False):
        Title.objects.filter(pk=broken_title.pk).update(publisher_public=broken_title.publisher_draft)


    for page_extension in extension_pool.page_extensions:
        for broken_page_extension in page_extension.objects.filter(public_extension=None, draft_extension__isnull=False):
            page_extension.objects.filter(pk=broken_extension.pk).update(public_extension=broken_extension.draft_extension)

    for title_extension in extension_pool.title_extensions:
        for broken_title_extension in title_extension.objects.filter(public_extension=None, draft_extension__isnull=False):
            title_extension.objects.filter(pk=broken_extension.pk).update(public_extension=broken_extension.draft_extension)


    cache.clear()



About creating a topic in developers list you mean this https://groups.google.com/forum/#!forum/django-cms, right?

**Comment by czpython** [comment] 2016-09-07 14:13
@vstoykov https://groups.google.com/forum/#!forum/django-cms-developers

**Comment by czpython** [comment] 2016-09-08 00:55
Closing as a duplicate of https://github.com/divio/django-cms/issues/4940

**Closed by czpython** 2016-09-08 00:55 UTC
