### ISSUE TITLE
"Successful install" landing page workflow broken

### ISSUE THREAD

**Issue by derek-adair** [divio/django-cms#5869] opened 2017-02-03 16:56 UTC
### Summary
The initial popup window that comes up after a fresh install doesn't seem to be working.  This is presumably the same window triggered by the anchor with the innerText of "Add the first page", because the app ends up in the same state.
![image](https://cloud.githubusercontent.com/assets/847236/22600134/cf57c8bc-e9fe-11e6-8755-a72548b2278b.png)

### Expected behaviour
I should be able to create a page from this initial popup.

#### Actual behaviour
I am unable to continue the flow until I click the create button.

#### Environment

* Python version: 3.4
* Django version: 1.9
* django CMS version:  3.4.1

**Comment by derek-adair** [comment] 2017-02-03 16:59
I'm assuming the link on [the initial landing page](http://imgur.com/a/PwU0I) is not providing the right configuration values for the module? i'm pretty new or i'd just submit a PR fixing this, but i'm not really sure where to even look.

**Comment by czpython** [comment] 2017-02-03 18:54
Thanks!
Closing as duplicate of https://github.com/divio/django-cms/issues/5828

**Closed by czpython** 2017-02-03 18:54 UTC
