### ISSUE TITLE
caching ignores session based language choice

### ISSUE THREAD

**Issue by iceripple** [divio/django-cms#5776] opened 2016-11-24 15:53 UTC
cms.cache.page._page_cache_key() does not consider request.LANGUAGE_CODE.
Once the page has been cached, selecting another language will have no effect if the selected language is not in the url scheme.

django-cms 3.3.3:
```python
def _page_cache_key(request):
    #md5 key of current path
    cache_key = "%s:%d:%s" % (
        get_cms_setting("CACHE_PREFIX"),
        settings.SITE_ID,
        hashlib.md5(iri_to_uri(request.get_full_path()).encode('utf-8')).hexdigest()
    )
    if settings.USE_TZ:
        cache_key += '.%s' % get_timezone_name()
    return cache_key
```
Would be nice if request.LANGUAGE_CODE could be added to the cache_key

**Comment by czpython** [comment] 2016-11-24 16:01
Hello @iceripple,
The caching uses `request.get_full_path()` which includes the language code.
Its strange that you would see the same content for all languages..

Can you provide some screenshots?

**Comment by iceripple** [comment] 2016-11-24 18:23
Hi Paulo,

you’re welcome try for yourself on https://www.kiesopmaat.nl

The homepage and all pages under the ‘Voor instellingen’ menu item are cms pages.

the language select menu sets the language through an ajax call to /i18n/setlang/ (django.conf.urls.i18n) and reloads the page when the server returns a response. The url does not change with the selected language. Only request.LANGUAGE_CODE  is set through django.locale.LocaleMiddleware.

To my -admittedly limited- understanding of the method, i would not expect the result of request.get_full_path() to be any different when another language is selected this way.

**Comment by czpython** [comment] 2016-11-24 21:00
Thanks for clarifying @iceripple.
I'm closing this as a duplicate of https://github.com/divio/django-cms/issues/4050.
Its a problem where the cms does not respect the session set language.

**Closed by czpython** 2016-11-24 21:00 UTC
