### ISSUE TITLE
Editing advanced settings through change view raises AttributeError

### ISSUE THREAD

**Issue by plamen-nikolov** [divio/django-cms#6109] opened 2017-10-28 20:51 UTC
I'm bumping it up as it's been around for more than 3 months. It's now relevant to the latest DjangoCMS as its officially supports Django 1.11. 

https://github.com/divio/django-cms/issues/6035

**Comment by czpython** [comment] 2017-10-28 21:09
Thanks for the follow-up.
Closing as duplicate of #6035.

**Closed by czpython** 2017-10-28 21:09 UTC
