### ISSUE TITLE
Edit mode modals are displayed incorrect

### ISSUE THREAD

**Issue by teutobod** [divio/django-cms#4039] opened 2015-04-16 20:53 UTC
Hi,

I just did a fresh installation of django cms following the "How-To-Guides". Playing around with the edit mode, I noticed that some modal windows behave very strange. 
Examples:
* The "advanced settings" modal gets minimized immediatly after it pops up.
* If I click on "page settings" the modal opens also in minimized mode. Clicking on the "maximize" button (small square in the right top corner) doesn't have any effect on the modal. 

I'm using Firefox 37.0.1.

Django==1.7.7
django-classy-tags==0.6.1
django-cms==3.0.12
django-mptt==0.6.1
django-sekizai==0.8.1
djangocms-admin-style==0.2.5
html5lib==0.999
six==1.9.0
South==1.0.2
virtualenv==12.0.7

Regards
Lars

**Comment by teutobod** [comment] 2015-04-17 15:55
[Here](http://de.tinypic.com/r/23s93du/8) is a short screencast that demonstrates the issue.

**Comment by mkoistinen** [comment] 2015-05-11 20:53
I suspect you have old local storage or cookies? Could you try to clear all browser cookies and local storage and see if this issue persists? If so, can you also clear/bypass your cache to make sure you're loading the correct JS/CSS?

**Comment by adrienbrunet** [comment] 2015-09-02 10:17
I don't know if it's related but sometimes my modals are also a bit weird (like described in  #1215). I'm using Firefox though and django-cms 3. The modals are full width and have a really low height. The handler to resize the modal does not work everytime and the maximize button does nothing most of the time. The behavior is quite non consistant. Have I messed up the config? Any advise?

**Comment by koobs** [comment] 2015-10-10 05:05
@adrienbrunet Does the height of the resulting modal increase as you add more test plugins to a page?

**Comment by adrienbrunet** [comment] 2015-10-19 12:59
Somehow, I'm not able to reproduce my bug. (I haven't changed anything though). If it occurs again, I let you know asap.

**Comment by FinalAngel** [comment] 2015-10-19 13:09
@adrienbrunet we also made significant improvements in django-cms 3-2 to the modal :)

**Comment by adrienbrunet** [comment] 2015-10-19 13:21
:+1:

**Comment by koobs** [comment] 2015-10-19 14:02
FWIW, I'm experiencing the same symptoms in the latest RC. Chrome again is fine.

**Comment by FinalAngel** [comment] 2015-10-19 14:05
@koobs 

related to:

* The "advanced settings" modal gets minimized immediatly after it pops up.
* If I click on "page settings" the modal opens also in minimized mode. Clicking on the "maximize" button (small square in the right top corner) doesn't have any effect on the modal.

??

**Comment by koobs** [comment] 2015-10-19 14:07
@FinalAngel  Advanced settings modal gets minimized (to the height of the number of elements in the page structure) immediately after it pops up. See my https://github.com/divio/django-cms/issues/4039#issuecomment-147038825

**Comment by FinalAngel** [comment] 2015-10-19 14:23
@koobs I cant reproduce this issue: http://screencast.com/t/nbvjofIp2

Can you try to do the following in your browsers console: ``localStorage.clear();`` and see if the issue persists?

**Comment by vxsx** [comment] 2015-11-23 11:06
@koobs cannot reproduce with latest develop. can you still reproduce the issue? is there anything special about the project itself?

**Comment by koobs** [comment] 2015-11-23 11:46
@vxsx Could you reproduce with previous versions? Re: the project; I believe I tested with the verbatim templates available in the documentation: http://docs.django-cms.org/en/latest/how_to/install.html#configuring-your-project-for-django-cms

Specifically template1/template2

**Comment by koobs** [comment] 2015-11-23 11:48
@FinalAngel localStorage was not the issue (@mkoistinen had already asked me to clear that setting while helping me debug on IRC, prior to reporting the issue here)

**Comment by vxsx** [comment] 2015-11-23 12:26
@koobs cannot reproduce with 3.1 or 3.0

**Comment by teutobod** [comment] 2015-11-23 17:19
@all: After a fresh installation of python and django on my machine the issue didn't occur any more. I guess the problem caused by some incompatible versions in the required packages.

**Comment by FinalAngel** [comment] 2015-11-23 17:28
thanks for the update @teutobod closing this than for now :)

**Closed by FinalAngel** 2015-11-23 17:28 UTC
Labels: component: frontend
