### ISSUE TITLE
There are not managing icons in list of pages in admin

### ISSUE THREAD

**Issue by AlexProfi** [divio/django-cms#4374] opened 2015-08-21 23:31 UTC
![screenshot-10](https://cloud.githubusercontent.com/assets/5154879/9421051/6855b894-4875-11e5-91db-5f5b157dafd0.png)
It happens sometimes when I save new page or click on toggle minus button in tree of pages

**Comment by evildmp** [comment] 2015-09-14 11:04
Does this only happen with the runserver, or also when running a site in production? I have often encountered rendering/behaviour glitches with the runserver, especially on complex admin pages, where it struggles to serve up the static files a page needs.

**Comment by AlexProfi** [comment] 2015-09-14 11:38
I see it on runserver but it's not permanent bug. On adding many pages I see this bug. It dissappears when I clcik on minus and then plus button to expand child pages  On production I don't check

**Comment by FinalAngel** [comment] 2015-09-21 06:28
@vxsx we also had this issue, did you fix this by any chance?

**Comment by vxsx** [comment] 2015-09-21 08:12
@FinalAngel no, we didn't fix this. This can happen if the page name length is long enough to overlap the icons (e.g. combo of long page name and lots of languages) or there is yet uncatched bug in the pagetree. 

@AlexProfi can you provide a bit more details? Is this behaviour consistent? What is the FF version / CMS version?

**Comment by AlexProfi** [comment] 2015-09-21 08:35
django cms 3.1.2 firefox 39 on linux

**Comment by yakky** [comment] 2015-11-17 05:30
@FinalAngel @vxsx  any update on this?

**Comment by vxsx** [comment] 2015-11-17 06:12
Sadly not yet @yakky.

**Comment by yakky** [comment] 2015-11-17 06:32
@vxsx thanks, postponing after 3.1.4 release

**Comment by yakky** [comment] 2016-01-24 17:03
@AlexProfi is this still valid in 3.1.4 / 3.2?
As we cannot reproduce this, I'm going to close this. Feel free to reopen fif you could provided updated feedback

**Closed by yakky** 2016-01-24 17:03 UTC
Labels: component: frontend, kind: bug
