### ISSUE TITLE
Cannot migrate to MySQL from SQLite3

### ISSUE THREAD

**Issue by alanondra** [divio/django-cms#4791] opened 2015-11-30 01:04 UTC
There is an error in the migration file `cms.0012_auto_20150607_2207` which generates this message:

```
mysql.connector.errors.ProgrammingError: 1091 (42000): Can't DROP 'user_id'; check that column/key exists
```

Running Python 3.4.3, Django-CMS 3.2.0, Django 1.8, and MySQL 5.7.2.

**Comment by yakky** [comment] 2015-11-30 06:44
What do you mean with "migrate to MySQL from SQLite3"?

**Comment by AlanOndra** [comment] 2015-12-02 13:05
Changing the database from SQLite3 to MySQL. I was unable to start a project using MySQL.

**Comment by evildmp** [comment] 2015-12-02 14:33
@AlanOndra It's not clear what's happening here.

So you have a working SQLite3 project, complete with database, and then you want to move it to MySQL? In that case, you wouldn't need to run ``cms.0012_auto_20150607_2207`` or any other migrations. Migrations are for making changes to the structure of a database, not migrating from one database to another.

If you mean something else, apologies, I haven't understood.

What error did you get when trying to start a project with MySQL? If that didn't succeed, you are very unlikely to get MySQL working otherwise.

If you give us more information I am sure we can help.

**Comment by LaurensBER** [comment] 2016-03-16 09:31
I'm having the same problem running the migrations on a empty DB. 

I can reproduce this issue.

State of the table:
`CREATE TABLE `cms_pageuser` (
  `user_ptr_id` int(11) NOT NULL,
  `created_by_id` int(11) NOT NULL,
  PRIMARY KEY (`user_ptr_id`),
  KEY `cms_pageuser_created_by_id_47c3d086010492c5_fk_auth_user_id` (`created_by_id`),
  CONSTRAINT `cms_pageuser_created_by_id_47c3d086010492c5_fk_auth_user_id` FOREIGN KEY (`created_by_id`) REFERENCES `auth_user` (`id`),
  CONSTRAINT `cms_pageuser_user_ptr_id_7b0231cd1ca953bf_fk_auth_user_id` FOREIGN KEY (`user_ptr_id`) REFERENCES `auth_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1`

Error:
`  Applying cms.0012_auto_20150607_2207...Traceback (most recent call last):
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/django/base.py", line 177, in _execute_wrapper
    return method(query, args)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1091 (42000): Can't DROP 'user_id'; check that column/key exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django_cassandra_engine/management/commands/migrate.py", line 14, in handle
    return super(Command, self).handle(*args, **options)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 502, in _alter_field
    self.execute(self._delete_constraint_sql(self.sql_delete_fk, model, fk_name))
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/django/base.py", line 227, in execute
    return self._execute_wrapper(self.cursor.execute, query, new_args)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/django/base.py", line 180, in _execute_wrapper
    utils.ProgrammingError(err.msg), sys.exc_info()[2])
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/django/base.py", line 177, in _execute_wrapper
    return method(query, args)
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/laurens/Env/test_new/lib/python3.4/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
django.db.utils.ProgrammingError: Can't DROP 'user_id'; check that column/key exists
`

Please note that we run the mysql connector (mysql-connector-python-rf (2.1.3)) instead of the default Django adapter:

-	'default':{
		'ENGINE': 'mysql.connector.django',
		'NAME': 'empty_db',
		'USER': 'root',
		'PASSWORD': '',
		'HOST': 'localhost',
		'PORT': '3306',
	},-

Reading the Django docs and stuff like [this](https://blog.ionelmc.ro/2014/12/28/terrible-choices-mysql/) I'm missing a specific MySQL setting. If I do find out which/what I'll try to add it and update this issue.

**Comment by LaurensBER** [comment] 2016-03-17 09:09
Just realized that migration 12 is about cms_usersettings:

```
class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20150419_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpagepermission',
            name='sites',
            field=models.ManyToManyField(help_text='If none selected, user haves granted permissions to all sites.', to='sites.Site', verbose_name='sites', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(related_name='djangocms_usersettings', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
    ]
```

The state of cms_usersettings is:

```
CREATE TABLE `cms_usersettings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `language` varchar(10) NOT NULL,
  `clipboard_id` int(11) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `cms_usersett_clipboard_id_2c0d157af86a3215_fk_cms_placeholder_id` (`clipboard_id`),
  CONSTRAINT `cms_usersett_clipboard_id_2c0d157af86a3215_fk_cms_placeholder_id` FOREIGN KEY (`clipboard_id`) REFERENCES `cms_placeholder` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

I can't figure out why this migration wants to drop the user_id nor why MySQL does not allow this (there is no constraint on user_id, right?). It might be that this is a bug in the MySQL connector or in the way Django interprets migrations? 

It would be quite useful if someone from the Django-CMS team would be willing to take a look at this and point me in the right direction, then I can file a bug for the correct project.

**Comment by LaurensBER** [comment] 2016-03-17 10:00
The problem seems to be that there is an unique_key with the same name, after dropping that we can remove the 'user_id' column without any problems. Seems to be a Django migration problem, right?

**Comment by jrief** [comment] 2016-05-08 21:02
Have you tried to dump the SQLite database content into a fixture, and reimport that fixture into MySQL?

A similar command I often use is:
```
./manage.py dumpdata --natural-foreign auth cms djangocms_text_ckeditor filer --exclude filer.clipboard --exclude filer.clipboarditem > fixture.json
```
you might need to add the other  3rd party plugins to the list of Django apps you want to dump.

**Comment by mewushuang** [comment] 2017-01-15 09:23
I met the same error, and i used mysql connector too,  maybe caused by  sth different in mysql connector with mysql-python i guess.
`$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, geekland, messages, sekizai, djangocms_admin_style, sitemaps, treebeard, cmsplugin_filer_utils
  Apply all migrations: cmsplugin_filer_folder, sessions, cms, djangocms_column, menus, djangocms_text_ckeditor, djangocms_video, sites, filer, djangocms_style, admin, cmsplugin_filer_image, easy_thumbnails, djangocms_googlemap, cmsplugin_filer_file, contenttypes, djangocms_snippet, djangocms_link, auth
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sites.0001_initial... OK
  Applying cms.0001_initial... OK
  Applying cms.0002_auto_20140816_1918... OK
  Applying cms.0003_auto_20140926_2347... OK
  Applying cms.0004_auto_20140924_1038... OK
  Applying cms.0005_auto_20140924_1039... OK
  Applying cms.0006_auto_20140924_1110... OK
  Applying cms.0007_auto_20141028_1559... OK
  Applying cms.0008_auto_20150208_2149... OK
  Applying cms.0008_auto_20150121_0059... OK
  Applying cms.0009_merge... OK
  Applying cms.0010_migrate_use_structure... OK
  Applying cms.0011_auto_20150419_1006... OK
  Applying cms.0012_auto_20150607_2207...Traceback (most recent call last):
  File "/home/van/archive/workspace/python/vpy/lib/python3.5/site-packages/mysql/connector/django/base.py", line 177, in _execute_wrapper
    return method(query, args)
  File "/home/van/archive/workspace/python/vpy/lib/python3.5/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/van/archive/workspace/python/vpy/lib/python3.5/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/van/archive/workspace/python/vpy/lib/python3.5/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1091 (42000): Can't DROP 'user_id'; check that column/key exists
`
The same error occurred when I tried with cms-installer. It works well if i change the db to default sqllite.
I use mysql5.7 , and tried with python 3.4 and 3.5

**Comment by mewushuang** [comment] 2017-01-15 09:25
I met the same error, and i used mysql connector too,  maybe caused by  sth different in mysql connector with mysql-python i guess.
```$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, geekland, messages, sekizai, djangocms_admin_style, sitemaps, treebeard, cmsplugin_filer_utils
  Apply all migrations: cmsplugin_filer_folder, sessions, cms, djangocms_column, menus, djangocms_text_ckeditor, djangocms_video, sites, filer, djangocms_style, admin, cmsplugin_filer_image, easy_thumbnails, djangocms_googlemap, cmsplugin_filer_file, contenttypes, djangocms_snippet, djangocms_link, auth
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sites.0001_initial... OK
  Applying cms.0001_initial... OK
  Applying cms.0002_auto_20140816_1918... OK
  Applying cms.0003_auto_20140926_2347... OK
  Applying cms.0004_auto_20140924_1038... OK
  Applying cms.0005_auto_20140924_1039... OK
  Applying cms.0006_auto_20140924_1110... OK
  Applying cms.0007_auto_20141028_1559... OK
  Applying cms.0008_auto_20150208_2149... OK
  Applying cms.0008_auto_20150121_0059... OK
  Applying cms.0009_merge... OK
  Applying cms.0010_migrate_use_structure... OK
  Applying cms.0011_auto_20150419_1006... OK
  Applying cms.0012_auto_20150607_2207...Traceback (most recent call last):
  File "/home/van/archive/workspace/python/vpy/lib/python3.5/site-packages/mysql/connector/django/base.py", line 177, in _execute_wrapper
    return method(query, args)
  File "/home/van/archive/workspace/python/vpy/lib/python3.5/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/van/archive/workspace/python/vpy/lib/python3.5/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/van/archive/workspace/python/vpy/lib/python3.5/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1091 (42000): Can't DROP 'user_id'; check that column/key exists
```
The same error occurred when I tried with cms-installer. It works well if i change the db to default sqllite.
I use mysql5.7 , and tried with python 3.4 and 3.5

**Comment by timgraham** [comment] 2017-02-02 01:31
I'd suggest to put together a minimal project  that reproduces the issue and file a bug with Django if the test fails with any built in database backends or with mysql/connector if the test only fails there. Most likely this isn't a django-cms problem.

**Comment by czpython** [comment] 2018-03-15 13:36
Closing for now.
Feel free to open a new ticket if this issue persists on newer django / django CMS versions.
Also it would really help to have a minimal project where we can reproduce this.

**Closed by czpython** 2018-03-15 13:36 UTC
Labels: needs more info
