### ISSUE TITLE
Code Snippet Plugin Disappears Upon Saving Text Content

### ISSUE THREAD

**Issue by artforlife** [divio/django-cms#6078] opened 2017-09-23 14:03 UTC
### Summary

I am not sure if this belongs here or is better suited for Aldryn NewsBlog repository. In short, placing a code snippet inside a Text content box does not work. 

I am able to place a Text box inside a `Newsblog_Article_Content` placeholder. Then, I type some text and place a CodeSnippet plugin inside the text content. The source looks like this:

```
<p>Post content here!</p>

<p>Some code here:<cms-plugin alt="Code - &lt;code&gt; " id="46" render-plugin="true" title="Code - &lt;code&gt;"><code>print(&#39;hello&#39;)</code></cms-plugin></p>
<cms-plugin alt="Code - &lt;pre&gt; " id="45" title="Code - &lt;pre&gt;"></cms-plugin>

<p>&nbsp;</p>
```
After I save the changes to the text, the code snippet is not shown. Upon opening the text area in edit mode, I see the following source:

```
<p>Post content here!</p>

<p>Some code here:<cms-plugin alt="Code - &lt;code&gt; " id="46" title="Code - &lt;code&gt;"></cms-plugin></p>

<p>&nbsp;</p>
```

* Python version: 3.5
* Django==1.10.9.dev20170906233227
* django CMS version: django-cms==3.4.5rc1

P.S. I have also experienced the same problem with Django 1.9 and a stack that seems to be deemed as "stable." I am just now reporting this because there were other more pressing issues at the time.

**Comment by czpython** [comment] 2017-09-26 16:19
Hello @artforlife,
Thanks for reporting.

Does this only happen with the `CodeSnippet` plugin?
Do you have a link to the plugin's source code?

**Comment by artforlife** [comment] 2017-09-26 16:37
@czpython I am not sure I fully understand the question. Is the CodeSnippet plugin not part of the Django-CMS? To me, it shows up by default in the Generic Text field as one of the buttons there. It is inside the dropbox called CMS Plugins.

See the attached image for illustration.

<img width="941" alt="screen shot 2017-09-26 at 12 36 25 pm" src="https://user-images.githubusercontent.com/8064423/30872240-6698a888-a2b7-11e7-819b-afe37d2261f1.png">

**Comment by czpython** [comment] 2017-09-26 16:47
@artforlife The text plugin comes from [djangocms-text-ckeditor](https://github.com/divio/djangocms-text-ckeditor). Any plugin inside of the "CMS Plugins" dropdown is a separate plugin with its own app.

If the plugin's type is CodeSnippet, you can get the file path to it (and thus the app) using something like: ``inspect.getfile(plugin_pool.get_plugin('CodeSnippet'))``

Example:

```
In [17]: from cms.plugin_pool import plugin_pool

In [18]: import inspect

In [19]: inspect.getfile(plugin_pool.get_plugin('StylePlugin'))
Out[19]: '/usr/local/lib/python2.7/site-packages/djangocms_style/cms_plugins.pyc'
```

Closing here as the issue is not in the core of django CMS.

**Closed** 2017-09-26 16:49 UTC
Labels: needs more info
