### ISSUE TITLE
Parameter for settings does not work

### ISSUE THREAD

**Issue by thoreg** [divio/django-cms#5326] opened 2016-05-20 13:21 UTC
On cms version '3.3.0.rc2' it is not possible to run e.g. the "cms check" management command with dedicated settings 

Variation like used with runserver - with the equal sign:
```
python manage.py cms check --settings=config.settings.development
...
usage: manage.py cms [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                     [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                     {check,copy,delete-orphaned-plugins,fix-tree,list,moderator,publisher-publish,uninstall}
                     ...
manage.py cms: error: unrecognized arguments: --settings=config.settings.development
```

Variation without equal sign - interpreted from "help" output:
```
python manage.py cms check --settings config.settings.development
...
usage: manage.py cms [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                     [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                     {check,copy,delete-orphaned-plugins,fix-tree,list,moderator,publisher-publish,uninstall}
                     ...
manage.py cms: error: unrecognized arguments: --settings config.settings.development
```

Hard coding of the dedicated settings works.

**Comment by mkoistinen** [comment] 2016-05-20 19:39
@yakky can you have a look at this?

**Comment by czpython** [comment] 2016-05-20 23:42
Yeah looks like we lost all django builtin options like ``--no-input``

**Comment by mkoistinen** [comment] 2016-05-20 23:50
The inability to declare --settings=... is a blocker. As is --no-input, to be honest.

**Comment by czpython** [comment] 2016-05-20 23:58
Looking at django source, seems that no-input is not there either.
The fix-tree command doesn't need this parameter but we need to make sure that it works for commands like uninstall plugins and such.

I agree that inability to declare --settings is a blocker.

**Comment by mkoistinen** [comment] 2016-05-23 22:52
Regression caused by #4947.

**Comment by czpython** [comment] 2016-05-24 16:17
@thoreg 
Thanks for your patience.
We've pushed a fix in https://github.com/divio/django-cms/pull/5340.
This will land in RC4.

**Closed** 2016-05-24 19:50 UTC
Labels: blocker, kind: bug, needs patch, needs tests, status: accepted
