### ISSUE TITLE
Resizing modal sends it outside window view area

### ISSUE THREAD

**Issue by jegorami** [divio/django-cms#6321] opened 2018-03-22 17:00 UTC
### Summary
Add/edit plugin action opens plugin configuration in a modal dialog.
When trying to resize it by dragging it using right lower corner, It enlarges in all directions, even going outside of the window view area.

### Expected behaviour
Resizing modal should follow mouse dragging movement and resize only to the right and / or down.

### Actual behaviour
Modal dialog resizes in all directions, even outside window view area

### Environment

* Python version: 2.7.6
* Django version: 1.8
* django CMS version: 3.5.1

**Comment by vxsx** [comment] 2018-03-22 17:24
It's not perfect, yes, but it works as intended. Would appreciate the pull request to limit the max size of the modal to the window size, but otherwise it's a wontfix.

**Closed by vxsx** 2018-03-22 17:24 UTC
Labels: status: won't fix
