### ISSUE TITLE
u'aldryn_newsblog_default' is not a registered namespace

### ISSUE THREAD

**Issue by yboussard** [divio/django-cms#5728] opened 2016-10-17 08:37 UTC
Hello,

I try to use aldryn_newsblog on a django-cms (django-cms==3.4.1, aldryn-newsblog==1.3.0)
I test on a fresh install (multiple time) and finally I try to setup django-cms with aldryn_newsblog extension with https://control.aldryn.com/control/ cloud system.
I have always the same error NoReverseMatch at /en/admin/r/56/1/ : u'aldryn_newsblog_default' is not a registered namespace
You can reproduce this at that url : https://test-youyou-stage.us.aldryn.io/en/admin/r/56/1/

On my local server I add in urls.py the namespace: 
    from aldryn_newsblog import urls as  aldryn_newsblog_urls
    ...
    url(r'^<namespace>/', include(aldryn_newsblog_urls, namespace = '<namespace>')) 
    ... 

The result that  /en/admin/r/56/1/ is resolved but provide a 404.
After that with a pdb I notice that namespace is not provided to query and 404 is return (another problem). And if I fix that , there is a new error .

So what append ? Why Apphook doesn't work ? aldryn_newsblog seems to be an essential add-on to django-cms . Do you use it with success  and if the answer is yes with witch good version of component ? 
Thanks a lot for your answer, 

Regards Youenn.

**Comment by czpython** [comment] 2016-10-17 11:15
Hello @yboussard,
I'm closing this as a duplicate of https://github.com/aldryn/aldryn-newsblog/issues/432.

**Closed by czpython** 2016-10-17 11:15 UTC
