### ISSUE TITLE
ToolbarMiddleware renders request.data empty when requesting multipart form data (with Django Rest Framework)

### ISSUE THREAD

**Issue by driesdesmet** [divio/django-cms#5446] opened 2016-06-22 08:00 UTC
This is an issue reported by @fsto in #3367 but I think it deserves it's own ticket. I ran into it using django-cms==3.2.5 and Django==1.8.13

It seems like 'cms.middleware.toolbar.ToolbarMiddleware' removes any uploaded file (sent via a multipart form request) in request.data which then is just an empty QueryDict. When commenting out 'cms.middleware.toolbar.ToolbarMiddleware' everything works like it should - I get the QueryDict in request.data containing the uploaded file.

A simple setup to reproduce this is to:

- Set up a django project with django-cms and django rest framework.
- Use ToolbarMiddleware
- Set up a POST handler inheriting APIView (django rest framework) with parser_classes = (MultiPartParser, )
- Any multipart form data will be removed (which is the issue). request.data is a <QueryDict: {}>
- Comment out 'cms.middleware.toolbar.ToolbarMiddleware' and the file upload handler works as intended.

**Comment by driesdesmet** [comment] 2016-06-22 08:50
Quite possibly, the problem lies upstream: the related DRF issue: https://github.com/tomchristie/django-rest-framework/issues/3951

**Comment by czpython** [comment] 2016-06-22 13:31
@driesdesmet 
I've tried reproducing the issue without DRF, here's the results:

```
ipdb> request.body
*** RawPostDataException: You cannot access body after reading from request's data stream
ipdb> request.POST
<QueryDict: {u'username': [u'xyz']}>
ipdb> request.FILES
<MultiValueDict: {u'upload': [<InMemoryUploadedFile: README.rst (application/octet-stream)>]}>
```

As you can see files and field data is available, request.body throws error because of the middleware but this is caused by the same code in https://github.com/divio/django-cms/issues/3367.

I'll close this as the reported issue is in DRF.
Will open a new ticket for ``request.body``

**Closed by czpython** 2016-06-22 13:31 UTC
Labels: needs patch, status: accepted
