### ISSUE TITLE
Apphook urls disappear for authenticated non superuser account

### ISSUE THREAD

**Issue by syaiful6** [divio/django-cms#6897] opened 2020-09-08 11:51 UTC
## Description

Our site allow user to login, we use standard Django authentication and User model. user can login to read private content. We assign the user to a Django Group that allow view page permission. The problem is when user logged in, the apphook url mysteriously disappear. And it caused our `reverse("view_name")` to fail, even though the view_name is registered in apphook, it work for non logged in user or superuser login.

This is the urlpattern Django tried to match for non logged in user and superuser login:

![Screenshot from 2020-09-07 10-12-35](https://user-images.githubusercontent.com/2830977/92471743-a1679d00-f202-11ea-9766-9c6f4b5e0f73.png)

And this is what's Django tried to match for logged in user (non staff and no superuser)l:

![Screenshot from 2020-09-07 10-12-25](https://user-images.githubusercontent.com/2830977/92472077-323e7880-f203-11ea-932c-058a71a07529.png)

## Steps to reproduce

1. Create basic login view
2. Assign an apphook to a page
3. Login using non superuser login
4. Visit the apphook url 

## Expected behaviour

The urlpattern for non logged in user and authenticated user should be the same. 

## Actual behaviour

The apphook seem not mounted for authenticated non superuser user. 

## Additional information

Python 3.7
Django CMS 3.7.4
Django 2.2.12

**Comment by FinalAngel** [comment] 2020-09-09 07:26
@victor-yunenko @Aiky30 appreciate any feedback here :)

**Comment by syaiful6** [comment] 2020-09-09 08:24
update, the url of apphook also disappear for new superuser account, it just work for the superuser that created the page.

**Comment by syaiful6** [comment] 2020-09-20 13:53
@Aiky30 After debugging today, I found it cause by a middleware in pinax django-user-accounts library: https://github.com/pinax/django-user-accounts/blob/v1.3.1/account/middleware.py#L30 That middleware set LANGUAGE_CODE to request, If I remove that middleware the apphook work.

**Comment by Aiky30** [comment] 2020-09-20 14:51
@syaiful6 Awesome. Does this mean we can close this issue? I would advise creating an issue with django-user-accounts if the issue is introduced by that package.

**Comment by syaiful6** [comment] 2020-09-24 01:36
yes, we can close this issue. But I am unsure if that package doing it wrong by settings the language code.

**Comment by Aiky30** [comment] 2020-10-01 11:07
@syaiful6 

> yes, we can close this issue. But I am unsure if that package doing it wrong by settings the language code.

If the other package is doing something wrong then I would advise opening an issue on the django-user-accounts package: https://github.com/pinax/django-user-accounts

**Closed by Aiky30** 2020-10-01 11:07 UTC
Labels: needs expert opinion
