### ISSUE TITLE
Make toolbar history work with placeholderfields

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#3701] opened 2014-12-21 04:32 UTC
This is the flip-side to #3700. If the History menu remains in the toolbar at all times, then we need to document how users should integrate their custom apphook models that are editable from the front-end so that clicking 'Undo' actually impacts the model instance (e.g. blog post) being edited and not whichever Page the apphook is attached to.

**Comment by yakky** [comment] 2015-02-22 18:04
This is not going to happen in 3.1, but definitely a much-needed improvements for django CMS

**Comment by czpython** [comment] 2016-05-26 14:10
Closing as duplicate of https://github.com/divio/django-cms/issues/4920

**Closed by czpython** 2016-05-26 14:10 UTC
Labels: kind: enhancement, status: accepted
