### ISSUE TITLE
overwritten urls are re-overwritten when page is moved (changing siblings order)

### ISSUE THREAD

**Issue by juanromerocortes** [divio/django-cms#6533] opened 2018-09-25 23:12 UTC
### Summary

I have a set of pages that are children of another one.
Those pages have the url overwritten (using the advanced settings option for it).
When I change the order of any of these pages, the overwrite field is modified, adding the "/parent_page/" slug to the "overwrite url" field.

### Expected behaviour
Moving pages using drag&drop should keep the overwrite url field the same.

### Actual behaviour
Moving pages using drag&drop is modifying the overwrite url field.

### Environment

* Python version: 3.6.3
* Django version:  1.11.10
* django CMS version:  3.5.0

**Comment by czpython** [comment] 2018-10-14 16:38
Closing as duplicate of #6383

**Closed by czpython** 2018-10-14 16:38 UTC
