### ISSUE TITLE
manage.py migrate fails on 3.1

### ISSUE THREAD

**Issue by mistalaba** [divio/django-cms#4123] opened 2015-05-22 13:45 UTC
I have two different sites running django-cms 3.0.13 (Django 1.7.8) and when I try to upgrade them, I get the following:

	$ python manage.py migrate
	/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/cmsplugin_filer_utils/__init__.py:5: RemovedInDjango18Warning: `FilerPluginManager.get_query_set` method should be renamed `get_queryset`.
	  class FilerPluginManager(models.Manager):

	Traceback (most recent call last):
	  File "manage.py", line 10, in <module>
		execute_from_command_line(sys.argv)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
		utility.execute()
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
		django.setup()
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
		apps.populate(settings.INSTALLED_APPS)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
		app_config.ready()
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
		self.module.autodiscover()
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 23, in autodiscover
		autodiscover_modules('admin', register_to=site)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
		import_module('%s.%s' % (app_config.name, module_to_search))
	  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
		__import__(name)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/cms/admin/__init__.py", line 11, in <module>
		plugin_pool.plugin_pool.discover_plugins()
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/cms/plugin_pool.py", line 34, in discover_plugins
		load('cms_plugins')
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/cms/utils/django_load.py", line 57, in load
		get_module(app, modname, verbose, failfast)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/cms/utils/django_load.py", line 41, in get_module
		module = import_module(module_name)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/utils/importlib.py", line 46, in import_module
		__import__(name)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/djangocms_link/cms_plugins.py", line 8, in <module>
		from djangocms_link.forms import LinkForm
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/djangocms_link/forms.py", line 9, in <module>
		class LinkForm(ModelForm):
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/djangocms_link/forms.py", line 12, in LinkForm
		page_link = PageSearchField(queryset=Page.objects.drafts(), label=_("Page"), required=False)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django_select2/fields.py", line 305, in __call__
		if not queryset and hasattr(cls, '_subclass_queryset'):
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/db/models/query.py", line 145, in __nonzero__
		self._fetch_all()
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
		self._result_cache = list(self.iterator())
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
		for row in compiler.results_iter():
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
		for rows in self.execute_sql(MULTI):
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
		cursor.execute(sql, params)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
		return super(CursorDebugWrapper, self).execute(sql, params)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
		return self.cursor.execute(sql, params)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
		six.reraise(dj_exc_type, dj_exc_value, traceback)
	  File "/home/user/.virtualenvs/mysite/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
		return self.cursor.execute(sql, params)
	django.db.utils.ProgrammingError: column cms_page.path does not exist
	LINE 1: SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth...
									^

I suspect that there's something off with the migrations, but I am not exactly sure what and don't know how to fix it. On discrepancy I see is that my installation has five migrations, but looking at the source code, django-cms 3.0.13 only has three. 

Here's mine from the db:
0001_initial
0002_auto_20140816_1918
0003_auto_20140926_2347
0004_auto_20150310_0040
0005_auto_20150420_1412

And 3.0.13 from your source:
0001_initial
0002_auto_20140816_1918
0003_auto_20140926_2347

Any ideas?
Cheers,
/Martin

**Comment by yakky** [comment] 2015-05-22 19:40
Have you updated the ``MIGRATION_MODULES`` parameter?

**Comment by marty3d** [comment] 2015-05-23 02:55
Yes, I removed 'cms' and 'menus' as mentioned in the docs.

Is there anything else I can provide?

**Comment by yakky** [comment] 2015-05-24 07:22
Well, I can't get where ``0004_auto_20150310_0040`` and ``0005_auto_20150420_1412`` come from.
Is ``cms`` before the other plugins in ``INSTALLED_APPS``?

**Comment by lddubeau** [comment] 2015-05-27 14:09
Regarding the crash, I would have thought this [patch](https://github.com/divio/djangocms-link/commit/2e3f8d399e3e42fe276ed3aa3199081ae2f654e0) would have fixed the problem. `djangocms-link` 1.6 or later contains the patch.

Here's one possible scenario regarding the mysterious migrations. Sometimes the migration system will consider that a model has been changed even though it has not been changed. Let's call this a "spurious change". This is the case for me with `django-allauth`: Django insists that there is a migration that should be recorded for it even though that's not the case. The problem is that if there is a spurious change and you issue `./manage.py makemigration` after you've modified one of *your* models, Django is going to make a migration for your model but will *also* see the spurious change and make a migration for it (a "spurious migration"), because if you do not specify more narrowly what you want `makemigration` to work on, it is going to work on all models in all apps that have migrations. I once ended up with a spurious migration for `django-allauth` this way. If you are installing packages system-wide, file system permissions should prevent the creation of the spurious migration but if you are using a virtualenv setup, then you probably have the necessary permissions to create the file.

I've not used Django CMS 3.0.x (I use 3.1.0) but if it is possible to get it in a state where Django detects a spurious change then this could explain the presence of spurious migrations.

**Comment by poligarcia** [comment] 2015-05-29 20:10
The same thing happens while running any management task:

```
foo@bar:~my_cms_project$ ./manage.py check
(Django18Warnings...)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 238, in patch_all
    patch_root_urlconf()
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 226, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 269, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/foo/my_cms_project/my_cms_project/urls.py", line 26, in <module>
    url(r'^cms/', include('cms.urls')),
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/cms/urls.py", line 20, in <module>
    urlpatterns = get_app_patterns()
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/cms/appresolver.py", line 204, in get_app_patterns
    for title in title_qs.exclude(page__application_urls=None).exclude(page__application_urls='').select_related():
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/db/models/query.py", line 141, in __iter__
    self._fetch_all()
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/cachalot/monkey_patch.py", line 45, in inner
    out = original(compiler, *args, **kwargs)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/cachalot/monkey_patch.py", line 98, in inner
    execute_query_func, cache_key, _get_table_cache_keys(compiler))
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/cachalot/monkey_patch.py", line 71, in _get_result_or_execute_query
    result = execute_query_func()
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/cachalot/monkey_patch.py", line 85, in <lambda>
    execute_query_func = lambda: original(compiler, *args, **kwargs)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/cachalot/monkey_patch.py", line 124, in inner
    out = original(cursor, sql, *args, **kwargs)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/foo/.virtualenvs/bar/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column cms_page.path does not exist
LINE 1: ..., "cms_title"."publisher_state", "cms_page"."id", "cms_page"...
```

The problem I think is that cms.urls is calling cms.appresolver.get_app_patterns that runs a query using django's ORM, which isn't migrated yet.

**Comment by lddubeau** [comment] 2015-05-29 20:25
@poligarcia Try with `debug_toolbar` removed from `INSTALLED_APPS`. You can always add it back later, after the migration. (I don't see migrations for it, so you won't need to migrate this app separately after you add it back.) My site is already migrated but if I have `debug_toolbar` in the installed apps, then `cms.appresolver.get_app_patterns`. If I do not have it in the installed apps, then the call is not made.

**Comment by poligarcia** [comment] 2015-05-29 20:32
Thanks, I'll give it a try and keep you posted!

**Comment by yakky** [comment] 2015-05-30 09:16
When using django debug toolbar bear in mind to always use explicit setup to configure it

On 29 May 2015 21:32:13 BST, "Poli García" <notifications@github.com> wrote:
>Thanks, I'll give it a try and keep you posted!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/divio/django-cms/issues/4123#issuecomment-106927843

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by rando305** [comment] 2015-06-01 17:24
django.db.utils.ProgrammingError: column cms_page.path does not exist
LINE 1: SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth...

I get this at run-time.  I don't get a migration error.

Any progress on this?

**Comment by yakky** [comment] 2015-06-01 17:37
This looks like an incomplete migration. Are you using Django 1.7 or 1.6?

**Comment by poligarcia** [comment] 2015-06-01 17:38
@lddubeau Disabling `debug_toolbar` makes the problem disappear.

Thanks

**Comment by rando305** [comment] 2015-06-01 17:50
1.7

**Comment by rando305** [comment] 2015-06-01 17:52
I have disabled debug_toolbar and it doesn't make a difference for me.
I also find the same result in the admin - when I select Pages in the  django CMS section

**Comment by lddubeau** [comment] 2015-06-02 13:10
@rando305 You should post a complete stack trace. It is only through examining the trace that I was able to propose a workaround for poligarcia's problem and that I was able to formulate an hypothesis regarding marty3d's problem.  

And the output of `select * from django_migrations where app='cms';` should be helpful in determining whether it is an incomplete migration.

**Comment by rando305** [comment] 2015-06-09 21:01
@lddubeau thank you for your help.

This is the trace:
(sorry about the ugliness.  How do I beautify this? like those above?)

ERROR:django.request: Internal Server Error: /en/ (2015-06-09 16:51:51; base.py:231)
Traceback (most recent call last):
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/cms/views.py", line 72, in details
    page = get_page_from_request(request, use_path=slug)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/cms/utils/page_resolver.py", line 116, in get_page_from_request
    page = get_page_from_path(path, preview, draft)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/cms/utils/page_resolver.py", line 72, in get_page_from_path
    return get_page_queryset_from_path(path, preview, draft).get()
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 159, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 101, in _record
    return method(sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column cms_page.path does not exist
LINE 1: SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth...
                                ^

ERROR:django.request: Internal Server Error: /en/ (2015-06-09 16:51:51; base.py:231)
Traceback (most recent call last):
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/cms/views.py", line 72, in details
    page = get_page_from_request(request, use_path=slug)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/cms/utils/page_resolver.py", line 116, in get_page_from_request
    page = get_page_from_path(path, preview, draft)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/cms/utils/page_resolver.py", line 72, in get_page_from_path
    return get_page_queryset_from_path(path, preview, draft).get()
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 159, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 101, in _record
    return method(sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column cms_page.path does not exist
LINE 1: SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth...

**Comment by rando305** [comment] 2015-06-09 21:30
when I try and run migrations I get the following:  (again sorry for the ugly - I haven't figured out how to prettify)

Running migrations:
  Applying djangocms_file.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/home/randy/PycharmProjects/env_ops/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 75, in render
    "for more" % new_unrendered_models
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'cms.PageUser'>, <ModelState: 'cms.PageUserGroup'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more
(env_ops)randy@TestSrv:~/PycharmProjects/Ops$

**Comment by yakky** [comment] 2015-06-09 23:15
@rando305 apparently there is something wrong with some configuration ``Cannot resolve bases for [, ]``  is a weird message (there are supposed to be Django models between breackets)
Any custom applications installed in the project?

**Comment by lddubeau** [comment] 2015-06-10 13:43
@rando305 If you put three backticks (```) at the start and end of the stack traces, github should treat them as code blocks. I would have edited it for you but I cannot edit other user's posts.

I've tried replicating your issue here but was unsuccessful.

**Comment by marty3d** [comment] 2015-06-11 12:04
Hi, sorry for a late reply...I've been traveling but now I'm back in one place for a while :)

So, I did a new try today. I copied my repo to a new directory and created a new virtualenv from my requirements.txt, then ran python manage.py syncdb and it works. So there's definitely something icky going on in site-packages, but I can't figure out what, and I'm a little bit concerned about clearing the whole thing and do a fresh install of all packages. Should I?

Here's a list of the discrepancies between the old and new virtualenv's site-packages (I left out everything that's identical):
```
Original:                                         New:
django_appconf-0.6-py2.7.egg-info                 django_appconf-1.0.1.dist-info
djangocms_admin_style-0.2.5-py2.7.egg-info        djangocms_admin_style-0.2.7.dist-info
djangocms_blog                                    * Does not exist *
django_compressor-1.4-py2.7.egg-info              django_compressor-1.4.dist-info
django_extensions-1.5.2-py2.7.egg-info            django_extensions-1.5.2.dist-info
django_filer-0.9.9-py2.7.egg-info                 django_filer-0.9.9.dist-info
django_meta-0.2.1-py2.7.egg-info                  django_meta-0.2.1.dist-info
django_meta_mixin-0.1.1-py2.7.egg-info            django_meta_mixin-0.1.1.dist-info
django_parler-1.2.1-py2.7.egg-info                django_parler-1.4.dist-info
django_polymorphic-0.6.1-py2.7.egg-info           django_polymorphic-0.7.1.dist-info
django_sekizai-0.8.1-py2.7.egg-info               django_sekizai-0.8.1.dist-info
Django_Select2-4.2.2-py2.7.egg-info               Django_Select2-4.3.1-py2.7.egg-info
django_taggit-0.12.2-py2.7.egg-info               django_taggit-0.14.0.dist-info
django_taggit_autosuggest-0.2.6-py2.7.egg-info    django_taggit_autosuggest-0.2.7-py2.7.egg-info
django_templatetag_sugar-1.0-py2.7.egg-info       django_templatetag_sugar-1.0.dist-info
ecdsa-0.13-py2.7.egg-info                         ecdsa-0.13.dist-info
ipython-2.2.0-py2.7.egg-info                      ipython-2.2.0.dist-info
paramiko-1.15.2-py2.7.egg-info                    paramiko-1.15.2.dist-info
pytz-2014.10-py2.7.egg-info                       pytz-2015.4.dist-info
six-1.9.0-py2.7.egg-info                          six-1.9.0.dist-info
Werkzeug-0.10.4-py2.7.egg-info                    Werkzeug-0.10.4.dist-info
```
Does this raise any eyebrows?

> Well, I can't get where 0004_auto_20150310_0040 and 0005_auto_20150420_1412 come from.
> Is cms before the other plugins in INSTALLED_APPS?

Actually, uninstalling 3.0.13 left some files in site-packages, so after deleting the cms folder manually, they're no longer an issue.

**Comment by lddubeau** [comment] 2015-06-11 12:17
@marty3d You don't have `djangocms-link` in either lists of packages. I had suggested in [this comment](https://github.com/divio/django-cms/issues/4123#issuecomment-105925327) that upgrading it would probably fix the issue. The trace you had in your original report went through code in `djangocms-link`.

So is it just not installed in the new setup? Did you upgrade it?

**Comment by marty3d** [comment] 2015-06-11 12:21
Oh sorry, it is present, I just removed it to show the differences between the package lists. Here's the full list in the original site-packages:
```
admin_enhancer
appconf
beautifulsoup4-4.3.2-py2.7.egg-info
bs4
classytags
cms
cmsplugin_filer-0.10.1-py2.7.egg-info
cmsplugin_filer_file
cmsplugin_filer_folder
cmsplugin_filer_image
cmsplugin_filer_link
cmsplugin_filer_teaser
cmsplugin_filer_utils
cmsplugin_filer_video
compressor
Crypto
debug_toolbar
django
Django-1.7.6.dist-info
django_admin_enhancer-1.0.0.dist-info
django_appconf-1.0.1.dist-info
django_classy_tags-0.6.1.dist-info
django_cms-3.1.0.dist-info
djangocms_admin_style
djangocms_admin_style-0.2.7.dist-info
djangocms-blog.egg-link
djangocms_link
djangocms_link-1.5.dist-info
djangocms_text_ckeditor
djangocms_text_ckeditor-2.4.3.dist-info
django_compressor-1.4.dist-info
django_debug_toolbar-1.3.0.dist-info
django_extensions
django_extensions-1.5.2.dist-info
django_filer-0.9.9.dist-info
django_meta-0.2.1.dist-info
django_meta_mixin-0.1.1.dist-info
django_mptt-0.6.1-py2.7.egg-info
django_parler-1.4.dist-info
django_polymorphic-0.7.1.dist-info
django_sekizai-0.8.1.dist-info
django_select2
Django_Select2-4.3.1-py2.7.egg-info
django_taggit-0.14.0.dist-info
django_taggit_autosuggest-0.2.7-py2.7.egg-info
django_taggit_templatetags-0.2.5-py2.7.egg-info
django_templatetag_sugar-1.0.dist-info
django_treebeard-3.0-py2.7.egg-info
easy-install.pth
easy_install.py
easy_install.pyc
easy_thumbnails
easy_thumbnails-2.1-py2.7.egg-info
ecdsa
ecdsa-0.13.dist-info
fabfile
fabric
Fabric-1.10.1-py2.7.egg-info
filer
html5lib
html5lib-0.99999-py2.7.egg-info
IPython
ipython-2.2.0.dist-info
lxml
lxml-3.4.4-py2.7.egg-info
_markerlib
menus
meta
meta_mixin
mptt
paramiko
paramiko-1.15.2.dist-info
parler
PIL
Pillow-2.7.0-py2.7.egg-info
pip
pip-7.0.3-py2.7.egg-info
pkg_resources.py
pkg_resources.pyc
polymorphic
psycopg2
psycopg2-2.5.4-py2.7.egg-info
pycrypto-2.6.1-py2.7.egg-info
pytz
pytz-2015.4.dist-info
sekizai
setuptools
setuptools-0.9.8-py2.7.egg-info
six-1.9.0.dist-info
six.py
six.pyc
south
South-1.0.2-py2.7.egg-info
sqlparse
sqlparse-0.1.15-py2.7.egg-info
taggit
taggit_autosuggest
taggit_templatetags
templatetag_sugar
treebeard
unidecode
Unidecode-0.04.17-py2.7.egg-info
werkzeug
Werkzeug-0.10.4.dist-info
```

**Comment by marty3d** [comment] 2015-06-11 12:55
Ok, new update!

@lddubeau mentioned djangocms-link and just to make sure, I uninstalled it and looked in site-packages. There was still a djangocms_link/migrations_django/0003_auto_20150310_0040.py file. Deleting the djangocms_link directory and installing djangocms-link again solved my problem! (of course there's another one now, but it's not related to django cms).

So basically, my issues where residues in site-packages, it gets fixed by making sure their directories don't exist in site-packages after uninstalling.

Cheers to all who helped out! (I'm not closing if someone else still has issues)

**Comment by yakky** [comment] 2015-06-11 15:54
@marty3d thank you so much for your update!
@rando305 probably you could test the same cleanup

**Comment by ablochs** [comment] 2015-08-31 13:20
the following solved the issue for me: do a fake migration back to 0002 and then migrate...
```
python manage.py migrate cms 0002 --fake
python manage.py migrate cms
```

**Comment by yakky** [comment] 2015-11-10 08:07
Closed as non-issue

**Closed by yakky** 2015-11-10 08:07 UTC
Labels: kind: bug, status: accepted, status: marked for rejection

**Comment by lohithdeva** [comment] 2018-05-23 12:33
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\django\conf\__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\django\conf\__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "H:\MyMDB\django\config\settings.py", line 99
    CREATE DATABASE mymdb;
                  ^
SyntaxError: invalid syntax





How to solve this error?
