### ISSUE TITLE
ProgrammingError raised on empty DB (CMS_RAW_ID_USERS)

### ISSUE THREAD

**Issue by Pankrat** [divio/django-cms#6100] opened 2017-10-13 13:31 UTC
### Summary

When running `django-admin check` or `django-admin migrate` on a fresh database and `CMS_RAW_ID_USERS = True` in the settings, I get a `ProgrammingError`. This affects Django 1.11.x and worked fine on Django 1.10.x.

### Expected behaviour

`django-admin check` and `django-admin migrate` should work.

### Actual behaviour

```
$ django-admin check
Traceback (most recent call last):
  File "django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "django/core/management/commands/check.py", line 68, in handle
    fail_level=getattr(checks, options['fail_level']),
  File "django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "django/contrib/admin/checks.py", line 25, in check_admin_app
    errors.extend(site.check(app_configs))
  File "django/contrib/admin/sites.py", line 81, in check
    errors.extend(modeladmin.check())
  File "django/contrib/admin/options.py", line 117, in check
    return self.checks_class().check(self, **kwargs)
  File "django/contrib/admin/checks.py", line 520, in check
    errors = super(ModelAdminChecks, self).check(admin_obj)
  File "django/contrib/admin/checks.py", line 72, in check
    errors.extend(self._check_raw_id_fields(admin_obj))
  File "django/contrib/admin/checks.py", line 90, in _check_raw_id_fields
    if not isinstance(obj.raw_id_fields, (list, tuple)):
  File "cms/utils/helpers.py", line 46, in __get__
    return self.fget(owner_cls)
  File "cms/admin/permissionadmin.py", line 158, in raw_id_fields
    threshold = threshold and get_user_model().objects.count() > threshold
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "auth_user"
```

It looks like Django now raises a ProgrammingError and not a OperationalError (which would be catched in cms/admin/permissionadmin.py). Maybe the more generic DatabaseError should be catched instead?

### Work-around

Disable `CMS_RAW_ID_USERS` until the database is initialized.

### Environment

* Python version: 2.7.12
* Django version: 1.11.6
* django CMS version: 3.4.5

**Comment by czpython** [comment] 2017-10-13 13:40
Thanks for reporting this.
Closing as a duplicate of https://github.com/divio/django-cms/issues/5262

**Closed by czpython** 2017-10-13 13:40 UTC
