### ISSUE TITLE
template edit gets blocked when youtube autoplay iframe is added

### ISSUE THREAD

**Issue by orlax** [divio/django-cms#5377] opened 2016-06-06 18:07 UTC
i create a custom plugin to add an iframe to a page in different placeholders it just has a charfield where i put the iframe code wicht gets rendered on the template with a {{ instance.iframe |safe }} tag. 

it works as intended, but if the youtube url has the &autoplay=1 attribute the pages fails to load most of the others plugins and can no longer edit, the toolbar toggle button gets disabled. 

only solution i found was to reverse to a backup of my data base when the plugin with autoplay on its iframe did not exist. 

maybe this is youtube fault?

**Comment by czpython** [comment] 2016-06-06 18:40
@orlax 
Please provide some code samples for us to try and reproduce the problem.
Specifically what plugin are you using for this youtube/iframe?

Also are there any errors on the browser console?

**Comment by orlax** [comment] 2016-06-06 20:23
here: https://github.com/orlax/youtubeIframeDjangocms

-started a new django cms project with the django-installer tool
-used bootstrap and sample data
-added an iframe element with autoplay from youtube to the "feature.html" templates.
-it fails to load other plugins besides the video and edit mode is no longer accesible.

**Comment by vxsx** [comment] 2016-06-07 06:24
Hi @orlax, in the example you provided I see markup like this
```html
<iframe id="ytplayer" type="text/html" width="640" height="390"
	  src="http://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1&origin=http://example.com"
	  frameborder="0"/>
```
The reason nothing else is rendering is because iframe is not a self-closing tag, so everything that comes after this line is treated as contents of the iframe. Correct way to write this would be
```html
<iframe id="ytplayer" type="text/html" width="640" height="390"
	  src="http://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1&origin=http://example.com"
	  frameborder="0"></iframe>
```

**Closed by vxsx** 2016-06-07 06:24 UTC
Labels: needs more info
