### ISSUE TITLE
Edit nested plugin: Missing inlines.

### ISSUE THREAD

**Issue by creimers** [divio/django-cms#4897] opened 2016-01-09 17:43 UTC
Django==1.8.4
cms==3.2

When editing the leaf plugin in the attached screenshot, its inlines are missing (`admin.StackedInline`). They are there, however, when the plugin is initialized.

<img width="960" alt="bildschirmfoto 2016-01-09 um 18 38 44" src="https://cloud.githubusercontent.com/assets/6090492/12217433/631163e8-b700-11e5-9bcc-83a07b9525c3.png">

Is this a bug? Am I missing something, e.g. a plugin setting?

**Comment by mkoistinen** [comment] 2016-01-12 14:09
The only thing that is apparent from the screen-shot here is that the Teaser plugin doesn't accept children plugins, which I believe is by design.

Your query about the Inlines is confusing to me here. Do you mean admin.ModelAdmin.inlines? If so, the Structure mode doesn't show Admin inline forms at all. You would get to them by editing the plugin where you've defined them.

It would be more useful to see your Plugin definition, but in general, to make Django Admin inlines work, just note that the CMSPluginBase inherits from ModelAdmin, so, you can use the 'inlines = [...]' as a class property in your Plugin definition. Of course, you'll have to import your inlines first, but they should work fine, I use them regularly. Here's an example: https://gist.github.com/mkoistinen/37100a4a6c730a81de12

I hope this helps. I will close this ticket, but if I've not addressed your question, please re-open.

**Closed by mkoistinen** 2016-01-12 14:09 UTC

**Comment by creimers** [comment] 2016-01-12 15:48
The teaser plugin does not accept child plugins by design, correct.

I know that the structure mode does not show any inline forms. I'm talking about inlines in the cms admin modals upon initialization/editing.

I think we are talking about the same kind of inlines.

Here's my plugin definition:

```
class TeaserPlugin(CMSPluginBase):
    model = Teaser
    name = _("Teaser")
    render_template = "teaser/_plugin_teaser.jade"
    inlines = [ButtonInline, ]
```

Also I have additional info from the error log when saving the instance with the missing inline forms:

```
  File "/env/local/lib/python2.7/site-packages/django/forms/formsets.py", line 97, in management_form
    code='missing_management_form',
ValidationError: [u'ManagementForm data is missing or has been tampered with']
```

Maybe I should paraphrase my question to be more general: Under what circumstances, if ever, have you seen Inline forms "disappear"?

**Comment by creimers** [comment] 2016-01-16 19:11
<img width="313" alt="bildschirmfoto 2016-01-16 um 19 40 22" src="https://cloud.githubusercontent.com/assets/6090492/12373963/48fb8f78-bc8d-11e5-871a-7a4648a91617.png">

I had a `__str__` method in python2...
