### ISSUE TITLE
Add and delete a plugin twice in a row -> 404 error

### ISSUE THREAD

**Issue by otg-sandrey** [divio/django-cms#4731] opened 2015-11-17 20:16 UTC
Steps to reproduce:
- create new page
- choose a Text (actully, I tried different plugins with the same result) plugin to add it to a placeholder
- Text plugin window will open
- click the cross in the top right corner of the plugin window to close it
- click "OK" to confirm that the plugin has to be deleted
- then again...
- choose a Text (actully, I tried different plugins with the same result) plugin to add it to a placeholder
- Text plugin window will open
- click the cross in the top right corner of the plugin window to close it
- click "OK" to confirm that the plugin has to be deleted

You'll see "undefined | 404 Not found" error. The plugin window is still open. The plugin is not deleted.

**Comment by otg-sandrey** [comment] 2015-11-17 20:18
I successfully reproduced the problem using the trial CMS instance at www.django-cms.org

**Comment by evildmp** [comment] 2015-11-20 12:11
Thanks for this excellent bug report. I can't reproduce it in 3.2 though.

I do however get a slightly unclear "Plugin will be added here" placeholder showing up after the first aborted plugin:

![Plugin will be added here](https://www.dropbox.com/s/093o38snw97i27n/Screenshot%202015-11-20%2012.05.49.png?dl=0)

**Comment by evildmp** [comment] 2015-11-20 13:20
I can reproduce in 3.1. However since we are about to release 3.2 very soon and it doesn't appear there, I think this is probably a won't fix, because of that.

**Closed** 2015-11-20 13:31 UTC
Labels: kind: bug, status: won't fix
