### ISSUE TITLE
Pages under apphook causes 404

### ISSUE THREAD

**Issue by horejsek** [divio/django-cms#6282] opened 2018-02-16 09:46 UTC
### Summary

Create a page with an app-hook and some pages under that page with app hook. Sometimes it causes 404. I discovered this problems: sometimes in doesn't work at all (all the time error 404), sometimes it doesn't work only when I'm in published mode and go into edit mode (only during the action, when I'm already in edit mode, it works), sometimes it works just fine. I'm not able to reproduce it the same way all the time.

Restart of the server doesn't help. Once helped to change slug of the page with app-hook and then change it back to original one. Once helped to move page with app-hook somewhere else but putting it back caused that problem again.

### Environment

* Python version: 3.5.2
* Django version: 1.11.6
* django CMS version: 3.4.5

**Comment by horejsek** [comment] 2018-02-19 11:42
It doesn't work even in Django CMS version 3.5.0

**Comment by czpython** [comment] 2018-02-19 11:47
Hello,
Thanks for reporting this.
Pages under apphooked pages have never been truly supported.
I think this mostly falls under a documentation issue.

**Comment by horejsek** [comment] 2018-02-19 14:56
Maybe in that case it shouldn't be allowed at all (not just write in the docs, but disable to create page under app hook) or consider to support it.

**Comment by vstoykov** [comment] 2018-03-26 09:09
@horejsek  It's not a good idea to disable pages under apphooks. There are valid cases and depending on your apphook urls the pages can work without problems.

Also depending on the logic in your app hook views you can render child pages without problem. We used this technique even on Django CMS 2.x days (if I'm not mistaken).

**Comment by horejsek** [comment] 2018-03-26 10:46
@vstoykov I agree with you. But if there is problem and it's not supported for now without plan to support it, it's good to disable it for now because users can use it without knowing those problems.

**Comment by vstoykov** [comment] 2018-03-26 10:56
Actually in my point of view the problem is in the implementation of the specific apphook and not the CMS. I need to check how it works in latest version to see if there are some changes for which I'm not aware of.

The support from the CMS will come with documentation explaining how you can have subpages to a page with apphook.

If you can show me your app `urls.py` file and the structure of pages with exact slugs (only the page with the apphook and it's children) then I can tell you where is your problem. and eventually how to fix it.

**Comment by horejsek** [comment] 2018-03-26 11:30
URLs:

 * / - homepage
 * /app - page with an app hook
 * /app/subpage - manual page created by user

And the app hook have:

```
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^view/$', views.view, name='view'),
    url(r'^view2/$', views.view2, name='view2'),
    ...
]
```

**Comment by vstoykov** [comment] 2018-03-26 12:10
I think that your URLs are actually:

  - `/`
  - `/app/`
  - `/app/subpage/`

Ends with slash (`/`) right?

If the structure is this and the URLs are exactly these, then it should work (there is no conflict between page slug `subpage/` and some regex which will match it).

But you are showing structure and URLs which are not the same as these that are giving you problems. When you show me the real structure and real `urls.py` that are causing you a problem then I can help you. Until then.... sorry I can't help you.

**Comment by horejsek** [comment] 2018-03-26 13:02
The URLs are those created by CMS, so Django will add last slash but it's not in the database.

Yes, structure and `urlpatterns` of app hook have no conflict.

It's random as I described in the description. Sometimes it works, sometimes not, where not can mean more situations. I haven't noticed any pattern yet.

**Comment by vstoykov** [comment] 2018-03-26 13:33
I know that URLs are created by CMS and the slash is not in the DB. This is how Django CMS works.

You say that there is no conflict between structure of the pages and the `urlpatterns` but until you show us the actual structure and your `urlpatterns` and on which page(s) it happens I will be 100% sure that there is a conflict which you are missing.

**Comment by horejsek** [comment] 2018-03-27 11:03
We have two apps. One has this `urlpatterns`:

```python
urlpatterns = [
    url(r'^$', views.index),
    url(r'^providers/$', views.providers),
    url(r'^providers/compare/$', views.compare_providers),
    url(r'^provider/(?P<provider_id>[0-9]+)/$', views.provider),
    url(r'^provider/(?P<provider_id>[0-9]+)/edit/$', views.edit_provider),
    url(r'^provider/(?P<provider_id>[0-9]+)/networks/$', views.provider_networks),
    url(r'^provider/(?P<provider_id>[0-9]+)/participants/$', views.provider_participants),
    url(r'^provider/(?P<provider_id>[0-9]+)/users/$', views.provider_users),
    url(r'^participants/$', views.participants),
    url(r'^participant/(?P<participant_id>[0-9]+)/$', views.participant),
    url(r'^participant/(?P<participant_id>[0-9]+)/providers/$', views.participant_providers),
    url(r'^organization/(?P<organization_id>[0-9]+)/$', views.organization),
    url(r'^organization/(?P<organization_id>[0-9]+)/providers/$', views.organization_providers),
]
```

Which was registered and under page with this app user created page with a slug `founding`. There shouldn't be any collision.

And also we have another app with the following `urlpatterns`:

```python
urlpatterns = [
    url(r'^$', views.events),
    url(r'^(?P<event_slug>[\w-]+)/$', views.event),
    url(r'^(?P<event_slug>[\w-]+)/register/$', views.event_registration),
    url(r'^(?P<event_slug>[\w-]+)/submit-proposal/$', views.proposal),
    url(r'^(?P<event_slug>[\w-]+)/proposal/(?P<proposal_id>[0-9]+)/$', views.proposal),
    url(r'^(?P<event_slug>[\w-]+)/proposal/(?P<proposal_id>[0-9]+)/voting$', views.proposal_voting),
    url(r'^(?P<event_slug>[\w-]+)/programme/block/$', views.programme_block),
    url(r'^(?P<event_slug>[\w-]+)/programme/block/(?P<block_id>[0-9]+)/$', views.programme_block),
    url(r'^(?P<event_slug>[\w-]+)/presentation/(?P<presentation_id>[0-9]+)/attachments$', views.presentation_attachments),
    url(r'^(?P<event_slug>[\w-]+)/presentation/(?P<presentation_id>[0-9]+)/detail', views.presentation_detail),
    url(r'^(?P<simple_event_id>[0-9]+)/export', views.simple_event_export_to_ics),
    url(r'^(?P<event_slug>[\w-]+)/export', views.event_export_to_ics),
]
```

Where I can see possible conflict with user page with a slug `code-conduct` because of the second URL. Anyway I wouldn't expect it sometimes works and sometimes not as I described and it had the same problem with both apps.

**Comment by vstoykov** [comment] 2018-03-27 15:50
Ok now to define what you mean by "not working". The page with slug `founding` sometimes shows correctly and sometimes return 404 or render some other page?

The same question for the `code-conduct` page?

If you say that adding pages under first app always work as expected and pages under the second app sometimes work (if there are numbers, underscores, or some nonascii characters, or are not direct children of the page with the attached app) and sometimes does not (render `views.event` or return 404 because there is no event with the given slug), then the problem is in the second app and is very normal behavior considering how Django URLs work.

Also you have URLs which can collide grand children of the second app if their slug start with `export` because your regex is too greedy (last two). And one more URL which is also too greedy (`views.presentation_detail`), but is very unlikely (IMHO) for your client to create such a page.

If you want to have CMS pages at the level of `event` pages then you have two options:

  1. Modify the regex a little bit to add some prefix/suffix to the event slug in order to not conflict with CMS pages. Can be very ugly and there is a chance to not be liked by the client.
  2. Make your `views.event` view smart and if there is no event with given slug to try to use [`cms.views.details`](https://github.com/divio/django-cms/blob/release/3.5.x/cms/views.py#L38-L169) to render the page. This is more complicated but will make your app to play nicely with the CMS.

**Comment by horejsek** [comment] 2018-03-28 10:43
We probably don't understand each other. The same problem we had with both apps, not just with that second one which can have problem with a conflict. Even in first app where is not page starting /founding, it had problem. Problems are random, can exactly say what it does. I described in the description already:

> (...) sometimes in doesn't work at all (all the time error 404), sometimes it doesn't work only when I'm in published mode and go into edit mode (only during the action, when I'm already in edit mode, it works), sometimes it works just fine. I'm not able to reproduce it the same way all the time.

I don't need pages at the event level so we don't have to deal with that. Let's focus on the first app, where is clearly no greedy URL (at least from the beginning of URL) and we created on root of the app hook level another page with a slug `funding` which did the problems mentioned. Interestingly it behaved differently after restart, sometimes not.

**Comment by vstoykov** [comment] 2018-03-28 12:54
Ok this will happen only on production or it happens during development?

You said that it behaved differently after restart. By behaving differently you mean that it starts working or it start breaking? In the past it was necessary to restart the server after publishing a page with app hook. I think that in latest version of Django CMS they tried to remove the need of restart by magically reloading the URLs but I'm not sure how well this works.

Also I see that you linked #6307. Are these problematic pages descendants of the Root node?

I'm not sure also what is your knowledge about how Django CMS handle URLs of apphooks under the hood. It will be very helpful if you can investigate what is the problem in your case to see if Django CMS is doing something strange which can be fixed (I know that you said that it is random, but probably there is logical explanation).

@czpython said that pages under apphooks was never truly supported which does not mean "unsupported". In the past we have problem with apphook inside another apphook (yeah definitely  not everyday problem) and there was also problem with that sometimes it worked sometimes it not. But I found where the problem was and proposed a solution which they accepted (#4121).

What I want to say is that this the functionality to have children under pages with attached application is not advertised but this does not mean that it's not there. If you can find the problem and probably suggest solution or at least clear steps to reproduce it, then it will be fixed for your case.

And again about your problem. Try to reproduce it in dev environment (copy the production DB if needed to your machine). When you see 404 with `DEBUG=True` you will see at least which is the view that is returning 404 and probably for what reason.

**Comment by horejsek** [comment] 2018-04-10 12:11
Going to respond to your paragraphs:

1. Both, development and production.
2. By differently I mean as I described all weird states, that after restart it sometimes change the state. For example I add page under app hook and then it shows 404, after restart it may work but it will show 404 during switching of edit/published mode.
3. The problem is only with pages under app hook.
4. Definitely there will be some logical explanation, but I don't know where to look or what to debug as it's changing the way how it react. It's hard then to debug something in case when I know almost nothing about Django CMS internals. That's why I created this issue as probably someone with knowledge maybe can have idea in few seconds than me debuging days. For us was simpler to just say to our users to not use it, at least for now.

**Comment by vstoykov** [comment] 2018-04-11 12:19
@horejsek did you manage to try what I described in my last paragraph?

> And again about your problem. Try to reproduce it in dev environment (copy the production DB if needed to your machine). When you see 404 with `DEBUG=True` you will see at least which is the view that is returning 404 and probably for what reason.

The important thing is to see Django's 404 error page during `DEBUG=True`.  Did you see 
```
Raised by: cms.views.details
```
or the value of `Raised by` is something different?

If it is `cms.views.details` then the issue is in the CMS and you can install DjangoCMS from source in your environment and start messing with this view to inspect when this is happening. This is the way you can learn how DjangoCMS is resolving an URL to a page. After this experience you will know more about Django CMS internals ;)

**Comment by horejsek** [comment] 2018-04-11 12:42
As I said, it's random which makes it very hard. We don't have time capacity to learn what is happening in details so we asked our users to not use this feature. If we did, I would even post pull request. So I at least notified Django CMS team about this problem so it can be fixed for other users or at least blocked totally if it's not supported. Both solutions works for me.

**Comment by czpython** [comment] 2018-04-11 14:34
We are discussing / planning to change the core apphook logic for 3.6, one of the features discussed is to officially support pages under apphooks. In the meantime, we've updated the docs to warn against this https://github.com/divio/django-cms/pull/6318.

**Closed by czpython** 2018-04-11 14:34 UTC
Labels: component: documentation, status: accepted
