### ISSUE TITLE
Using scroll bar of plugin menu in Firefox & IE moves plugins

### ISSUE THREAD

**Issue by o-zander** [divio/django-cms#4407] opened 2015-08-31 15:27 UTC
A customer found a bug on Firefox (36+ verified) and IE (seems to be alls versions) while using the scroll bar of the plugin menu. When the menu is open and the scroll bar is used by dragging it with the mouse, underlying plugin is selected and moved. The problem doesn't occur in the placeholder menu and not on Chrome. django-cms 3.1 and 3.1.2 were checked.

**Comment by yakky** [comment] 2015-08-31 16:21
@FinalAngel likely target for fixing this is 3.2, right?

**Comment by FinalAngel** [comment] 2015-08-31 16:28
@yakky most likely - /cc @vxsx

**Comment by vxsx** [comment] 2015-08-31 17:31
@FinalAngel cannot reproduce on `preview` 3.2 branch possibly because we changed the hover trigger behaviour

**Comment by yakky** [comment] 2015-09-13 10:21
Fixed by #4415

**Closed by yakky** 2015-09-13 10:21 UTC
Labels: component: frontend
