### ISSUE TITLE
Create a new Child issue.

### ISSUE THREAD

**Issue by JostCrow** [divio/django-cms#4576] opened 2015-10-12 16:05 UTC
When creating a sub page an error occured

### recreate the bug.
1. Create a sub page (via the arrow).
2. Delete the sub page.
3. Add a sub page again.

This error has to do with the fact that treebeard still has a numchild on the parentpage. Therefor the parentpage is not a leaf so it will create the page as an extra child but it really is the first child.

**Comment by yakky** [comment] 2015-10-12 17:29
@JostCrow which CMS version are you using?

**Comment by JostCrow** [comment] 2015-10-12 19:47
I started with 3.1.2 and upgraded to 3.1.3 after the bug appeared

On Mon, 12 Oct 2015 19:29 Iacopo Spalletti <notifications@github.com> wrote:

> @JostCrow <https://github.com/JostCrow> which CMS version are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/divio/django-cms/issues/4576#issuecomment-147468893>.
>
-- 

Jorik Kraaikamp

**Comment by yakky** [comment] 2015-10-12 20:10
So you're still experiencing this in 3.1.3?

**Comment by JostCrow** [comment] 2015-10-13 06:12
Yes

On Mon, 12 Oct 2015 22:10 Iacopo Spalletti <notifications@github.com> wrote:

> So you're still experiencing this in 3.1.3?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/divio/django-cms/issues/4576#issuecomment-147506262>.
>
-- 

Jorik Kraaikamp

**Comment by yakky** [comment] 2015-10-13 06:54
While this was an issue in 3.1.2, I cannot reproduce on a  clean 3.1.3 / Django 1.7 project

**Comment by yakky** [comment] 2015-11-13 06:57
@JostCrow would you try https://github.com/yakky/django-cms/tree/feature/treebeard?

**Comment by yakky** [comment] 2015-11-16 15:22
@JostCrow tentative fix at #4717

**Comment by yakky** [comment] 2015-11-17 05:07
Closed by #4717

**Closed by yakky** 2015-11-17 05:07 UTC
Labels: blocker, has patch
