### ISSUE TITLE
Overwrite Url breaks page copy

### ISSUE THREAD

**Issue by SteinRobert** [divio/django-cms#6057] opened 2017-08-25 15:52 UTC
### Summary

Copying a page which uses an overwrite url breaks both pages - the original and the copy.

### Expected behaviour

It should be possible to copy pages which have set an overwrite url. For the copy the overwrite url should be reset or set to a path which isn't used.

#### Actual behaviour

Both pages - the copy and the original page break the function `get_page_from_path`.
It returns a `MultipleObjectsReturned` exception.

#### Environment

* Python version: 2.7.10
* Django version: 1.8.17
* django CMS version: 3.4.4

**Comment by czpython** [comment] 2017-08-25 15:56
Thanks for reporting.
Closing as duplicate of https://github.com/divio/django-cms/issues/5311

**Closed by czpython** 2017-08-25 15:56 UTC
