### ISSUE TITLE
Toolbar CSS & JS raise exception with ManifestStaticFilesStorage and Django 1.10

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#5963] opened 2017-05-07 12:27 UTC
### Summary

When using DjangoCMS with Django 1.10 and the `ManifestStaticFilesStorage` backend, you'll get the following error:

`ValueError: The file 'cms/css/cms.base.css' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7fc5632c9550>.`

It seems that it comes from the following change in [Django 1.10](https://docs.djangoproject.com/en/1.11/releases/1.10/):

> If django.contrib.staticfiles is installed, the static template tag uses the staticfiles storage to construct the URL rather than simply joining the value with STATIC_ROOT. The new approach encodes the URL, which could be backwards-incompatible in cases such as including a fragment in a path, e.g. {% static 'img.svg#fragment' %}, since the # is encoded as %23. To adapt, move the fragment outside the template tag: {% static 'img.svg' %}#fragment.

And that's caused by the `static_with_version` templatetag that calls `django.templatetags.static.StaticNode.url` with a URL that hasn't been patched to include the version number, leading to a file that doesn't exist (and causing the above exception to be raised).

### Expected behaviour

No exception raised. 🌞 

#### Actual behaviour

Exception raised. 😭 

#### Environment

* Python version: 3.4.2
* Django version: 1.10.7
* django CMS version: 3.4.3

**Comment by czpython** [comment] 2017-05-07 14:08
Thanks @sephii.
I'm closing this as duplicate of https://github.com/divio/django-cms/issues/5740

**Closed by czpython** 2017-05-07 14:08 UTC
