### ISSUE TITLE
NamespaceAlreadyRegistered

### ISSUE THREAD

**Issue by lory87** [divio/django-cms#4666] opened 2015-11-06 10:55 UTC
If I delete every page in the cms and create a new page which is named like one before like home the it appears this error. NamespaceAlreadyRegistered

**Comment by mkoistinen** [comment] 2015-12-03 13:51
The seems related to an apphook that you have/had registered. Can you repeat this in 3.2.0?

**Comment by czpython** [comment] 2016-08-27 02:51
Closing as we're unable to reproduce this on the latest version.

**Closed by czpython** 2016-08-27 02:51 UTC
Labels: needs more info
