### ISSUE TITLE
Djangocms failed in install because timezone incorrect

### ISSUE THREAD

**Issue by lukasgarcya** [divio/django-cms#5713] opened 2016-09-30 13:46 UTC
I try install the Django CMS and I receive the error: ValueError: Incorrect timezone setting: local
The installation has failed.

![error djangocms](https://cloud.githubusercontent.com/assets/1985696/18993765/2c4ac1bc-86fb-11e6-8b48-d6c8e6337848.png)

**Comment by czpython** [comment] 2016-10-02 16:46
Thanks for reporting @lukasgarcya.
Closing this as duplicate of https://github.com/nephila/djangocms-installer/issues/291

**Closed by czpython** 2016-10-02 16:46 UTC

**Comment by lukasgarcya** [comment] 2016-10-02 17:22
Thank You.
@czpython Do you have any solution?
