### ISSUE TITLE
Unknown column 'cms_cmsplugin.level when running plugin migrations

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#4357] opened 2015-08-13 13:38 UTC
For example, migrating Aldryn Events:

```
./manage.py migrate aldryn_events 
/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/parler/forms.py:198: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form EventAdminForm needs updating 
return super(TranslatableModelFormMetaclass, mcs).__new__(mcs, name, bases, attrs)

Operations to perform: 
Apply all migrations: aldryn_events 
Running migrations: 
Applying aldryn_events.0007_set_default_namespaces...Traceback (most recent call last): 
File "./manage.py", line 10, in <module> 
execute_from_command_line(sys.argv) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line 
utility.execute() 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute 
self.fetch_command(subcommand).run_from_argv(self.argv) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv 
self.execute(*args, **options.__dict__) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute 
output = self.handle(*args, **options) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle 
executor.migrate(targets, plan, fake=options.get("fake", False)) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate 
self.apply_migration(migration, fake=fake) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration 
migration.apply(project_state, schema_editor) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 105, in apply 
operation.database_forwards(self.app_label, schema_editor, project_state, new_state) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards 
self.code(from_state.render(), schema_editor) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/aldryn_events/migrations/0007_set_default_namespaces.py", line 32, in create_default_namespaces 
app_config__isnull=True)) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 141, in __iter__ 
self._fetch_all() 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all 
self._result_cache = list(self.iterator()) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator 
for row in compiler.results_iter(): 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter 
for rows in self.execute_sql(MULTI): 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql 
cursor.execute(sql, params) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute 
return super(CursorDebugWrapper, self).execute(sql, params) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute 
return self.cursor.execute(sql, params) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__ 
six.reraise(dj_exc_type, dj_exc_value, traceback) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute 
return self.cursor.execute(sql, params) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute 
return self.cursor.execute(query, args) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute 
self.errorhandler(self, exc, value) 
File "/home/user/lala/workspace/django/intranet_cms/virtualenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler 
raise errorclass, errorvalue 
django.db.utils.OperationalError: (1054, "Unknown column 'cms_cmsplugin.level' in 'field list'")
```

The migration is trying to use the old (Django MPTT) ``level`` attribute, which no longer exists.

**Comment by evildmp** [comment] 2015-08-13 13:41
@frague59 for your information.

**Comment by yakky** [comment] 2015-08-15 11:16
@frague59 @czpython could you check the fix suggested in above PR?

**Comment by yakky** [comment] 2015-08-15 14:03
@evildmp could you review the text?

**Comment by mkoistinen** [comment] 2015-08-17 15:58
LGTM.

**Comment by yakky** [comment] 2015-08-18 06:30
Merging it and closing this

**Comment by yakky** [comment] 2015-08-18 06:31
Closed by #4364

**Closed by yakky** 2015-08-18 06:31 UTC
Labels: component: documentation, has patch, kind: bug, status: accepted

**Comment by jstacoder** [comment] 2015-08-19 19:43
so where do i add 

```python
 from distutils.version import LooseVersion
 import cms
 USES_TREEBEARD = LooseVersion(cms.__version__) >= LooseVersion('3.1')

 class Migration(migrations.Migration):

    if USES_TREEBEARD:
        run_before = [
            ('cms', '0004_auto_20140924_1038')
         ]
```
adding to the aldryn_events migration file causes this error:

```python
KeyError: u"Migration aldryn_events.0007_set_default_namespaces dependencies reference nonexistent child node (u'cms', u'0004_auto_20140924_0138')"
```

any ideas?

**Comment by jstacoder** [comment] 2015-08-19 20:44
ahh, i had to delete the database for it to complete

**Comment by jstacoder** [comment] 2015-08-20 18:06
trying to duplicate this, i found the issue was when migrations were applied automatically when creating a project, if that was done, the tables must be dropped, including the `django_migrations` table, so it will run through them again, waiting to complete the offending migrations before doing the standard Django ones after running `cms.0003_auto_20140926_2347`

**Comment by yakky** [comment] 2015-08-20 21:01
@jstacoder how do you create initial migrations? Which CMS version in your project?

**Comment by jstacoder** [comment] 2015-08-20 21:08
@yakky  the initial migrations were created and applied when i created my project using the `djangocms` command, im not sure exactly what version of the CMS project it is using, when it asks during generation which version to use, i have been using the default `stable` version, and for django i have been using `version 1.7`

**Comment by yakky** [comment] 2015-08-20 21:12
@jstacoder so, just to clarify the steps:

* pip install djangocms-installer ## version 0.7.9
* djangocms -p . testprj ## select all default, cms version = stable (==3.1), Django = 1.7
after the project setup
* pip install aldryn-events ## and patch it as above
* ... all the aldryn-events configuration setup
* python manage.py migrate
* ... error...

Am I correct?

**Comment by cyberstar** [comment] 2015-08-21 10:26
@jstacoder please try to reproduce with https://github.com/aldryn/aldryn-events/pull/155 (not merged yet) applied.

@yakky the issue comes if you will migrate cms without aldryn-events listed in installed apps, then add aldryn_events+deps and try to migrate... should be fixed after mentioned pr would be merged.

**Comment by jstacoder** [comment] 2015-08-21 16:02
Ahh, that makes sense, I've been trying to reproduce it again, with no luck, but that sounds like what I did originally. Ok I'll try to see if #155 works for the issue, I really appreciate your help and the responses.

Thank You,
Kyle Roux | Level 2 Designs Inc. | Developer
________________________________
(P: 714-888-4557<tel:714-888-4557> xtn. 307)
(F: 714-455-2115<tel:714-455-2115>)
Email: kyle@Level2Designs.com<mailto:kyle@level2designs.com>
1045 W. Katella Ave.<x-apple-data-detectors://5/3>
Suite<x-apple-data-detectors://5/3> #350
Orange, CA 92867
For emergency support, please call:
714-888-4557<tel:714-888-4557> xtn. 2
or email:
support@level2designs.com<mailto:support@level2designs.com>
CONFIDENTIALITY NOTE:The information contained in this transmission is for business purposes and is privileged
and confidential information intended only for the use of the individual or entity named above. If you are not
the intended recipient, any dissemination, distribution or copying of this communication is strictly prohibited.
If you have received this transmission in error, please return to the sender and delete it.


On Aug 21, 2015, at 3:27 AM, "Kirill Kniazev" <notifications@github.com<mailto:notifications@github.com>> wrote:


@jstacoder<https://github.com/jstacoder> please try to reproduce with aldryn/aldryn-events#155<https://github.com/aldryn/aldryn-events/pull/155> (not merged yet) applied.

@yakky<https://github.com/yakky> the issue comes if you will migrate cms without aldryn-events listed in installed apps, then add aldryn_events+deps and try to migrate... should be fixed after mentioned pr would be merged.

-

**Comment by czpython** [comment] 2015-08-24 20:59
@yakky I believe I've encountered a similar issue but would like to clarify if it falls under the same documentation suggestion.

I've got a 3.0.14 project, upgraded it to 3.1.2, running django 1.6.11.

When running migrations, the cms ran and then aldryn-style, but it tries to migrate https://github.com/aldryn/aldryn-style/blob/master/aldryn_style/south_migrations/0004_move_additional_class_names_to_text_field.py
which fails with ```django.db.utils.ProgrammingError: column cms_cmsplugin.rght does not exist```. Does this mean that we'd have to add the depends_on for all datamigrations on all apps that have migrations made prior to 3.1?

**Comment by yakky** [comment] 2015-08-25 06:37
@czpython yes, it's the same issue. Datamigrations needs ``needed_by``/``run_before`` on first 3.1 migration, if the plugins are meant to work both on 3.0 and 3.1 (dependency it's not enough to guarantee that the datamigration is run before 3.1 migrations)

**Comment by jstacoder** [comment] 2015-08-25 07:19
ok @yakky , @cyberstar aldryn/aldryn-events#155 did the trick, i was able to reproduce, like you said, by applying the inital migrations, then adding aldryn-events then running migrate, there was an issue though, after running `djangocms -p . my_site`  picking all defaults, except django 1.7, when i went to install aldryn/aldryn-events#155, i got this error 

```
Processing dependencies for aldryn-events==1.0.4
error: html5lib 0.999999 is installed but html5lib<0.9999 is required by set(['django-cms'])
```
but i was able to bypass that by just doing
```bash
pip install 'html5lib<0.9998'
```
after that 
```
python manage.py migrate
```
worked like a charm

**Comment by yakky** [comment] 2015-08-25 15:13
@jstacoder the htmllib version issue will be fixed in next CMS release
