### ISSUE TITLE
copy_plugin in frontend leads to a 302 redirect to http:// instad of https://

### ISSUE THREAD

**Issue by SachaMPS** [divio/django-cms#4215] opened 2015-06-25 14:08 UTC
CMS: 3.1
Django: 1.6

##### Description
We have an SSL secured Site running the CMS. We couldnt copy plugins in the frondend because of the  response which is returned from django cms which contained a 302 Moved Temporarily and a unsecure http:// adress

##### The error
Browser complains about mixed content (https / http) and stops processing the response

##### The request
Request URL:https://xxxxxxx.de/admin/cms/page/clear-placeholder/1908/
Request Method:POST

##### The response contained the following location
Status Code:302 Moved Temporarily
Location: http://xxxxxxx.de/admin/

##### The intermediate solution (for anyone interested)
Add the following to your location in nginx (or similar for anything else than nginx)
proxy_set_header   X-Forwarded-Proto https;

**Comment by yakky** [comment] 2015-06-25 16:17
@SachaMPS How is setup the Site object in the admin?

**Comment by SachaMPS** [comment] 2015-06-25 16:23
Do you mean this:?
![image](https://cloud.githubusercontent.com/assets/305877/8359529/4734f0d4-1b67-11e5-94ed-db20637b7ed1.png)

**Comment by yakky** [comment] 2015-06-25 16:31
Yes
I double checked, anyway, and the path to copy the plugins is domainless: 

    <script>
    (function($) {
    // CMS.$ will be passed for $
    $(document).ready(function () {
    new CMS.Plugin('cms_plugin-13233', {
    'type': 'plugin',
    'page_language': 'it',
    'placeholder_id': '2377',
    'plugin_name': 'Blocco Immagine',
    'plugin_type': 'NphMediaBlock',
    'plugin_id': '13233',
    'plugin_language': 'en',
    'plugin_parent': 'None',
    'plugin_order': '',
    'plugin_breadcrumb': [{"url": "/admin/cms/page/edit-plugin/13233/", "title": "Blocco Immagine"}],
    'plugin_restriction': [],
    'onClose': false,
    'urls': {
    'add_plugin': '/admin/cms/page/add-plugin/}',
    'edit_plugin': '/admin/cms/page/edit-plugin/13233/',
    'move_plugin': '/admin/cms/page/move-plugin/',
    'delete_plugin': '/admin/cms/page/delete-plugin/13233/',
    'copy_plugin': '/admin/cms/page/copy-plugins/'
    }

    });
    });
    })(CMS.$);
    </script>

So the browser should just use the https path. Is there any file loaded from ``non-https`` addresses?
I can't reproduce with the same setup as yours

**Comment by SachaMPS** [comment] 2015-06-25 16:35
@yakky The problem is not the outgoing request from the browser... Its the response The request uses an https:// path but the response contains the 302 status code and a location to a none http:// path.

(I used firefox dev tools because they gave me the most insight what happened)

The request which produced this was:
https://xxxxxxx.de/admin/cms/page/clear-placeholder/1908/

**Comment by yakky** [comment] 2015-06-25 16:50
This is the response I get on an example https website:

    Status: 302
    Cache-Control: max-age=0
    Connection: keep-alive
    Content-Language: it
    Content-Type: text/html; charset=utf-8
    Date: Thu, 25 Jun 2015 16:46:24 GMT
    Expires: Thu, 25 Jun 2015 16:46:24 GMT
    Last-Modified: Thu, 25 Jun 2015 16:46:24 GMT
    Location: https://example.com/admin/
    Server: nginx
    Set-Cookie: messages="...."; Path=/
    Transfer-Encoding: chunked
    Vary: Accept-Language, Cookie
    X-Frame-Options: SAMEORIGIN

Note the ``Location: https://example.com/admin/``
Any special middleware which may prevent Django to "understand" it's an https request? Maybe the frontend proxy turns the request to plain http to the internal applications server?

**Comment by SachaMPS** [comment] 2015-06-25 16:57
@yakky I will again look into our setup... If you're getting https it seems as it must be part of our setup and not the cms itself. Anyhow its weird because we even redirect immediately from http to https on every page load and there didn't occure any other similar errors. 

Think you can close this issue and i will come back if i found somehting more specific

**Comment by yakky** [comment] 2015-06-25 17:12
Using i18n_url_patterns is recommended, but I cannot see how this could affect the behavior (btw: the above website is a multi-site setup with only one of the website under https, both using USE_I18N and i18n_url_patterns)

**Comment by evildmp** [comment] 2015-07-06 11:29
@SachaMPS Is it it possible that your browser has remembered a permanent redirect, and is acting on that? I have had some mysterious browser/HTTP interactions of this kind that produced some very odd behaviour.

**Comment by SachaMPS** [comment] 2015-07-08 08:12
@evildmp No, i am pretty sure not... To get more details on the request i switched to firefox and saw the problem directly also in Firefox. And i actually never use firefox so chances for a caching problem don't seem very probable. If you want i can give you all the details about our setup, maybe s.th. catches your eye then.

**Comment by yakky** [comment] 2015-07-08 11:48
@SachaMPS that would help,, thanks

**Comment by evildmp** [comment] 2015-09-16 15:02
Hi @SachaMPS have you got any further with this? We have a similar issue #4432, and again it's hard see how it could be a CMS issue rather than a server configuration matter.

**Comment by SachaMPS** [comment] 2015-09-16 15:06
@evildmp Sorry, we since then lived with our solution to solve this via nginx.

**Comment by yakky** [comment] 2015-09-23 06:43
@SachaMPS thanks for the feedback. Closing this, then

**Closed by yakky** 2015-09-23 06:43 UTC
Labels: needs more info

**Comment by zhangguiyu** [comment] 2016-04-04 08:25
We faced a similar predicament, we have a nginx proxy with SSL on the gateway, while in the backend we have nginx (no SSL) with uwsgi. Some of Django-CMS admin edits just stalled after submission, notably the "unpublish", "publish", "resolve" URLs.

In the end we did 2 things:

1) HTTPS NGINX PROXY:

sites-enabled/gateway.conf:

    location / {
        proxy_pass http://LAN_ADDRESS_RUNNING_NGINX_UWSGI/;
        proxy_set_header Host $http_host;   # required for django 1.5
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # HTTPS -------------- combine following with django settings:
        # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
        proxy_set_header X-Forwarded-Proto https;       # WORKS: 2016.04.04
        ....

2) DJANGO settings.py

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

And everything works now

Reference:

http://stackoverflow.com/questions/9097404/django-is-redirecting-from-https-to-http

**Comment by macdelacruz** [comment] 2016-04-17 07:39
Accordingly SECURE_PROXY_SSL_HEADER should be used only if your SSL proxy strips all X-Forwarded-Proto header in incoming request. So to add to @rafael-queo `proxy_set_header X-Forwarded-Proto https` should be set to `proxy_set_header X-Forwarded-Proto $scheme` when using SECURE_PROXY_SSL_HEADER.

[https://docs.djangoproject.com/en/1.9/ref/settings/#s-secure-proxy-ssl-header](https://docs.djangoproject.com/en/1.9/ref/settings/#s-secure-proxy-ssl-header)

**Comment by philippeowagner** [comment] 2016-07-11 11:45
For reference only: https://github.com/divio/django-cms/issues/4432#issuecomment-231711675
