### ISSUE TITLE
static_with_version not resolving paths on S3

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#5922] opened 2017-04-06 15:17 UTC
I'm using `S3BotoStorage` from django-storages for static files which when it can't find files throws a 500 error. `static_with_version` is causing some grief with static files on S3.

Running locally `static_with_version` appears to be ok, returning `'/static/cms/css/3.4.2/cms.base.css'`

#### Actual behaviour
On a remote dev environment I'm seeing the following error generated;

> The file 'cms/css/cms.base.css' could not be found

However the versioned path does exist;

<img width="271" alt="screen shot 2017-04-06 at 16 13 33" src="https://cloud.githubusercontent.com/assets/1461191/24761717/210ef124-1ae4-11e7-87ec-697c65899579.png">

The first time I saw this I just copied the files into `cms/css/` but surely I shouldn't need to do that?

* Python version: 2.7.6
* Django version: 1.10.6
* django CMS version: 3.4.2

**Comment by czpython** [comment] 2017-04-08 15:04
Hello @marksweb,
We use the cms with S3 at Divio cloud without issue.
Did you run `collectstatic`?

**Comment by czpython** [comment] 2017-04-13 10:08
Hello @marksweb,
Are you using the manifest static file storage?

**Comment by marksweb** [comment] 2017-04-13 10:10
@czpython Hi, yes, these are my storage classes;

```python
from django.conf import settings
from django.contrib.staticfiles.storage import ManifestFilesMixin
from django.utils.deconstruct import deconstructible

from storages.backends.s3boto import S3BotoStorage


@deconstructible
class DeconstructableS3BotoStorage(S3BotoStorage):
    pass


@deconstructible
class MediaStorage(S3BotoStorage):
    location = '{sub_bucket}/{folder}'.format(
        sub_bucket=settings.AWS_S3_SUB_BUCKET,
        folder=settings.MEDIAFILES_LOCATION
    )

    def path(self, name):
        return self._normalize_name(name)


@deconstructible
class StaticStorage(ManifestFilesMixin, S3BotoStorage):

    # https://s3-{region}.amazonaws.com/{bucket}/{sub_bucket}/static
    location = '{sub_bucket}/{folder}'.format(
        sub_bucket=settings.AWS_S3_SUB_BUCKET,
        folder=settings.STATICFILES_LOCATION
    )
```

**Comment by czpython** [comment] 2017-04-13 10:17
Thanks for the update.
I believe this is a duplicate of https://github.com/divio/django-cms/issues/5740

**Comment by marksweb** [comment] 2017-04-13 10:21
@czpython yes, that looks like the same issue - I didn't pick that up when searching the issues, so apologies.

In the meantime I've got the workaround to simply copy the files over which isn't ideal, but it'll do until theres an official release.

I'm happy for you to close unless you think there is anything still useful in this issue?

**Comment by czpython** [comment] 2017-04-13 14:13
The reference should be enough, thanks for the follow-up.
Closing as duplicate of #5740.

**Closed by czpython** 2017-04-13 14:13 UTC
Labels: needs more info
