### ISSUE TITLE
Minor bug: First creating page view doesn't select action

### ISSUE THREAD

**Issue by FabrizioA** [divio/django-cms#5764] opened 2016-11-17 09:23 UTC
I've just installed Django CMS 3.4.1 in "by hand" mode following the only docs. All works ok, but when I launch the Web Server the system redirect me to Django Admin login page and then redirect me to Django CMS create page popup. If I select "New Page" (the only available action) and then I click to Next... I get this error:

https://www.dropbox.com/s/w32qg5grapoczh4/Schermata%202016-11-17%20alle%2010.17.33.png?dl=0

If I close the popup and reopen it by clicking on "Create" top left button I can select the "New Page" action and then click to next.

PS: small question: With a fresh installation of Django CMS 3.4.1, once I have followed the "Install by hand" section of docs, I get the welcome screen that I posted in my screenshot above.... not the blue screen of docs... it's normal?? :)

**Comment by czpython** [comment] 2016-11-17 12:17
Hello @FabrizioA,
I'm unable to reproduce this under a blank project with the latest djangocms-admin-style.
Can you check if `djangocms_admin_style` is in your `INSTALLED_APPS`?

**Comment by FabrizioA** [comment] 2016-11-17 14:26
Hi,

this is my INSTALLED_APPS list:

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'cms',  # django CMS itself
    'treebeard',  # utilities for implementing a tree
    'menus',  # helper for model independent hierarchical website navigation
    'sekizai',  # for JavaScript and CSS management
    'easy_thumbnails',
    'filer',
    'mptt',
    'djangocms_admin_style',  # for the admin skin. You **must** add 'djangocms_admin_style' in the list **before** 'django.contrib.admin'.
    'django.contrib.messages',  # to enable messages framework (see :ref:`Enable messages <enable-messages>`)
    'djangocms_file',
    'djangocms_googlemap',
    'djangocms_inherit',
    'djangocms_picture',
    'djangocms_teaser',
    'djangocms_video',
    'djangocms_link',
    'djangocms_snippet',
    'core_website',
]

Question: is normal that inside the window I have the header of Django Administration? With Django CMS 3.3 I did not have it.

**Comment by czpython** [comment] 2016-11-17 14:33
The problem is this line:
```
'djangocms_admin_style', # for the admin skin. You must add 'djangocms_admin_style' in the list before 'django.contrib.admin'.
```

You need to add it **before** `django.contrib.admin`

**Comment by FabrizioA** [comment] 2016-11-17 14:44
Ok, I have fixed the Django header inside the CMS window due to the wrong order of 'djangocms_admin_style'.

But, the problem of first create page action is still here. To create one first page, I need to close the "auto-opened" popup and click to the top right create button.
It is a low priority bug... nothing that be very important.

**Comment by czpython** [comment] 2016-11-17 14:50
@FabrizioA Would you mind sharing a screencast of the steps you're taking to reproduce the bug?

**Comment by FabrizioA** [comment] 2016-11-17 15:03
@czpython I have installed Django CMS by hand following: http://docs.django-cms.org/en/release-3.4.x/how_to/install.html

then, I go to http://localhost:8000/it/  
I login into django-cms admin page
and django-cms redirect me to welcome screen with automatic create windows opened.

If I select the only action available (Nuova Pagina) and click Avanti I get the error below.

https://www.dropbox.com/s/9gm6ynloyze353b/Schermata%202016-11-17%20alle%2016.00.40.png?dl=0

to solve it I need to close the window and reopen it by clicking "Crea" button in the top right of window.
Then I select the only "Nuova Pagina" button available and I can click "Avanti" without problems.

It seems to be a javascript or client side code problem.

**Comment by czpython** [comment] 2016-12-28 18:44
Closing as duplicate of https://github.com/divio/django-cms/issues/5828

**Closed by czpython** 2016-12-28 18:44 UTC
Labels: needs more info
