### ISSUE TITLE
Admin interface: Add page in the top right corner does not always check for duplicate slugs

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#3767] opened 2015-01-15 20:58 UTC
I wasn't able to find this issue reported elsewhere, and I hope this is not a duplicate or already fixed.

Usually, I get a warning if I add a page with a slug which is already in use.

But I don't if I do this:
1.) In the admin interface, copy a page (I put the copy into the main menu)
2.) change the slug to 'foo'
3.) click on 'add page' in the top right corner
4.) make the new page slug 'foo'
4a.) NO WARNING!
5.) enjoy the Bad Gateway error / MultipleObjectsReturned() error

Regards, 
Moini

**Comment by sveetch** [comment] 2015-01-16 11:40
+1 got this also on a new project, with customer it is a little risky even if we warn about this bug, they probably will make the error

**Comment by sveetch** [comment] 2015-01-16 11:43
Seems related to #3548

**Comment by yakky** [comment] 2015-02-22 17:56
@Moini @sveetch could you check on 3.0.10? I can't reproduce this

**Comment by Moini** [comment] 2015-02-22 21:17
@yakky : these screenshots are with 3.09 still:
![bildschirmfoto - 22 02 2015 - 22 00 24](https://cloud.githubusercontent.com/assets/3240233/6320504/a6307e02-badf-11e4-8a5c-0e2d346fbe36.png)

![bildschirmfoto - 22 02 2015 - 22 01 17](https://cloud.githubusercontent.com/assets/3240233/6320506/ab64732e-badf-11e4-950f-6c6eb5311d69.png)

After upgrading to 3.10, I tried the (new? didn't see it in 3.09) 'insert above' after clicking on the copy icon in the pages overview, and it didn't insert anything as far as I could see, just like the others, 'insert below/insert inside'... 
I don't get an error message, it's just that nothing happens when I click on any of those arrows. Not even a rumbling of my hard disk (which I can usually hear whenever there's a db access).

Can't reproduce, because I can't use the copy function I used before. Are there any known incompatibilities? Or am I doing something terribly wrong?

**Comment by yakky** [comment] 2015-02-22 21:31
Could you try running ``manage.py cms fix-mptt``?
The three insert function and copy/paste works and no change related to these functions is in 3.0.10.
My guess is that the mptt tree is has some errors which causes the insert / copy to fail.
You can debug this by opening the inspector and looking at the messages returned by the ajax calls

**Comment by Moini** [comment] 2015-02-22 21:52
@yakky , the fix-mptt command returns an error, in one of our own functions which is part of the cms-diff functionality. I don't know enough to give qualified info about that :( . 
I'll ask doctormo if he can help here.

**Comment by Moini** [comment] 2015-02-23 14:40
After commenting out our own cms-modifying apps from the settings.py, I was able to run fix-mptt without errors.
I still can't copy pages.
On the terminal, what I see after clicking on one of the arrows is: 
[23/Feb/2015 14:33:45] "POST /en/admin/cms/page/333/dialog/copy/ HTTP/1.1" 200 0

In the debugger in FF, I get this:
![bildschirmfoto - 23 02 2015 - 15 35 07](https://cloud.githubusercontent.com/assets/3240233/6329565/cbc2791c-bb71-11e4-88ea-a3194bd57ade.png)

I'm not sure if that is what you asked me to do, so please direct me if I did the wrong thing. If I had to guess, I'd say the part with 'No response body' is problematic...

**Comment by yakky** [comment] 2015-03-01 07:48
@Moini is ``CMS_PERMISSION`` enabled in the project? If so, do you get a dialog after clicking on the arrow-down icon?

**Comment by yakky** [comment] 2015-03-01 08:01
@Moini could you test #3908? that should re-enable copy feature when permission is disabled

**Comment by yakky** [comment] 2015-03-01 12:30
@Moini @sveetch please test #3911 for slug conflicts resolution

**Comment by Moini** [comment] 2015-03-01 14:40
@yakky No, we don't (yet) use CMS_PERMISSION, but we might in the future. I'll try to test the fixes tomorrow. Thank you!

**Comment by sveetch** [comment] 2015-03-01 15:30
Just checking with 3.0.10 without to set CMS_PERMISSION (so in default value at False) and when i just try to create another page with an existing slug, i have the validation error about existing slug.

But like @Moini i can't copy pages, will try to test the pull request.

**Comment by sveetch** [comment] 2015-03-01 17:04
@yakky Well, i tested the #3911 , validation in admin allways give me an error about existing slug when i try to use an existing one when creating a new page. Didn't test with the "copy" feature because it don't work too.

**Comment by yakky** [comment] 2015-03-01 19:37
@sveetch that's the intended behavior: parentless and first level pages share the same url space, so you can't assign the same slug to both

**Comment by Moini** [comment] 2015-03-02 22:01
@yakky: #3908 works fine :) - copying is possible again.

#3911 does not work for me - I can still insert and publish a page following the pattern in the bug report. 
If I *edit* the page settings via icon in the pages overview, then I immediately get a warning that the slug is already in use. But just 'add page' -> choose name -> save -> publish still gives me the double-slugs :-(

Does #3911 depend on any other changes made since the release of 3.0.10? 
I only copy-pasted your changes into 3.0.10.

**Comment by yakky** [comment] 2015-03-02 22:04
@Moini probably I misunderstood your flow

**Comment by yakky** [comment] 2015-03-02 22:12
@Moini I cannot replicate the issue.

This is the base situation:

    * Home
         * sub-1
         * sub-2
    * Another root

1. Copy ``sub-2`` by adding as child to ``Another root`` then I copy it as ``Home`` / ``Another root`` sibling
1. Edit the new ``sub-2`` page and change the slug to ``foo``
1. Click on ``Add Page``
1. The Page changeform is presented
1. Add a random title, se the slug to ``foo``
1. Validation error is shown

This by applying #3911 on top of 3.0.10

**Comment by Moini** [comment] 2015-03-02 22:30
@yakky I tried to make some screenshots of where I click, and of getting no warning, but now, I get warnings. 
So either I found another bug - and can't remember how to trigger it now - or I forgot to restart the server after copy-pasting your fixes. I guess it was the second option :( 
Sorry about that! And thank you very much for fixing this bug!

**Comment by yakky** [comment] 2015-03-02 22:31
@Moini could you confirm that the steps in my previous comment are correct to reproduce the original issue?
I'll merge #3911 tomorrow, so feel free to experiment more with it

**Comment by Moini** [comment] 2015-03-02 23:43
I would have liked to replay the situation with our own current trunk, but that one is broken at the moment...

But yes, the workflow you describe is almost the same I used 
(only in step 1, I only copied once, directly from sub1 to sub1-copy, but the result is the same, and does not depend on the copying, but only on the slug foo being used *inside /home* and *parallel to /home* (at the same, outermost level) at the same time)

(btw. I can't *move* pages now with (modified) 3.0.10, didn't check with unmodified 3.0.10 - is this known? 
I grab them, move them to their new place, drop them, they seem to be in the right place and I get a small 'Loading' in the top right corner, which never goes away. After a refresh, everything is back to the previous state. Should I make this a new bug?)

**Comment by yakky** [comment] 2015-03-03 05:19
The never disappearing loading label means the 'move' view returned a 500 error. Could you check the traceback? You can just open the network tab of the inspector and look at the response of the failed view. I tried moving around a few pages with no issue

**Comment by Moini** [comment] 2015-03-03 15:33
Okay, the problem is again in our own modifications... which I thought I had deactivated... :( 
Next time, I know where to find the traceback...
Good that I didn't open a new bug.
Thank you very much, @yakky , and sorry!

**Comment by mkoistinen** [comment] 2015-03-04 15:53
Fixed by #3911.

**Closed by mkoistinen** 2015-03-04 15:53 UTC
Labels: blocker, has patch, kind: bug, status: accepted
