### ISSUE TITLE
i18n URLs do not redirect on wrong language slug

### ISSUE THREAD

**Issue by stefanw** [divio/django-cms#4133] opened 2015-05-29 17:34 UTC
Consider the following URLs:

- `/de/kontakt/` main language contact page
- `/en/contact/` English language contact page

However, if somehow the prefix gets changed, the following happens:
- `/en/kontakt/` serves the English contact page, but with a German URL
- `/de/contact/` serves the German contact page, but with an English URL

I believe this to be a bug. I think there should be a check if the current path (after the language prefix) matches the resolved page and if not, redirect to the page using the correct language path/slug. This should happen in order to have canonical URLs for content.

I will try to provide a PR with a test, if you consider a redirect in this case to be a solution.

**Comment by yakky** [comment] 2015-05-30 14:53
Duplicate of #3548

**Comment by FinalAngel** [comment] 2015-10-29 21:36
Closed as duplicate

**Closed by FinalAngel** 2015-10-29 21:36 UTC
Labels: kind: bug, status: accepted
