### ISSUE TITLE
Apphook's menu item fails to appear in CMS toolbar unless the Page is published

### ISSUE THREAD

**Issue by evildmp** [divio/django-cms#3588] opened 2014-11-18 13:05 UTC
Steps to reproduce:

1. django-cms==3.0.6, aldryn-blog==0.4.5
1. create a new Page
2. assign the Blog application to the Page

I'd expect to see the **Blog** item in the toolbar like so:

![screenshot 2014-11-18 13 04 10](https://cloud.githubusercontent.com/assets/86222/5087737/890e5a72-6f23-11e4-9285-38aa769d0296.png)

However, unless the Page is published, the **Blog** item will not appear in the CMS toolbar on that Page. If the Page is published then unpublished, **Blog** will disappear.

**Comment by czpython** [comment] 2016-07-29 11:24
Closing as duplicate of #2605

**Closed by czpython** 2016-07-29 11:24 UTC
Labels: kind: bug, needs patch, status: accepted
