### ISSUE TITLE
Current site infos in session / not possible to use shared cookie for multisite installations

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#5650] opened 2016-09-01 12:43 UTC
Let's say I have foo.main-domain.com and bar.main-domain.com, both configured as django-cms sites. When I try to use

```
SESSION_COOKIE_DOMAIN = '.main-domain.com'
```

so my users would not need to login for each sub domain, the system behaves strange. It seems that the session keeps infos about current site, cached menu, etc, in the session, so it show for example the wrong menu (and the wrong site name in the toolbar)? I have the same problem (probably) when developing on my local machine (without SESSION_COOKIE_DOMAIN), it goes away when I work with foo.localhost and bar.localhost.

**Comment by benzkji** [comment] 2016-09-12 11:15
has already been discovered in #5609, I guess.

**Comment by czpython** [comment] 2016-12-24 21:12
Closing as duplicate of https://github.com/divio/django-cms/issues/5310

**Closed by czpython** 2016-12-24 21:12 UTC
