### ISSUE TITLE
Installing django-cms==3.2.5 tries to install html5lib==0.999999999

### ISSUE THREAD

**Issue by saeed-222** [divio/django-cms#5578] opened 2016-07-29 21:08 UTC
`
Collecting html5lib!=0.9999,!=0.99999,>=0.90 (from django-cms==3.2.5->-r requirements/base.txt (line 1))
  Downloading html5lib-0.999999999.tar.gz (245kB)
    Complete output from command python setup.py egg_info:
    html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 18.2)
`

**Comment by czpython** [comment] 2016-07-29 21:38
Closed as duplicate of #5564

**Closed by czpython** 2016-07-29 21:38 UTC
