### ISSUE TITLE
ImportError: cannot import name PageUser

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#3973] opened 2015-03-30 20:37 UTC
How to reproduce:

* django-1.6.x
* django-cms==3.0.x

substitute the usermodel as described [here](https://docs.djangoproject.com/en/1.6/topics/auth/customizing/#substituting-a-custom-user-model).

Run the application in uwsgi.

Then this import error will happen:

```
(...snip...)
   from cms.models.fields import PlaceholderField
  File "django-cms/cms/models/fields.py", line 2, in <module>
    from cms.forms.fields import PageSelectFormField
  File "django-cms/cms/forms/fields.py", line 8, in <module>
    from cms.forms.widgets import PageSelectWidget, PageSmartLinkWidget
  File "django-cms/cms/forms/widgets.py", line 14, in <module>
    from cms.models import Page, PageUser
ImportError: cannot import name PageUser
```

The problem here is that model ``PageUser`` wants to inherit from a customized model. This can't work and even if, one would have to recreate separate migrations.

There must be a reason, why referring to an alternative User model is not done the way, Django emphasizes it in its docs, say somethings like:

```
class PageUser(models.Model):
    user_ptr = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True)
    created_by = models.ForeignKey(user_model_label, related_name="created_users")

    class Meta:
        verbose_name = _('User (page)')
        verbose_name_plural = _('Users (page)')
        app_label = 'cms'
```

**Comment by jrief** [comment] 2015-03-31 09:54
By reading the code of **django-cms**, it seems impossible to substitute the usermodel. The reason is, that many models (``GlobalPagePermission``, ``PagePermission``, ``PageUser`` and ``UserSettings``) in django-cms refer onto the table ``auth_user``. This is hard coded and can only be changed if one would recreate all migrations for the cms. This certainly is not a very robust solution. 

Therefore I evaluated some alternative possibilities:

#### Replace the foreign key onto ``auth.User`` by an ``IntegerField``.
This is the preferred method for polymorphic models, but could be applied here as well. The tables ``GlobalPagePermission``, ``PagePermission``, ``PageUser`` and ``UserSettings`` then  would have a simple integer key pointing onto ``auth.User.id`` or onto a primary key from any model substituting ``auth.User``.

The disadvantage is, that we loose the database constraint on foreign keys.

#### Remove the current implementation hack
The current implementation makes more harm than benefit. The error as reported yesterday is caused by  [this ugly hack](https://github.com/divio/django-cms/blob/develop/cms/models/permissionmodels.py#L29). It is not very robust and portable to write programs, which run with ``./manage.py runserver`` but do not run under ``uwsgi``.

Then the programmer of a substituted ``AUTH_USER_MODEL`` has to take care that data is replicated between his user table and the ``auth_user`` table. 

The disadvantage is, that we replicate data, which is not DRY – but at least automated.

#### Transfer the responsibility for migrations onto the implementor of the third party app
If the implementor of the third party app substituting the model ``auth.User`` would add the field ``created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="created_users")`` (pointing to itself) to his own version of the User model, then the CMS permission system would work as before.

The disadvantage is, that the implementor then must create hist own migration files for **django-cms**.

@yakky I think you're the best person to decide how to proceed here.

**Comment by mkoistinen** [comment] 2015-03-31 20:24
Unable to reproduce. I've created a django CMS 3.0.12 project under Django 1.6 using a custom user model as per the docs. My code is here if anyone else wants to have a go: https://gist.github.com/mkoistinen/aae6aec979afe471e02f.

The project works as expected locally, so I then moved it to a Nginx server using µWSGI. It continues to work as expected.

I've provided this feedback to @jrief. Closing.

Naturally, if there's something I missed, please re-open.

**Closed by mkoistinen** 2015-03-31 20:24 UTC
