### ISSUE TITLE
cms.middleware.toolbar doesn't clear menu cache properly

### ISSUE THREAD

**Issue by heppstux** [divio/django-cms#5609] opened 2016-08-14 11:57 UTC
Using a plugin (with cache=False) in a static placeholder on a multi-Sites instance of DjangoCMS I figured out, that the toolbar-middleware doesn't clear the menu cache respecting the current SITE_ID.

Thus in edit-mode with activated toolbar my menu-plugin would render arbitrary navigation structure from other Sites.

**Comment by czpython** [comment] 2016-12-24 21:12
Closing as duplicate of https://github.com/divio/django-cms/issues/5310

**Closed by czpython** 2016-12-24 21:12 UTC
Labels: status: on hold
