### ISSUE TITLE
Documentation on adding PlaceholderField to existing model is unclear

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#5894] opened 2017-03-14 18:23 UTC
The docs only include the following note:

> If you add a PlaceholderField to an existing model, you’ll be able to see the placeholder in the frontend editor only after saving the relevant instance.

Unless there is some other bug going on in our project, it appears you must specifically save the model using the admin, if you save the relevant instance via the shell (or as part of a data migration), this will not create the placeholder. 

I've started digging through the code and see where on the PlaceholderField it will create the Placeholder instance, but it's not clear to me why this same code isn't called when saving from the shell. Appreciate any guidance but would like to get a simpler, documented path of running a data migration to handle this so we don't have to instruct editors to follow strange instructions for adding content.

**Comment by czpython** [comment] 2017-03-20 11:40
Hello @jsma,
The placeholder in a `PlaceholderField` should always be created on save, regardless of how the object was saved.

Can you post the code you're using in the shell to save the object?
And have you verified that the object is indeed being saved?

**Comment by czpython** [comment] 2017-04-02 15:50
Hello @jsma , I'm closing this as I'm unable to reproduce this with the latest 3.4.x release.

If you're still encountering this issue, please create a ticket on the [Users Mailing List](https://groups.google.com/forum/#!forum/django-cms) or Stackoverflow.

Make sure to include the Django, Django CMS and python versions used.

**Closed by czpython** 2017-04-02 15:50 UTC
Labels: needs more info
